//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareType
    {
        public int 車子編號 { get; set; }
        public string 所屬公司 { get; set; }
        public string 車子名稱 { get; set; }
        public string 種類 { get; set; }
        public string logo { get; set; }
        public Nullable<int> unit_pric { get; set; }
        public string Modify_Id { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public Nullable<int> Limit_Time { get; set; }
    }
}
