//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockEmp
    {
        public int Clock_Num { get; set; }
        public string Clock_Name { get; set; }
        public string Clock_Dept { get; set; }
        public string Clock_Hier { get; set; }
        public string Clock_Bname { get; set; }
        public string Clock_Scr { get; set; }
        public Nullable<System.DateTime> Clock_Sdate { get; set; }
        public string Clock_Stime { get; set; }
        public Nullable<System.DateTime> Clock_Edate { get; set; }
        public string Clock_Etime { get; set; }
        public string Clock_Class { get; set; }
        public Nullable<System.DateTime> Clock_Date { get; set; }
        public string Clock_BossId { get; set; }
        public string Clock_BossY { get; set; }
        public string Clock_Board { get; set; }
        public Nullable<System.DateTime> Clock_Dboard { get; set; }
        public string Clock_Mana { get; set; }
        public Nullable<System.DateTime> Clock_Dmana { get; set; }
        public string Clock_Bmana { get; set; }
        public Nullable<System.DateTime> Clock_Dbmana { get; set; }
        public string Clock_Hmana { get; set; }
        public Nullable<System.DateTime> Clock_Dhmana { get; set; }
        public string Clock_Contro { get; set; }
        public Nullable<System.DateTime> Clock_Dcontro { get; set; }
        public string Clock_Boss { get; set; }
        public Nullable<System.DateTime> Clock_Dboss { get; set; }
        public string Clock_Front { get; set; }
        public Nullable<System.DateTime> Clock_Dfront { get; set; }
        public Nullable<int> Clock_Day { get; set; }
        public Nullable<int> Clock_Time { get; set; }
    }
}
