//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComDetail
    {
        public string 借用編號 { get; set; }
        public Nullable<int> 電腦編號 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public string 小時 { get; set; }
        public int i { get; set; }
    }
}
