//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComeVisit
    {
        public int Visit_Num { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public string Visit_Time { get; set; }
        public string Visit_Company { get; set; }
        public string Visit_People { get; set; }
        public string Visit_Job { get; set; }
        public Nullable<int> Visit_Calls { get; set; }
        public string Visit_Orix { get; set; }
        public string Visit_Dep { get; set; }
        public string Visit_Renew { get; set; }
        public Nullable<System.DateTime> Visit_Update { get; set; }
        public Nullable<int> Visit_Hour { get; set; }
        public Nullable<int> Visit_ConfRoom { get; set; }
    }
}
