//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaticEmp
    {
        public int Atm_Num { get; set; }
        public string Mes_Start { get; set; }
        public string Mes_Stop { get; set; }
        public string LAW_Content { get; set; }
        public string Cust_Name { get; set; }
        public string Rul_Place { get; set; }
        public string Add_Name { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Corp_Acct { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string Rul_Other { get; set; }
        public Nullable<int> Fee { get; set; }
    }
}
