//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int SEQ { get; set; }
        public string ORD_CLASS { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> PROCED_CON { get; set; }
        public string BOSS { get; set; }
        public Nullable<System.DateTime> BOSS_DATE { get; set; }
        public string APLY_PERSON { get; set; }
        public Nullable<System.DateTime> APLY_DATE { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<System.DateTime> Mes_DelDate { get; set; }
        public string Mes_DelName { get; set; }
    }
}
