//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSign
    {
        public int Sign_Num { get; set; }
        public string Sign_Name { get; set; }
        public Nullable<System.DateTime> Sign_Time { get; set; }
        public string Sign_Boss { get; set; }
        public Nullable<System.DateTime> Sign_TBoss { get; set; }
        public string Sign_IP { get; set; }
        public string Sign_Pop { get; set; }
        public Nullable<System.DateTime> Sign_TPop { get; set; }
        public string Sign_S { get; set; }
    }
}
