//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int En_Num { get; set; }
        public string En_Date { get; set; }
        public string En_Name { get; set; }
        public string En_Start { get; set; }
        public string En_End { get; set; }
        public string En_NTime { get; set; }
        public Nullable<System.DateTime> En_Send { get; set; }
        public string En_Boss { get; set; }
        public Nullable<System.DateTime> En_State { get; set; }
        public Nullable<int> En_Leave { get; set; }
        public string En_Key { get; set; }
        public Nullable<System.DateTime> En_Write { get; set; }
        public Nullable<System.DateTime> En_DBoss { get; set; }
        public string En_Deal { get; set; }
        public string En_NCard { get; set; }
        public string En_Scr { get; set; }
    }
}
