//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiApplyDetail
    {
        public string 申請單號 { get; set; }
        public int 序號 { get; set; }
        public Nullable<int> 耗材代號 { get; set; }
        public Nullable<int> 申請數量 { get; set; }
    }
}
