//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpAllot
    {
        public int idx { get; set; }
        public string 公司別 { get; set; }
        public string 帳號 { get; set; }
        public string 合約編號 { get; set; }
        public string 戶名 { get; set; }
        public Nullable<decimal> 核准購買金額 { get; set; }
        public Nullable<decimal> 已撥付金額 { get; set; }
        public Nullable<decimal> 本次預撥金額 { get; set; }
        public Nullable<decimal> 手續費 { get; set; }
        public Nullable<decimal> 應扣除額保證金 { get; set; }
        public Nullable<decimal> 第一期款 { get; set; }
        public Nullable<decimal> 本次實撥金額 { get; set; }
        public Nullable<System.DateTime> 預撥日期 { get; set; }
        public string 付款方式 { get; set; }
        public Nullable<System.DateTime> 付款日 { get; set; }
        public string 備註 { get; set; }
        public System.DateTime 建檔日期 { get; set; }
        public string 標示刪除 { get; set; }
        public Nullable<System.DateTime> 核准日期 { get; set; }
        public string 核准人員 { get; set; }
        public string 建檔人 { get; set; }
        public string 編修人 { get; set; }
        public Nullable<System.DateTime> 修改日期 { get; set; }
        public string 會計課確認人 { get; set; }
        public Nullable<System.DateTime> 會計課確認日 { get; set; }
        public string 資金課確認人 { get; set; }
        public Nullable<System.DateTime> 資金課確認日 { get; set; }
        public string 供應商 { get; set; }
        public string 營業員 { get; set; }
        public Nullable<System.DateTime> 作業日 { get; set; }
        public string 計張 { get; set; }
        public string 肯美 { get; set; }
        public Nullable<System.DateTime> 起租日 { get; set; }
    }
}
