//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePage
    {
        public string 帳號 { get; set; }
        public string 員工編號 { get; set; }
        public string 英文名 { get; set; }
        public string 標題 { get; set; }
        public string 簡述 { get; set; }
        public Nullable<int> 頁筆數 { get; set; }
        public string 留言列顏色 { get; set; }
        public string 回覆列顏色 { get; set; }
        public string 回覆功能選擇 { get; set; }
        public string 照片 { get; set; }
        public string 背景圖片 { get; set; }
        public string 背景顏色 { get; set; }
        public string 文字顏色 { get; set; }
        public string 字型大小 { get; set; }
        public string 標題字型 { get; set; }
        public string 標題顏色 { get; set; }
        public string 興趣 { get; set; }
    }
}
