//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR6861
    {
        public string AtmC_NO { get; set; }
        public string WorkDate { get; set; }
        public string AtmCWeek { get; set; }
        public string AtmCWeekN { get; set; }
        public string AtmCCode { get; set; }
        public string AtmC { get; set; }
        public string IDNO_01 { get; set; }
        public string Name_01 { get; set; }
        public string LastModeDate { get; set; }
        public string LastModeTime { get; set; }
        public string LastModePs { get; set; }
        public string LastModeMn { get; set; }
        public string AtmCom { get; set; }
        public string AtmDep { get; set; }
        public string AtmSection { get; set; }
        public string AtmJob { get; set; }
        public string AtmCause { get; set; }
        public string AtmCauseScr { get; set; }
        public string AtmBoss { get; set; }
        public Nullable<System.DateTime> AtmBossD { get; set; }
        public int Atm_Num { get; set; }
        public string Atm_In { get; set; }
        public string Atm_State { get; set; }
    }
}
