//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meet
    {
        public int Meet_Num { get; set; }
        public Nullable<System.DateTime> Meet_Date { get; set; }
        public string Meet_Place { get; set; }
        public string Meet_Renew { get; set; }
        public Nullable<System.DateTime> Meet_Update { get; set; }
        public string Meet_File { get; set; }
        public string Meet_Company { get; set; }
    }
}
