//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetItem
    {
        public int Item_Num { get; set; }
        public string Item_Company { get; set; }
        public string Item_Post { get; set; }
        public string Item_Name { get; set; }
        public string Item_Address { get; set; }
        public string Item_Tel { get; set; }
        public string Item_Extension { get; set; }
        public string Item_Fax { get; set; }
        public string Item_Unite { get; set; }
        public string Item_Mail { get; set; }
        public string Item_English { get; set; }
        public Nullable<int> Item_Meet { get; set; }
    }
}
