//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEmp
    {
        public int Mes_Num { get; set; }
        public Nullable<System.DateTime> Mes_Creat { get; set; }
        public string Mes_Input { get; set; }
        public string Mes_EmpNum { get; set; }
        public string Mes_Name { get; set; }
        public string Mes_Official { get; set; }
        public string Mes_Agent { get; set; }
        public string Mes_AOfficial { get; set; }
        public Nullable<System.DateTime> Mes_Start { get; set; }
        public Nullable<System.DateTime> Mes_Stop { get; set; }
        public string Mes_Renew { get; set; }
        public Nullable<System.DateTime> Mes_Update { get; set; }
        public Nullable<int> Mes_Class { get; set; }
        public string Mes_Boss { get; set; }
        public Nullable<System.DateTime> Mes_BossTime { get; set; }
        public string Mes_Pop { get; set; }
        public Nullable<System.DateTime> Mes_PopTime { get; set; }
        public string Mes_Thing { get; set; }
        public string Mes_Del { get; set; }
        public string Mes_DelName { get; set; }
        public Nullable<System.DateTime> Mes_DelDate { get; set; }
        public string Mes_ID { get; set; }
        public string Mes_State { get; set; }
    }
}
