//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewEmp
    {
        public int 編號 { get; set; }
        public string 中文姓名 { get; set; }
        public string 英文姓名 { get; set; }
        public string 身分證字號 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public string 部門或科系代碼 { get; set; }
        public string 職稱 { get; set; }
        public string 分機 { get; set; }
        public string 電話1 { get; set; }
        public string 電話2 { get; set; }
        public string 手機 { get; set; }
        public string 地址 { get; set; }
        public Nullable<System.DateTime> 雇用日期 { get; set; }
        public string 管理部確認 { get; set; }
        public Nullable<System.DateTime> 管理部確認日 { get; set; }
        public string 資訊室確認 { get; set; }
        public Nullable<System.DateTime> 資訊室確認日 { get; set; }
        public string 資訊室說明 { get; set; }
        public string 總經理室確認 { get; set; }
        public Nullable<System.DateTime> 總經理室確認日 { get; set; }
        public string 董事長確認 { get; set; }
        public Nullable<System.DateTime> 董事長確認日 { get; set; }
        public string 已到職 { get; set; }
        public Nullable<System.DateTime> 到職日 { get; set; }
        public string 建檔人 { get; set; }
        public Nullable<System.DateTime> 建檔日期 { get; set; }
        public string 郵件帳號 { get; set; }
        public string 部門代號 { get; set; }
        public string 工作地點 { get; set; }
        public string 類別 { get; set; }
        public Nullable<System.DateTime> 派遣日 { get; set; }
        public Nullable<System.DateTime> 派遣終止日 { get; set; }
        public string 派遣日期 { get; set; }
        public string UPPER_BOSS { get; set; }
        public string 是否為主管職 { get; set; }
        public string 社內帳號 { get; set; }
        public string 復職 { get; set; }
    }
}
