//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int 自動編號 { get; set; }
        public string 主題 { get; set; }
        public string 內容 { get; set; }
        public string 公佈人 { get; set; }
        public Nullable<System.DateTime> 公佈日期 { get; set; }
        public string 是否使用 { get; set; }
        public string 圖檔 { get; set; }
        public string ALL { get; set; }
        public string OTC { get; set; }
        public string OALT { get; set; }
        public string OAMC { get; set; }
        public string OTI { get; set; }
    }
}
