//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoCashFlow
    {
        public int SEQ { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string Aply_No_R { get; set; }
        public string Aply_No { get; set; }
        public string Proced_aply_No { get; set; }
        public Nullable<double> Pay_R_Amt { get; set; }
        public Nullable<double> Supl_Amt { get; set; }
        public Nullable<double> Renew_Amt { get; set; }
        public string Cen_ID { get; set; }
        public Nullable<System.DateTime> Cen_Date { get; set; }
        public string Cen_Remark { get; set; }
        public string Cen_YN { get; set; }
        public string CenM_ID { get; set; }
        public Nullable<System.DateTime> CenM_Date { get; set; }
        public string CenM_YN { get; set; }
        public Nullable<double> Sum_AMT { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string emp_code { get; set; }
        public string cust_name { get; set; }
        public string FRC_Sales { get; set; }
        public string FRC_area { get; set; }
        public string Sign_Boss { get; set; }
        public Nullable<System.DateTime> Boss_Date { get; set; }
        public string Doc_Status { get; set; }
        public string N_EMP_CODE { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string NOTE { get; set; }
        public string Cha_Item { get; set; }
        public string R_EMP_CODE { get; set; }
        public string H_BossName { get; set; }
        public Nullable<double> Freeze_YES { get; set; }
        public Nullable<double> Freeze_NO { get; set; }
    }
}
