//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTQ1
    {
        public int Q1_Num { get; set; }
        public string licenceNo { get; set; }
        public string CustName { get; set; }
        public string UserName { get; set; }
        public string UserTel { get; set; }
        public string lossitem { get; set; }
        public string A1 { get; set; }
        public string A1_Scr { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A3_Scr { get; set; }
        public string A4 { get; set; }
        public string A4_Scr { get; set; }
        public string A5 { get; set; }
        public string A5_Scr { get; set; }
        public string A6 { get; set; }
        public string A6_Scr { get; set; }
        public string Add_Name { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
        public string Kind { get; set; }
        public string A7 { get; set; }
        public string A7_Scr { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    }
}
