//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_FARE_APLY_DETAIL
    {
        public string FARE_APLY_NO { get; set; }
        public int SEQ_NO { get; set; }
        public string FARE_DATE { get; set; }
        public string FARE_CODE { get; set; }
        public Nullable<decimal> FARE_APLY_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TAX_AMT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> FARE_APRV_AMT { get; set; }
        public string RECV_CODE { get; set; }
        public string FARE_PAY_TO { get; set; }
        public string UNIF_NO { get; set; }
        public string SUPPLY_NAME { get; set; }
        public string REMARK { get; set; }
        public string RECEIPT_TYPE { get; set; }
        public string RECEIPT_NO { get; set; }
        public string DUE_DATE { get; set; }
    }
}
