//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrixGiftScr
    {
        public string GiftNo { get; set; }
        public Nullable<System.DateTime> Gift_Date { get; set; }
        public string Gift_Time { get; set; }
        public string CTAC_ADDR { get; set; }
        public string TEL { get; set; }
        public string CONTACT { get; set; }
        public Nullable<int> ITEM { get; set; }
        public Nullable<double> Item_Money { get; set; }
        public int SEQ { get; set; }
    }
}
