//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORIX_OTCContext : DbContext
    {
        public ORIX_OTCContext()
            : base("name=ORIX_OTCContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminId> AdminIds { get; set; }
        public DbSet<AMCREO> AMCREOs { get; set; }
        public DbSet<AnnualEmp> AnnualEmps { get; set; }
        public DbSet<AOComment> AOComments { get; set; }
        public DbSet<AOType> AOTypes { get; set; }
        public DbSet<ApplyMail> ApplyMails { get; set; }
        public DbSet<ApproveType> ApproveTypes { get; set; }
        public DbSet<AskLeave> AskLeaves { get; set; }
        public DbSet<AskLeaveClass> AskLeaveClasses { get; set; }
        public DbSet<Beforehand> Beforehands { get; set; }
        public DbSet<CameraDetail> CameraDetails { get; set; }
        public DbSet<CameraMain> CameraMains { get; set; }
        public DbSet<CameraType> CameraTypes { get; set; }
        public DbSet<CareDetail> CareDetails { get; set; }
        public DbSet<CareKeep> CareKeeps { get; set; }
        public DbSet<CareMain> CareMains { get; set; }
        public DbSet<CareType> CareTypes { get; set; }
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<ClockEmp> ClockEmps { get; set; }
        public DbSet<ClockType> ClockTypes { get; set; }
        public DbSet<ComCrit> ComCrits { get; set; }
        public DbSet<ComDetail> ComDetails { get; set; }
        public DbSet<ComeVisit> ComeVisits { get; set; }
        public DbSet<ComMain> ComMains { get; set; }
        public DbSet<ComMd> ComMds { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyAply> CompanyAplies { get; set; }
        public DbSet<CompanyAplyScr> CompanyAplyScrs { get; set; }
        public DbSet<CompanyCopy> CompanyCopies { get; set; }
        public DbSet<CompanyCopyType> CompanyCopyTypes { get; set; }
        public DbSet<CompanyName> CompanyNames { get; set; }
        public DbSet<ComType> ComTypes { get; set; }
        public DbSet<ConfRoomDetail> ConfRoomDetails { get; set; }
        public DbSet<ConfRoomDetail2009> ConfRoomDetail2009 { get; set; }
        public DbSet<ConfRoomMain> ConfRoomMains { get; set; }
        public DbSet<ConfRoomType> ConfRoomTypes { get; set; }
        public DbSet<Counter> Counters { get; set; }
        public DbSet<CreditTime> CreditTimes { get; set; }
        public DbSet<CrossRedate> CrossRedates { get; set; }
        public DbSet<CrossSell> CrossSells { get; set; }
        public DbSet<CustomApprove> CustomApproves { get; set; }
        public DbSet<CustomApproveNType> CustomApproveNTypes { get; set; }
        public DbSet<CustomeApproveName> CustomeApproveNames { get; set; }
        public DbSet<CustRequire> CustRequires { get; set; }
        public DbSet<CustRequireType> CustRequireTypes { get; set; }
        public DbSet<DiplomaticEmp> DiplomaticEmps { get; set; }
        public DbSet<Dispatch> Dispatches { get; set; }
        public DbSet<DispatchType> DispatchTypes { get; set; }
        public DbSet<DocMd> DocMds { get; set; }
        public DbSet<EmpNote> EmpNotes { get; set; }
        public DbSet<EmpSign> EmpSigns { get; set; }
        public DbSet<EmpTravel> EmpTravels { get; set; }
        public DbSet<Entrance> Entrances { get; set; }
        public DbSet<EquiApply> EquiApplies { get; set; }
        public DbSet<EquiApplyDetail> EquiApplyDetails { get; set; }
        public DbSet<EquiSpec> EquiSpecs { get; set; }
        public DbSet<EquiStock> EquiStocks { get; set; }
        public DbSet<EquiType> EquiTypes { get; set; }
        public DbSet<ETemporary> ETemporaries { get; set; }
        public DbSet<ExpAllot> ExpAllots { get; set; }
        public DbSet<EYesterday> EYesterdays { get; set; }
        public DbSet<GeneralItem> GeneralItems { get; set; }
        public DbSet<GeneralService> GeneralServices { get; set; }
        public DbSet<GuestBook> GuestBooks { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<HolidayLogin> HolidayLogins { get; set; }
        public DbSet<HolidayType> HolidayTypes { get; set; }
        public DbSet<HolidayType1> HolidayType1 { get; set; }
        public DbSet<HomePage> HomePages { get; set; }
        public DbSet<HostName> HostNames { get; set; }
        public DbSet<HR0101> HR0101 { get; set; }
        public DbSet<HR6861> HR6861 { get; set; }
        public DbSet<HR6861T> HR6861T { get; set; }
        public DbSet<HREMP> HREMPs { get; set; }
        public DbSet<HREmpScr> HREmpScrs { get; set; }
        public DbSet<HRMail> HRMails { get; set; }
        public DbSet<HU_DEPT_20121108> HU_DEPT_20121108 { get; set; }
        public DbSet<HU_DEPT1> HU_DEPT1 { get; set; }
        public DbSet<Information> Information { get; set; }
        public DbSet<InformationType> InformationTypes { get; set; }
        public DbSet<InsuranceRatio> InsuranceRatios { get; set; }
        public DbSet<InsuranceType> InsuranceTypes { get; set; }
        public DbSet<IP位址資料> IP位址資料 { get; set; }
        public DbSet<JCICAPLY> JCICAPLies { get; set; }
        public DbSet<junket> junkets { get; set; }
        public DbSet<junketItem> junketItems { get; set; }
        public DbSet<LeaveOffice> LeaveOffices { get; set; }
        public DbSet<LEX_SallyForth> LEX_SallyForth { get; set; }
        public DbSet<LEX_VAL_BAL> LEX_VAL_BAL { get; set; }
        public DbSet<Machinery> Machineries { get; set; }
        public DbSet<MachineryType> MachineryTypes { get; set; }
        public DbSet<Meet> Meets { get; set; }
        public DbSet<MeetItem> MeetItems { get; set; }
        public DbSet<MessageClass> MessageClasses { get; set; }
        public DbSet<MessageEmp> MessageEmps { get; set; }
        public DbSet<MessageRule> MessageRules { get; set; }
        public DbSet<NBCarry> NBCarries { get; set; }
        public DbSet<NBCarryType> NBCarryTypes { get; set; }
        public DbSet<NewEmp> NewEmps { get; set; }
        public DbSet<NewEmpBoss> NewEmpBosses { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NoCashFlow> NoCashFlows { get; set; }
        public DbSet<NtMd> NtMds { get; set; }
        public DbSet<OALT_FIELD_SIGN> OALT_FIELD_SIGN { get; set; }
        public DbSet<OALTcommon> OALTcommons { get; set; }
        public DbSet<OALTQ1> OALTQ1 { get; set; }
        public DbSet<OALTQ2> OALTQ2 { get; set; }
        public DbSet<OALTQ3> OALTQ3 { get; set; }
        public DbSet<OALTQ4> OALTQ4 { get; set; }
        public DbSet<OALTQ6> OALTQ6 { get; set; }
        public DbSet<OALTQ7> OALTQ7 { get; set; }
        public DbSet<OALTquoted> OALTquoteds { get; set; }
        public DbSet<OALTQution> OALTQutions { get; set; }
        public DbSet<OALTSrvMail> OALTSrvMails { get; set; }
        public DbSet<OALTSrvMailScr> OALTSrvMailScrs { get; set; }
        public DbSet<OALTteach> OALTteaches { get; set; }
        public DbSet<old_OTC_PROCED_BACK_ACT> old_OTC_PROCED_BACK_ACT { get; set; }
        public DbSet<old_OTC_PROCED_BACK_ERD> old_OTC_PROCED_BACK_ERD { get; set; }
        public DbSet<old_OTC_PROCED_DEPT_ERD> old_OTC_PROCED_DEPT_ERD { get; set; }
        public DbSet<ONESTOP> ONESTOPs { get; set; }
        public DbSet<ONESTOPScr> ONESTOPScrs { get; set; }
        public DbSet<ONESTOPType> ONESTOPTypes { get; set; }
        public DbSet<ONESTOPUNIT> ONESTOPUNITs { get; set; }
        public DbSet<ONESTOPUNITemp> ONESTOPUNITemps { get; set; }
        public DbSet<OR2_FARE_APLY> OR2_FARE_APLY { get; set; }
        public DbSet<OR2_FARE_APLY_DETAIL> OR2_FARE_APLY_DETAIL { get; set; }
        public DbSet<OR2_FARE_APRV> OR2_FARE_APRV { get; set; }
        public DbSet<ORIX_SPEICAL> ORIX_SPEICAL { get; set; }
        public DbSet<ORIXAuthority> ORIXAuthorities { get; set; }
        public DbSet<OrixGift> OrixGifts { get; set; }
        public DbSet<OrixGiftScr> OrixGiftScrs { get; set; }
        public DbSet<OrixGiftType> OrixGiftTypes { get; set; }
        public DbSet<ORIXLVL> ORIXLVLs { get; set; }
        public DbSet<ORIXReceive> ORIXReceives { get; set; }
        public DbSet<ORIXSend> ORIXSends { get; set; }
        public DbSet<OTC_DOC_BR> OTC_DOC_BR { get; set; }
        public DbSet<OTC_FIELD_SIGN> OTC_FIELD_SIGN { get; set; }
        public DbSet<OTC_INT_APLY> OTC_INT_APLY { get; set; }
        public DbSet<OTC_INT_APLY_HOMENOTE> OTC_INT_APLY_HOMENOTE { get; set; }
        public DbSet<OTC_INT_FLOW> OTC_INT_FLOW { get; set; }
        public DbSet<OTC_PROCED_Absorb> OTC_PROCED_Absorb { get; set; }
        public DbSet<OTC_PROCED_APLY> OTC_PROCED_APLY { get; set; }
        public DbSet<OTC_PROCED_APLY_HOMENOTE> OTC_PROCED_APLY_HOMENOTE { get; set; }
        public DbSet<OTC_PROCED_APLY_LIST> OTC_PROCED_APLY_LIST { get; set; }
        public DbSet<OTC_PROCED_APRV> OTC_PROCED_APRV { get; set; }
        public DbSet<OTC_PROCED_APRV_T> OTC_PROCED_APRV_T { get; set; }
        public DbSet<OTC_PROCED_BACK_ACT> OTC_PROCED_BACK_ACT { get; set; }
        public DbSet<OTC_PROCED_BACK_ERD> OTC_PROCED_BACK_ERD { get; set; }
        public DbSet<OTC_PROCED_COLUMN> OTC_PROCED_COLUMN { get; set; }
        public DbSet<OTC_PROCED_Content> OTC_PROCED_Content { get; set; }
        public DbSet<OTC_PROCED_Content2> OTC_PROCED_Content2 { get; set; }
        public DbSet<OTC_PROCED_DEMERIT> OTC_PROCED_DEMERIT { get; set; }
        public DbSet<OTC_Proced_Demerit_Affirm> OTC_Proced_Demerit_Affirm { get; set; }
        public DbSet<OTC_PROCED_DEPT_ERD> OTC_PROCED_DEPT_ERD { get; set; }
        public DbSet<OTC_PROCED_DOC> OTC_PROCED_DOC { get; set; }
        public DbSet<OTC_PROCED_INVO> OTC_PROCED_INVO { get; set; }
        public DbSet<OTC_PROCED_LOSE> OTC_PROCED_LOSE { get; set; }
        public DbSet<OTC_PROCED_LVL> OTC_PROCED_LVL { get; set; }
        public DbSet<OTC_PROCED_MIS> OTC_PROCED_MIS { get; set; }
        public DbSet<OTC_PROCED_MIS_TYPE> OTC_PROCED_MIS_TYPE { get; set; }
        public DbSet<OTC_PROCED_NEW_APLYNO> OTC_PROCED_NEW_APLYNO { get; set; }
        public DbSet<OTC_PROCED_OALTADD> OTC_PROCED_OALTADD { get; set; }
        public DbSet<OTC_PROCED_OBJECT> OTC_PROCED_OBJECT { get; set; }
        public DbSet<OTC_PROCED_PAY> OTC_PROCED_PAY { get; set; }
        public DbSet<OTC_PROCED_SEND> OTC_PROCED_SEND { get; set; }
        public DbSet<OTC_PROCED_TYPE> OTC_PROCED_TYPE { get; set; }
        public DbSet<OTC_PROCED_UNITE> OTC_PROCED_UNITE { get; set; }
        public DbSet<PaperAply> PaperAplies { get; set; }
        public DbSet<PaperAplyScr> PaperAplyScrs { get; set; }
        public DbSet<PaperCTW> PaperCTWs { get; set; }
        public DbSet<PaperFolder> PaperFolders { get; set; }
        public DbSet<PaperItem> PaperItems { get; set; }
        public DbSet<PaperSelectAply> PaperSelectAplies { get; set; }
        public DbSet<PaperSelectT> PaperSelectTs { get; set; }
        public DbSet<PE_ReviewForm> PE_ReviewForm { get; set; }
        public DbSet<PostAgent> PostAgents { get; set; }
        public DbSet<Postal> Postals { get; set; }
        public DbSet<PROCED_CODE> PROCED_CODE { get; set; }
        public DbSet<PROCED_Deadline> PROCED_Deadline { get; set; }
        public DbSet<ProcedUnit> ProcedUnits { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProjectorDetail> ProjectorDetails { get; set; }
        public DbSet<ProjectorMain> ProjectorMains { get; set; }
        public DbSet<ProjectorType> ProjectorTypes { get; set; }
        public DbSet<ProocedUNIT> ProocedUNITs { get; set; }
        public DbSet<RecordDetail> RecordDetails { get; set; }
        public DbSet<RecordMain> RecordMains { get; set; }
        public DbSet<RecordType> RecordTypes { get; set; }
        public DbSet<Rentec> Rentecs { get; set; }
        public DbSet<RentecACH> RentecACHes { get; set; }
        public DbSet<RentecType> RentecTypes { get; set; }
        public DbSet<ReplyBook> ReplyBooks { get; set; }
        public DbSet<ResponsetType> ResponsetTypes { get; set; }
        public DbSet<SALE_APLY_AMOUNT> SALE_APLY_AMOUNT { get; set; }
        public DbSet<SALEDEPCU> SALEDEPCUS { get; set; }
        public DbSet<SALEDEPREC> SALEDEPRECs { get; set; }
        public DbSet<SALEDEPTYPE> SALEDEPTYPEs { get; set; }
        public DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public DbSet<ScheduleItem> ScheduleItems { get; set; }
        public DbSet<ScheduleMain> ScheduleMains { get; set; }
        public DbSet<ScheduleType> ScheduleTypes { get; set; }
        public DbSet<ScheduleView> ScheduleViews { get; set; }
        public DbSet<SecurityAgree> SecurityAgrees { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<ServiceMail> ServiceMails { get; set; }
        public DbSet<ServiceRMail> ServiceRMails { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<Shart_Amount> Shart_Amount { get; set; }
        public DbSet<Shart_AReporder> Shart_AReporder { get; set; }
        public DbSet<Shart_CAROrder> Shart_CAROrder { get; set; }
        public DbSet<Shart_Contract> Shart_Contract { get; set; }
        public DbSet<Shart_cost> Shart_cost { get; set; }
        public DbSet<Shart_Custom> Shart_Custom { get; set; }
        public DbSet<Shart_ETAGPay> Shart_ETAGPay { get; set; }
        public DbSet<Shart_Holiday> Shart_Holiday { get; set; }
        public DbSet<Shart_INVO> Shart_INVO { get; set; }
        public DbSet<Shart_licence> Shart_licence { get; set; }
        public DbSet<Shart_licenceDate> Shart_licenceDate { get; set; }
        public DbSet<Shart_licenceRed> Shart_licenceRed { get; set; }
        public DbSet<Shart_Order> Shart_Order { get; set; }
        public DbSet<Shart_OtherINV> Shart_OtherINV { get; set; }
        public DbSet<Shart_OtherSendPay> Shart_OtherSendPay { get; set; }
        public DbSet<Shart_RAmount> Shart_RAmount { get; set; }
        public DbSet<Shart_Reporder> Shart_Reporder { get; set; }
        public DbSet<Shart_ReporderList> Shart_ReporderList { get; set; }
        public DbSet<Shart_ReporderScr> Shart_ReporderScr { get; set; }
        public DbSet<Shart_ReporderSeat> Shart_ReporderSeat { get; set; }
        public DbSet<Shart_RINVO> Shart_RINVO { get; set; }
        public DbSet<Shart_RorderT> Shart_RorderT { get; set; }
        public DbSet<Shart_RVend> Shart_RVend { get; set; }
        public DbSet<Shart_Self> Shart_Self { get; set; }
        public DbSet<Shart_SendCar> Shart_SendCar { get; set; }
        public DbSet<Shopping> Shoppings { get; set; }
        public DbSet<Sign_AgreeBook> Sign_AgreeBook { get; set; }
        public DbSet<Special> Specials { get; set; }
        public DbSet<SpecialMail> SpecialMails { get; set; }
        public DbSet<SpecialType> SpecialTypes { get; set; }
        public DbSet<SrtbivrTMail> SrtbivrTMails { get; set; }
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<USBCarry> USBCarries { get; set; }
        public DbSet<USBDetail> USBDetails { get; set; }
        public DbSet<USBMain> USBMains { get; set; }
        public DbSet<USBType> USBTypes { get; set; }
        public DbSet<VoteDetail> VoteDetails { get; set; }
        public DbSet<VoteLog> VoteLogs { get; set; }
        public DbSet<VoteMain> VoteMains { get; set; }
        public DbSet<WB6101> WB6101 { get; set; }
        public DbSet<WB6621> WB6621 { get; set; }
        public DbSet<WB6621_APRV> WB6621_APRV { get; set; }
        public DbSet<WB6621type> WB6621type { get; set; }
        public DbSet<work_day> work_day { get; set; }
        public DbSet<WorkClass> WorkClasses { get; set; }
        public DbSet<WorkEmp> WorkEmps { get; set; }
        public DbSet<WorkRecord> WorkRecords { get; set; }
        public DbSet<WorkState> WorkStates { get; set; }
        public DbSet<WorkView> WorkViews { get; set; }
        public DbSet<YearHoliday> YearHolidays { get; set; }
        public DbSet<員工> 員工 { get; set; }
        public DbSet<員工_950310> 員工_950310 { get; set; }
        public DbSet<員工_970508> 員工_970508 { get; set; }
        public DbSet<員工_981006> 員工_981006 { get; set; }
        public DbSet<郵件帳號_> 郵件帳號_ { get; set; }
    }
}
