//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrixGift
    {
        public string GiftNo { get; set; }
        public string Aply_Com { get; set; }
        public string Gift_File { get; set; }
        public string Gift_Contribute { get; set; }
        public string Re_Name { get; set; }
        public Nullable<System.DateTime> Re_Update { get; set; }
        public string Gift_Company { get; set; }
        public string Gift_Cause { get; set; }
        public string Gift_Sign { get; set; }
        public string Class { get; set; }
        public Nullable<double> Gift_Money { get; set; }
        public string Doc_Status { get; set; }
        public string Aply_Person { get; set; }
        public Nullable<System.DateTime> Aply_Date { get; set; }
    }
}
