//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_NEW_APLYNO
    {
        public string Proced_aply_no { get; set; }
        public string B_Ori_Aplyno { get; set; }
        public string B_new_applyno { get; set; }
        public Nullable<int> B_Bus_Money { get; set; }
        public string B_Con_StarDate { get; set; }
        public string B_INV_Month { get; set; }
        public string B_Bus_Month { get; set; }
        public string CEN_ID { get; set; }
        public Nullable<System.DateTime> CEN_Date { get; set; }
        public string VP_ID { get; set; }
        public Nullable<System.DateTime> VP_Date { get; set; }
        public string B_Con_EndDate { get; set; }
    }
}
