//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_Proced_Demerit_Affirm
    {
        public string Proced_Aply_no { get; set; }
        public int AtmC_No { get; set; }
        public string Proced_Con { get; set; }
        public Nullable<System.DateTime> CEN_Date { get; set; }
        public string CEN_ID { get; set; }
        public string CENM_ID { get; set; }
        public Nullable<System.DateTime> CENM_Date { get; set; }
        public string BS_YN { get; set; }
        public string CEN_YN { get; set; }
        public string CENM_YN { get; set; }
        public string REMARK { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public string VP_Name { get; set; }
        public Nullable<System.DateTime> VP_Time { get; set; }
        public string SPARETime { get; set; }
        public string BACKINVTime { get; set; }
        public string CEN_REMARK { get; set; }
        public string CEN_VPScr { get; set; }
        public Nullable<System.DateTime> CEN_VPDate { get; set; }
        public string CEN_VPName { get; set; }
        public Nullable<System.DateTime> Deal_Date { get; set; }
        public string INVO_YN { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public string R_Name { get; set; }
        public Nullable<System.DateTime> Extend_Date { get; set; }
        public string Extend_User { get; set; }
        public string R_Scr { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
        public string Check_USER { get; set; }
        public string PERD { get; set; }
        public Nullable<System.DateTime> R_ACCDate { get; set; }
        public string Sign_AccName { get; set; }
    }
}
