//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_INT_APLY
    {
        public string INT_NO { get; set; }
        public string NOTE { get; set; }
        public string APLY_PERSON { get; set; }
        public string APLY_DATE { get; set; }
        public string DEPT { get; set; }
        public string DURN { get; set; }
        public string DATE_FR { get; set; }
        public string DATE_TO { get; set; }
        public string DATE_TYPE { get; set; }
        public string Target { get; set; }
        public string Del_Name { get; set; }
        public Nullable<System.DateTime> Del_Date { get; set; }
        public string Modify_ID { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Proced_File { get; set; }
        public string Doc_Status { get; set; }
        public string OTHER { get; set; }
        public string TargetD { get; set; }
    }
}
