//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_Content
    {
        public string PROCED_APLY_NO { get; set; }
        public string APLY_COM { get; set; }
        public string MAIN { get; set; }
        public string Content { get; set; }
        public string B_deadline { get; set; }
        public string B_exe_time { get; set; }
        public Nullable<int> B_spare_time { get; set; }
        public string B_capital { get; set; }
        public string B_cancel_money { get; set; }
        public Nullable<int> B_sale_money { get; set; }
        public string B_open_inv { get; set; }
        public string B_title { get; set; }
        public string B_unite { get; set; }
        public string B_send_address { get; set; }
        public string B_pay_new { get; set; }
        public string B_pay_supply { get; set; }
        public string B_balance { get; set; }
        public string B_supply_title { get; set; }
        public Nullable<int> B_balance_new { get; set; }
        public string B_custom_title { get; set; }
        public string B_custom_unite { get; set; }
        public string B_new_custom { get; set; }
        public string B_time { get; set; }
        public string B_rent { get; set; }
        public string B_new_applyno { get; set; }
        public string B_startdate { get; set; }
        public string B_no_rent { get; set; }
        public Nullable<double> B_TR_percent { get; set; }
        public Nullable<int> B_contract_time { get; set; }
        public string B_time_rent { get; set; }
        public Nullable<int> B_cancel_money_inv { get; set; }
        public Nullable<int> B_open_inv_inv { get; set; }
        public string B_Sing_No { get; set; }
        public string B_Sing_Scr { get; set; }
        public string B_customer_send_address { get; set; }
        public string B_clause { get; set; }
        public string B_payment { get; set; }
        public string B_change_payment { get; set; }
        public Nullable<int> B_interest { get; set; }
        public Nullable<double> B_TR { get; set; }
        public string B_model { get; set; }
        public string B_model_No { get; set; }
        public string B_model_change_No { get; set; }
        public Nullable<int> B_backward { get; set; }
        public string B_cheque { get; set; }
        public Nullable<int> B_cheque_money { get; set; }
        public string B_cheque_date { get; set; }
        public string B_cheque_change { get; set; }
        public Nullable<int> B_cheque_change_money { get; set; }
        public string B_cheque_change_date { get; set; }
        public string B_backward_way { get; set; }
        public string B_liaise { get; set; }
        public string B_Tel { get; set; }
        public string B_temporary_date { get; set; }
        public Nullable<int> B_new_time { get; set; }
        public string B_new_rent { get; set; }
        public string B_new_unite { get; set; }
        public string B_continue_date { get; set; }
        public string B_contract_stop { get; set; }
        public string B_contract_commerce { get; set; }
        public string B_troubleDate { get; set; }
        public string B_troubleScr { get; set; }
        public Nullable<int> B_Compensate { get; set; }
        public string B_stopinv { get; set; }
        public string B_service { get; set; }
        public string B_ReturnInv { get; set; }
        public string B_Fax { get; set; }
        public string B_every_rent { get; set; }
        public string B_Object { get; set; }
        public string B_Sign_salse { get; set; }
        public string B_Sign_end { get; set; }
        public string B_Advice { get; set; }
        public string B_Other_Files { get; set; }
        public string B_New_Contract { get; set; }
        public string B_Agree { get; set; }
        public string B_new_capital { get; set; }
        public string B_DealSign { get; set; }
        public string B_Inv_end { get; set; }
        public string B_Rent_acc { get; set; }
        public string B_Capital_acc { get; set; }
        public string B_New_Contract1 { get; set; }
        public string B_PayDate { get; set; }
        public Nullable<double> B_Self_TR { get; set; }
        public string B_PayInv_YN { get; set; }
        public string B_Change_Date { get; set; }
        public string B_Other_UP { get; set; }
        public string B_TT_YN { get; set; }
        public string B_TT_Date { get; set; }
        public string B_Cash_YN { get; set; }
        public string B_Cash_Date { get; set; }
        public string B_backward_self { get; set; }
        public string B_backward_Other { get; set; }
        public Nullable<int> B_Postpone { get; set; }
        public string B_Postpone_INV { get; set; }
        public string B_Fee { get; set; }
        public string B_InvSend { get; set; }
        public string B_OtherIncome { get; set; }
        public string B_FutureDate { get; set; }
        public string B_APayDate { get; set; }
        public string B_PayOK { get; set; }
        public string B_INVType { get; set; }
        public string B_INVNumber { get; set; }
        public string B_INVMoney { get; set; }
        public string B_INVDate { get; set; }
        public string B_cancel_INV_Month { get; set; }
        public string B_cancel_title { get; set; }
        public string B_cancel_unite { get; set; }
        public string B_cancel_address { get; set; }
        public string B_cancel_Pay { get; set; }
        public Nullable<double> B_Offprint { get; set; }
        public Nullable<double> B_OffprintTol { get; set; }
        public string B_Ori_Aplyno { get; set; }
        public string B_Before_AplyNo { get; set; }
        public string B_Continue_DueDate { get; set; }
        public string B_Continue_Aply { get; set; }
        public Nullable<int> B_Continue_Time { get; set; }
        public string B_Con_StarDate { get; set; }
        public string B_Con_EndDate { get; set; }
        public string B_INV_Month { get; set; }
        public string B_Damage { get; set; }
        public string B_Bus_Month { get; set; }
        public Nullable<double> B_Bus_Money { get; set; }
        public string B_Spec_No { get; set; }
        public string B_Spec_change_No { get; set; }
        public Nullable<double> B_sale_Bus { get; set; }
        public string B_EndDate { get; set; }
        public Nullable<double> B_Other_Pay { get; set; }
        public string B_Paper { get; set; }
        public string B_Case_Time { get; set; }
        public string B_Case_Month { get; set; }
        public string B_Re_INVO { get; set; }
        public string B_CUR_STS { get; set; }
        public string B_Merge_Case { get; set; }
        public string B_nstartdate { get; set; }
        public string B_nEndDate { get; set; }
    }
}
