//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_FIELD_SIGN
    {
        public string ORD_CLASS { get; set; }
        public int SEQ_NO { get; set; }
        public string CLASS_CNAME { get; set; }
        public string CLASS_NAME { get; set; }
        public string CLASS_YN { get; set; }
        public string CLASS_STATE { get; set; }
        public string CLASS_FLOW { get; set; }
        public string CLASS_E { get; set; }
        public Nullable<int> CLASS_SIZE { get; set; }
        public string CLASS_TAB { get; set; }
        public string CLASS_MIS { get; set; }
        public string Class_Show { get; set; }
        public string CLASS_AUTO { get; set; }
    }
}
