//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_APRV_T
    {
        public string PROCED_APLY_NO { get; set; }
        public string PROCED_APRV_EMP { get; set; }
        public string PROCED_APRV_LVL { get; set; }
        public string APRV_OPINION { get; set; }
        public string APRV_DEPT { get; set; }
        public string FLOW { get; set; }
        public string APLY_COM { get; set; }
    }
}
