//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperFolder
    {
        public int Paper_Num { get; set; }
        public string Box_Num { get; set; }
        public string Paper_Dept { get; set; }
        public string Paper_Rname { get; set; }
        public Nullable<System.DateTime> Paper_Rdate { get; set; }
        public string Paper_Gist { get; set; }
        public string Paper_Del { get; set; }
        public string Paper_Keep { get; set; }
        public string Trn_No { get; set; }
        public string CORP_NO { get; set; }
        public string entry_id { get; set; }
        public Nullable<System.DateTime> entry_Date { get; set; }
        public string CUR_STS { get; set; }
        public Nullable<System.DateTime> IN_STOCK_DATE { get; set; }
    }
}
