//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAgent
    {
        public string Post_EmpNo { get; set; }
        public string Post_Dept { get; set; }
        public string Post_ProfessionalTitle { get; set; }
        public string Post_Name { get; set; }
        public string Post_ID { get; set; }
        public string Post_Agent { get; set; }
        public string Post_AgentID { get; set; }
        public string Post_Scr { get; set; }
        public Nullable<System.DateTime> Post_SDate { get; set; }
        public Nullable<System.DateTime> Post_EDate { get; set; }
        public string Post_SHour { get; set; }
        public string Post_EHour { get; set; }
        public int Post_Num { get; set; }
        public string Post_Add { get; set; }
        public Nullable<System.DateTime> Post_AddDate { get; set; }
        public Nullable<System.DateTime> Post_Update { get; set; }
        public string Post_Rename { get; set; }
        public string Post_LVLotc { get; set; }
        public string Post_LVLoalt { get; set; }
        public string Post_LVLamc { get; set; }
    }
}
