//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentec
    {
        public string CUST_NO2 { get; set; }
        public string CTAC { get; set; }
        public string CTAC_ADDR { get; set; }
        public string TEL { get; set; }
        public string FAX_NO { get; set; }
        public string MOBIL { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Rec_Date { get; set; }
        public string CORP_NAME { get; set; }
        public string ENG_CORP_NAME { get; set; }
        public string OBJ_POST { get; set; }
        public string PROD_NAME { get; set; }
        public Nullable<int> QTY { get; set; }
        public string AR_PROD { get; set; }
        public string OBJ_CTENT { get; set; }
        public Nullable<System.DateTime> trem_start { get; set; }
        public Nullable<System.DateTime> trem_stop { get; set; }
        public string trem { get; set; }
        public Nullable<int> money_type { get; set; }
        public Nullable<double> monty_amt { get; set; }
        public Nullable<double> CON_TOL_AMT { get; set; }
        public Nullable<double> CURR_RATE { get; set; }
        public Nullable<double> REDR_TOL_AMT { get; set; }
        public Nullable<double> portage { get; set; }
        public Nullable<double> customs { get; set; }
        public Nullable<double> insurance { get; set; }
        public Nullable<double> business_tax { get; set; }
        public Nullable<double> OTH_FEE_TOL { get; set; }
        public Nullable<double> SALE_NET_AMT { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<double> QUOT_AMT { get; set; }
        public Nullable<double> M_PAY_AMT { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<int> B_TR { get; set; }
        public Nullable<double> MONTH_PAY_AMT { get; set; }
        public string FailScr { get; set; }
        public Nullable<double> ACH { get; set; }
        public string QUOT_Name { get; set; }
        public Nullable<System.DateTime> QUOT_Date { get; set; }
        public string Crd_AddName { get; set; }
        public Nullable<System.DateTime> ADD_Date { get; set; }
        public string Re_ID { get; set; }
        public Nullable<System.DateTime> Re_Date { get; set; }
        public string SEQ_NO { get; set; }
        public string HAND_EMP { get; set; }
        public string service { get; set; }
        public string CUST_SOUR { get; set; }
        public string CUR_STS { get; set; }
        public string OTHER { get; set; }
        public string GRP_SEQ_NO { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> box { get; set; }
        public Nullable<double> import { get; set; }
        public Nullable<double> export { get; set; }
        public Nullable<double> dutyamt { get; set; }
        public Nullable<double> ORD_RAIT { get; set; }
        public Nullable<double> rent_buyamt { get; set; }
        public string GRP_YN { get; set; }
        public string SendAddress { get; set; }
        public Nullable<System.DateTime> APRV_DATE { get; set; }
        public string APRV_Emp { get; set; }
        public Nullable<int> PAY_TYPE { get; set; }
        public string PAY_DATE { get; set; }
        public Nullable<int> RECV_CODE { get; set; }
        public Nullable<int> INV_ADDR { get; set; }
        public string INV_ADDROTHER { get; set; }
        public Nullable<System.DateTime> BUILD_DATE { get; set; }
        public Nullable<double> RGT_CAPT_AMT { get; set; }
        public string SALES_ITEM { get; set; }
        public Nullable<double> SALE_NET_AMT1 { get; set; }
        public Nullable<double> PROFIT1 { get; set; }
        public string OTH_DESC { get; set; }
        public string CUS_NAME { get; set; }
        public string CUS_UNITE { get; set; }
        public string CUS_LIAISE { get; set; }
        public string INC_TEL { get; set; }
        public Nullable<double> OBJ_TOL_AMT { get; set; }
        public Nullable<int> PAY_STS { get; set; }
        public string PAY_DATE1 { get; set; }
    }
}
