//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALEDEPREC
    {
        public int Rec_Num { get; set; }
        public Nullable<int> Rec_Cus { get; set; }
        public string Rec_Meat { get; set; }
        public string Rec_Scr { get; set; }
        public string Rec_Renew { get; set; }
        public Nullable<System.DateTime> Rec_Update { get; set; }
        public string Rec_Dep { get; set; }
        public Nullable<System.DateTime> Rec_Date { get; set; }
        public string Rec_Time { get; set; }
        public string Rec_Company { get; set; }
        public string Rec_Salse { get; set; }
    }
}
