//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_APLY_AMOUNT
    {
        public int SALE_NUM { get; set; }
        public Nullable<System.DateTime> SALE_DATE { get; set; }
        public string SALE_DEPT { get; set; }
        public string SALE_NAME { get; set; }
        public string SALE_CUSTNAME { get; set; }
        public string SALE_UNITE { get; set; }
        public string SALE_OBJ { get; set; }
        public Nullable<int> SALE_BUY_M { get; set; }
        public Nullable<int> SALE_APLY_M { get; set; }
        public Nullable<System.DateTime> SALE_EXE_DATE { get; set; }
        public Nullable<System.DateTime> SALE_FACTORY_DATE { get; set; }
        public string SALE_OPERATION { get; set; }
        public string SALE_SCR { get; set; }
        public string SALE_RENAME { get; set; }
        public Nullable<System.DateTime> SALE_UPDATE { get; set; }
    }
}
