//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMain
    {
        public int 自動編號 { get; set; }
        public string 主管編號 { get; set; }
        public string 行程編號 { get; set; }
        public Nullable<int> 項目代號 { get; set; }
        public string 行程 { get; set; }
        public Nullable<System.DateTime> 使用日期 { get; set; }
        public string 開始時間 { get; set; }
        public string 結束時間 { get; set; }
        public Nullable<System.DateTime> 例行結束日 { get; set; }
        public string 例行類型 { get; set; }
        public string 星期 { get; set; }
        public string 編輯人員 { get; set; }
        public Nullable<System.DateTime> 建檔日期 { get; set; }
    }
}
