//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityAgree
    {
        public string SEQ_NO { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_id { get; set; }
        public string APLY_COM { get; set; }
        public string DEPT { get; set; }
        public string PROCED_APLY_NO { get; set; }
        public string Cust_no { get; set; }
        public string Cust_Name { get; set; }
        public string Doc1 { get; set; }
        public string Doc2 { get; set; }
        public string Doc3 { get; set; }
        public string Sign_Date { get; set; }
        public string Eff_Date { get; set; }
        public string CON_DATE_TO { get; set; }
        public string End_Note { get; set; }
        public string PACT_no { get; set; }
        public string PACT_Name { get; set; }
        public string OTC { get; set; }
        public string OALT { get; set; }
        public string OAMC { get; set; }
        public string OTI { get; set; }
        public string OTLI { get; set; }
        public string COOPAGREEMENT { get; set; }
        public string Secret_Promise { get; set; }
        public string Doc_Return { get; set; }
        public string Profit_PACT { get; set; }
        public string SPEC_PACT { get; set; }
        public string BLOC { get; set; }
        public string OffshoreYN { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string CON_MAN { get; set; }
        public Nullable<System.DateTime> CON_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Scen_File { get; set; }
        public string con_date_all { get; set; }
        public string OEC { get; set; }
        public string SPC { get; set; }
    }
}
