//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Reporder
    {
        public string Order_No { get; set; }
        public string Cust_no { get; set; }
        public string Car_Name1 { get; set; }
        public string Car_Name2 { get; set; }
        public Nullable<int> Car_Person { get; set; }
        public string Car_Tel1 { get; set; }
        public string Car_Tel2 { get; set; }
        public string Cur_STS { get; set; }
        public string Car_Pay { get; set; }
        public string Pay_Type { get; set; }
        public string Scr_Need { get; set; }
        public string Entry_Dept { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Modify_ID { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public string INV_STS { get; set; }
        public string INV_Scr { get; set; }
        public string Car_Name3 { get; set; }
        public string Car_Tel3 { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Case_Sour { get; set; }
        public string assistant { get; set; }
    }
}
