//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_cost
    {
        public string Licence_type { get; set; }
        public string vend_no { get; set; }
        public Nullable<int> Hire { get; set; }
        public Nullable<double> Hire3 { get; set; }
        public Nullable<double> Hire1 { get; set; }
        public Nullable<double> Hire6 { get; set; }
        public Nullable<double> Hire10 { get; set; }
        public Nullable<double> HireH { get; set; }
        public Nullable<double> HireS { get; set; }
        public int SEQ { get; set; }
        public string Entry_Id { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Modify_Id { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public string StopYN { get; set; }
    }
}
