//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_ETAGPay
    {
        public string ETAG_NO { get; set; }
        public Nullable<int> PAGE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public Nullable<System.DateTime> Date_FR { get; set; }
        public Nullable<System.DateTime> Date_To { get; set; }
        public string PAY_TYPE { get; set; }
        public string DEPT { get; set; }
    }
}
