//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Contract
    {
        public string Trn_no { get; set; }
        public string Ration_Addr { get; set; }
        public string Ration_Place { get; set; }
        public string Recver { get; set; }
        public string Taker { get; set; }
        public string Aply_no { get; set; }
        public Nullable<System.DateTime> USE_Date { get; set; }
        public string USE_Class { get; set; }
        public string USE_Cause { get; set; }
        public string Memo { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string Send_no { get; set; }
    }
}
