//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign_AgreeBook
    {
        public int SEQ { get; set; }
        public string ID_NO { get; set; }
        public string CHECK_USER { get; set; }
        public Nullable<System.DateTime> IN_STOCK_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<int> RIGHT_QTY { get; set; }
        public Nullable<int> COPY_QTY { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
        public string assistant { get; set; }
        public string Scen_File { get; set; }
        public string MEMO { get; set; }
        public string Aply_No { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string IN_STOCK_Num { get; set; }
    }
}
