//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public int ID { get; set; }
        public string Sort { get; set; }
        public string Name { get; set; }
        public string HREF { get; set; }
        public string APLY_COM { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Crd_AddName { get; set; }
        public Nullable<System.DateTime> ADD_DATE { get; set; }
        public string Re_ID { get; set; }
        public Nullable<System.DateTime> Re_Date { get; set; }
        public string DelYN { get; set; }
        public Nullable<int> SEQ { get; set; }
    }
}
