//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USBCarry
    {
        public int Cy_Num { get; set; }
        public Nullable<System.DateTime> Cy_Date { get; set; }
        public string Cy_Name { get; set; }
        public Nullable<int> Cy_Class { get; set; }
        public Nullable<System.DateTime> Cy_LendD { get; set; }
        public string Cy_LendH { get; set; }
        public Nullable<System.DateTime> Cy_LendED { get; set; }
        public string Cy_LendEH { get; set; }
        public string Cy_Cause { get; set; }
        public string Cy_Boss { get; set; }
        public Nullable<System.DateTime> Cy_BossD { get; set; }
        public Nullable<System.DateTime> Cy_Mis { get; set; }
        public Nullable<System.DateTime> Cy_Update { get; set; }
        public string Cy_Lend { get; set; }
        public string Cy_YN { get; set; }
        public Nullable<System.DateTime> Cy_YNdate { get; set; }
        public string Cy_YNname { get; set; }
        public string Cy_MisScr { get; set; }
        public string Cy_State { get; set; }
        public Nullable<int> Cy_USB { get; set; }
    }
}
