//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WB6101
    {
        public string ID_NO { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string NickName { get; set; }
        public string LeaveCode { get; set; }
        public string WorkingTime { get; set; }
        public string TurnTeamCode { get; set; }
        public string Traffic { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeDate { get; set; }
        public string LeaveDate { get; set; }
        public string JobReMain { get; set; }
        public string ReturnDate { get; set; }
        public string LeaveStDate { get; set; }
        public string ReductedSen { get; set; }
        public string ReCo_Sen { get; set; }
        public string EmploymtSen { get; set; }
        public string LeaveCDate { get; set; }
        public string LeaveSen { get; set; }
        public string ImageFile { get; set; }
        public string OrganizeCode { get; set; }
        public string DevGrpCode { get; set; }
        public string JobGradeCode { get; set; }
        public string JobTitleCode { get; set; }
        public string MageStutusCo { get; set; }
        public string Company { get; set; }
        public string Area { get; set; }
        public string Devision { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Field { get; set; }
        public string CostCode { get; set; }
        public string JobGrade { get; set; }
        public string JobTitle { get; set; }
        public string MageStutus { get; set; }
        public string CollarCode { get; set; }
        public string Emp_StatusCo { get; set; }
        public string OfficeCode { get; set; }
        public string SpecStatus1 { get; set; }
        public string SpecStatus2 { get; set; }
        public string SpecStatus3 { get; set; }
        public string SpecStatus4 { get; set; }
        public string SpecStatus5 { get; set; }
        public string DcMrg { get; set; }
        public string DcMrgName { get; set; }
        public string JobBackUp { get; set; }
        public string JobBkUpName { get; set; }
        public string NationCode { get; set; }
        public string OverSeaNat { get; set; }
        public string OverSeaLocal { get; set; }
        public string OverSea_Form { get; set; }
        public string OverSea_End { get; set; }
        public string CostRate01 { get; set; }
        public string CostRate02 { get; set; }
        public string CostRate03 { get; set; }
        public string CostRate04 { get; set; }
        public string CostRate05 { get; set; }
        public string LeaveSDt { get; set; }
        public string LeaveCDt { get; set; }
        public string LaDo_01 { get; set; }
        public string LaLv_01 { get; set; }
        public string Spec_01 { get; set; }
        public string Leav_01 { get; set; }
        public string LeLa_01 { get; set; }
        public string DoLv_01 { get; set; }
        public string LvLv_01 { get; set; }
        public string LvPs_01 { get; set; }
        public string LaDo_02 { get; set; }
        public string LaLv_02 { get; set; }
        public string Spec_02 { get; set; }
        public string Leav_02 { get; set; }
        public string LeLa_02 { get; set; }
        public string DoLv_02 { get; set; }
        public string LvLv_02 { get; set; }
        public string LvPs_02 { get; set; }
        public string LaDo_03 { get; set; }
        public string LaLv_03 { get; set; }
        public string Spec_03 { get; set; }
        public string Leav_03 { get; set; }
        public string LeLa_03 { get; set; }
        public string DoLv_03 { get; set; }
        public string LvLv_03 { get; set; }
        public string LvPs_03 { get; set; }
        public string LaDo_04 { get; set; }
        public string LaLv_04 { get; set; }
        public string Spec_04 { get; set; }
        public string Leav_04 { get; set; }
        public string LeLa_04 { get; set; }
        public string DoLv_04 { get; set; }
        public string LvLv_04 { get; set; }
        public string LvPs_04 { get; set; }
        public string LaDo_05 { get; set; }
        public string LaLv_05 { get; set; }
        public string Spec_05 { get; set; }
        public string Leav_05 { get; set; }
        public string LeLa_05 { get; set; }
        public string DoLv_05 { get; set; }
        public string LvLv_05 { get; set; }
        public string LvPs_05 { get; set; }
        public string LaDo_06 { get; set; }
        public string LaLv_06 { get; set; }
        public string Spec_06 { get; set; }
        public string Leav_06 { get; set; }
        public string LeLa_06 { get; set; }
        public string DoLv_06 { get; set; }
        public string LvLv_06 { get; set; }
        public string LvPs_06 { get; set; }
        public string LaDo_07 { get; set; }
        public string LaLv_07 { get; set; }
        public string Spec_07 { get; set; }
        public string Leav_07 { get; set; }
        public string LeLa_07 { get; set; }
        public string DoLv_07 { get; set; }
        public string LvLv_07 { get; set; }
        public string LvPs_07 { get; set; }
        public string LaDo_08 { get; set; }
        public string LaLv_08 { get; set; }
        public string Spec_08 { get; set; }
        public string Leav_08 { get; set; }
        public string LeLa_08 { get; set; }
        public string DoLv_08 { get; set; }
        public string LvLv_08 { get; set; }
        public string LvPs_08 { get; set; }
        public string LaDo_09 { get; set; }
        public string LaLv_09 { get; set; }
        public string Spec_09 { get; set; }
        public string Leav_09 { get; set; }
        public string LeLa_09 { get; set; }
        public string DoLv_09 { get; set; }
        public string LvLv_09 { get; set; }
        public string LvPs_09 { get; set; }
        public string LaDo_10 { get; set; }
        public string LaLv_10 { get; set; }
        public string Spec_10 { get; set; }
        public string Leav_10 { get; set; }
        public string LeLa_10 { get; set; }
        public string DoLv_10 { get; set; }
        public string LvLv_10 { get; set; }
        public string LvPs_10 { get; set; }
        public string LaDo_11 { get; set; }
        public string LaLv_11 { get; set; }
        public string Spec_11 { get; set; }
        public string Leav_11 { get; set; }
        public string LeLa_11 { get; set; }
        public string DoLv_11 { get; set; }
        public string LvLv_11 { get; set; }
        public string LvPs_11 { get; set; }
        public string LaDo_12 { get; set; }
        public string LaLv_12 { get; set; }
        public string Spec_12 { get; set; }
        public string Leav_12 { get; set; }
        public string LeLa_12 { get; set; }
        public string DoLv_12 { get; set; }
        public string LvLv_12 { get; set; }
        public string LvPs_12 { get; set; }
        public string LastModeDate { get; set; }
        public string LastModeTime { get; set; }
        public string LastModePs { get; set; }
        public string LastModeMn { get; set; }
    }
}
