//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixOtcModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkEmp
    {
        public int Work_Num { get; set; }
        public Nullable<System.DateTime> Work_Date { get; set; }
        public string Work_Dept { get; set; }
        public string Work_Name { get; set; }
        public Nullable<System.DateTime> Work_Adate { get; set; }
        public string Work_Week { get; set; }
        public string Work_Start { get; set; }
        public string Work_Stop { get; set; }
        public string Work_Scr { get; set; }
        public string Work_Yes { get; set; }
        public string Work_BossId { get; set; }
        public string Work_State { get; set; }
        public string Work_Boss { get; set; }
        public Nullable<System.DateTime> Work_Bdate { get; set; }
        public Nullable<double> Work_Day { get; set; }
        public Nullable<double> Work_Time { get; set; }
        public string Work_Class { get; set; }
        public string Work_ID { get; set; }
        public string Work_Sdate { get; set; }
        public string Work_TimeT { get; set; }
        public string Work_Com { get; set; }
        public Nullable<System.DateTime> Aply_Date { get; set; }
        public Nullable<System.DateTime> Fare_Date { get; set; }
        public Nullable<System.DateTime> Work_BossA { get; set; }
        public string Work_AStart { get; set; }
        public string Work_AStop { get; set; }
        public string Work_Deal { get; set; }
        public string Boss2 { get; set; }
        public string behind_Cause { get; set; }
        public Nullable<System.DateTime> behind_Date { get; set; }
        public Nullable<System.DateTime> Boss2_Date { get; set; }
        public string Boss2_NoCause { get; set; }
        public string Boss2_YN { get; set; }
        public Nullable<System.DateTime> Boss2_AplyDate { get; set; }
        public Nullable<System.DateTime> Boss2_FareDate { get; set; }
    }
}
