USE [USCACCT]
GO

/****** Object:  Table [dbo].[ACC18]    Script Date: 04/27/2015 14:47:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ACC18](
	[BANK_NO] [varchar](10) NOT NULL,
	[BANK_NAME] [varchar](40) NULL,
	[BANK_ABBR] [varchar](10) NULL,
	[REMK] [varchar](60) NULL,
	[ENTRY_ID] [varchar](10) NULL,
	[ENTRY_DATE] [varchar](10) NULL,
	[ENTRY_TIME] [varchar](8) NULL,
	[MODIFY_ID] [varchar](10) NULL,
	[MODIFY_DATE] [varchar](10) NULL,
	[MODIFY_TIME] [varchar](8) NULL,
 CONSTRAINT [PK_ACC18] PRIMARY KEY NONCLUSTERED 
(
	[BANK_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

