//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC10
    {
        public string MANU_NO { get; set; }
        public string MANU_NAME { get; set; }
        public string MANU_ABBR { get; set; }
        public string MANU_NAME_ENG { get; set; }
        public string MANU_ABBR_ENG { get; set; }
        public string FOR_YN { get; set; }
        public string CORP_KIND { get; set; }
        public string UNIF_NO { get; set; }
        public string TAX_NO { get; set; }
        public string CHIEF_NAME { get; set; }
        public string CONT_NAME { get; set; }
        public string ZIP_CODE { get; set; }
        public string ADDR_MANU { get; set; }
        public string ADDR_ENG { get; set; }
        public string ZIP_CONT { get; set; }
        public string ADDR_CONT { get; set; }
        public string ADDR_CONT_ENG { get; set; }
        public string ADDR_INVO { get; set; }
        public string TEL_MANU { get; set; }
        public string FAX_MANU { get; set; }
        public string EMAIL { get; set; }
        public string EMP_NO { get; set; }
        public string PURC_NAME { get; set; }
        public string ACCT_NO { get; set; }
        public string RELA_NAME { get; set; }
        public string BANK_NO { get; set; }
        public string BEGIN_DATE { get; set; }
        public string REMK { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string FIELD_6 { get; set; }
        public string FIELD_7 { get; set; }
        public string FIELD_8 { get; set; }
        public string FIELD_9 { get; set; }
        public string FIELD_10 { get; set; }
    }
}
