//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC11
    {
        public string CUST_NO { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_ABBR { get; set; }
        public string CUST_NAME_ENG { get; set; }
        public string CUST_ABBR_ENG { get; set; }
        public string FOR_YN { get; set; }
        public string EDI_NO { get; set; }
        public string CORP_KIND { get; set; }
        public string UNIF_NO { get; set; }
        public string TAX_NO { get; set; }
        public string CHIEF_NAME { get; set; }
        public string TEL_CUST { get; set; }
        public string FAX_CUST { get; set; }
        public string ZIP_CODE { get; set; }
        public string ADDR_CUST { get; set; }
        public string ADDR_ENG { get; set; }
        public string ZIP_CONT { get; set; }
        public string ADDR_CONT { get; set; }
        public string CONT_NAME { get; set; }
        public string ADDR_CONT_ENG { get; set; }
        public string ADDR_INVO { get; set; }
        public string INVO_TITLE { get; set; }
        public string ZIP_ACCT { get; set; }
        public string ADDR_ACCT { get; set; }
        public string ACCT_NAME { get; set; }
        public string TEL_ACCT { get; set; }
        public string ZIP_CORP { get; set; }
        public string ADDR_CORP { get; set; }
        public string CORP_NAME { get; set; }
        public string TEL_CORP { get; set; }
        public string EMAIL { get; set; }
        public string EMP_NO { get; set; }
        public string RECE_WAY { get; set; }
        public Nullable<short> CONT_NUM { get; set; }
        public Nullable<short> MM_DAY { get; set; }
        public string TRADE_COND { get; set; }
        public string PAY_WAY { get; set; }
        public Nullable<short> PAY_DAY { get; set; }
        public string ACCT_NO { get; set; }
        public string BANK_NO { get; set; }
        public string CRED_GRADE { get; set; }
        public Nullable<double> DISC_RATE { get; set; }
        public string ST_DATE { get; set; }
        public string END_DATE { get; set; }
        public string SALE_CUST_PROD { get; set; }
        public Nullable<decimal> CRED_AMT { get; set; }
        public string BAL_OR_SA { get; set; }
        public string ORDER_MUST { get; set; }
        public string AREA_CODE { get; set; }
        public string SALE_TYPE { get; set; }
        public string BEGIN_DATE { get; set; }
        public string SALE_NO { get; set; }
        public string SCORP_NO { get; set; }
        public string SDEPT_NO { get; set; }
        public string PAY_RANGE { get; set; }
        public string REMK { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string XTYPE { get; set; }
        public string COM { get; set; }
        public string BELONG_TO { get; set; }
        public string JOIN_SELF_TYPE { get; set; }
        public string TAX_INNER_TYPE { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string FIELD_6 { get; set; }
        public string FIELD_7 { get; set; }
        public string FIELD_8 { get; set; }
        public string FIELD_9 { get; set; }
        public string FIELD_10 { get; set; }
        public string ATTACH_PAPER { get; set; }
        public string INVO_XTYPE { get; set; }
    }
}
