//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminId
    {
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 帳號管理 { get; set; }
        public string 留言交辦事項 { get; set; }
        public string 公佈欄管理 { get; set; }
        public string OTC會計報修 { get; set; }
        public string OTC營業報修 { get; set; }
        public string 個人首頁 { get; set; }
        public string 行程管理 { get; set; }
        public string 預約借用 { get; set; }
        public string 資金預撥 { get; set; }
        public string 文件委外 { get; set; }
        public string 文件送出調回 { get; set; }
        public string 福利社 { get; set; }
        public string 新人登錄 { get; set; }
        public string 離職人員 { get; set; }
        public string 延時加班申請 { get; set; }
        public string 耗材申請 { get; set; }
        public string 庫存管理 { get; set; }
        public string 會計預算 { get; set; }
        public string 缺曠職 { get; set; }
        public string 機房日誌 { get; set; }
        public string 保險專區 { get; set; }
        public string 測試 { get; set; }
        public string 員工出差 { get; set; }
        public string 催收作業 { get; set; }
        public string NB攜出 { get; set; }
        public string AMC專區 { get; set; }
        public string OTC專區 { get; set; }
        public string OALT專區 { get; set; }
        public string OTI專區 { get; set; }
        public string POP專區 { get; set; }
        public string 所得稅專區 { get; set; }
        public string 是否派外 { get; set; }
        public string 假日調整 { get; set; }
        public string 租賃系統 { get; set; }
        public string 影像憑證 { get; set; }
        public string 退票通知 { get; set; }
        public string 簽呈追蹤 { get; set; }
        public string OALT問卷調查 { get; set; }
        public string 印花稅 { get; set; }
        public string REO { get; set; }
        public string 徵信借出 { get; set; }
        public string 職務代理人 { get; set; }
        public string 單位分組 { get; set; }
        public string 假日登入 { get; set; }
        public string 出勤歷史記錄 { get; set; }
        public string 建立者 { get; set; }
        public string HR人事維護 { get; set; }
        public Nullable<System.DateTime> 修改時間 { get; set; }
        public string 人事作業申請 { get; set; }
        public string C0800專線 { get; set; }
        public string OALT交辦事項 { get; set; }
        public string 債權憑證未歸還 { get; set; }
        public string 欠件模組 { get; set; }
        public string CCIS { get; set; }
        public string OALT催收 { get; set; }
        public string CCIS單位分組 { get; set; }
        public string OAT影像憑證 { get; set; }
        public string OAT影像新增 { get; set; }
        public string OAT簽呈觀看 { get; set; }
        public string OAT應收帳款觀看 { get; set; }
        public string 發文行文 { get; set; }
        public string 公司證明文件 { get; set; }
        public string 公務車借用 { get; set; }
        public string 類別 { get; set; }
        public string 角色 { get; set; }
        public string 先行出具合約申請 { get; set; }
        public string OneStop { get; set; }
        public string OneStop觀看 { get; set; }
        public string 收發信件 { get; set; }
        public string OALT客服 { get; set; }
        public string 短租使用者 { get; set; }
        public string 肯美案件確認 { get; set; }
        public string 電腦權限申請 { get; set; }
        public string 債權憑證屆期日 { get; set; }
        public string 回饋金 { get; set; }
        public string 快遞登記 { get; set; }
        public string 個資同意書 { get; set; }
        public string 致贈禮品 { get; set; }
        public string 債管課外訪申請 { get; set; }
        public string JCIC { get; set; }
        public string 工作日誌 { get; set; }
        public string OALTQA { get; set; }
        public string 廉潔保密 { get; set; }
        public string 定存單 { get; set; }
    }
}
