//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCREO
    {
        public int Reo_Num { get; set; }
        public string Reo_Subject { get; set; }
        public string Reo_Scr { get; set; }
        public string Reo_File { get; set; }
        public string Reo_Boss { get; set; }
        public Nullable<System.DateTime> Reo_Date { get; set; }
        public Nullable<System.DateTime> Reo_BossD { get; set; }
        public string Reo_Name { get; set; }
    }
}
