//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beforehand
    {
        public int SEQ { get; set; }
        public string Doc_Status { get; set; }
        public Nullable<System.DateTime> Aply_Date { get; set; }
        public string assistant { get; set; }
        public string Aply_no { get; set; }
        public string Cust_Name { get; set; }
        public string Aply_Person { get; set; }
        public string Main { get; set; }
        public string Content { get; set; }
        public string Boss_emp { get; set; }
        public Nullable<System.DateTime> AtmBossD { get; set; }
        public string WorkBoss { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Crd_Boss { get; set; }
        public string LVLClass { get; set; }
    }
}
