//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareMain
    {
        public int 自動編號 { get; set; }
        public string 借用編號 { get; set; }
        public Nullable<int> 車子編號 { get; set; }
        public string 借用人 { get; set; }
        public string 借用目的 { get; set; }
        public Nullable<System.DateTime> 使用日期 { get; set; }
        public string 開始時間 { get; set; }
        public string 結束時間 { get; set; }
        public Nullable<System.DateTime> 例行結束日 { get; set; }
        public string 例行類型 { get; set; }
        public string 星期 { get; set; }
        public Nullable<System.DateTime> 借用日期 { get; set; }
        public string 建檔人 { get; set; }
        public string 建檔人編號 { get; set; }
        public Nullable<double> Car_Sodometer { get; set; }
        public Nullable<double> Car_Eodometer { get; set; }
        public Nullable<double> Car_Additive { get; set; }
        public Nullable<double> Car_Amount { get; set; }
        public Nullable<double> Car_Money { get; set; }
        public Nullable<System.DateTime> Car_Return { get; set; }
        public string Car_Company { get; set; }
        public string Car_Area { get; set; }
        public Nullable<System.DateTime> Car_Magger { get; set; }
        public Nullable<System.DateTime> Car_Keep { get; set; }
        public Nullable<System.DateTime> Car_out { get; set; }
        public string Car_Send { get; set; }
        public Nullable<double> Car_Time { get; set; }
        public Nullable<double> Car_Additive2 { get; set; }
        public Nullable<double> Car_Amount2 { get; set; }
        public Nullable<double> Car_Money2 { get; set; }
        public Nullable<double> Car_Additive3 { get; set; }
        public Nullable<double> Car_Amount3 { get; set; }
        public Nullable<double> Car_Money3 { get; set; }
        public Nullable<System.DateTime> p_deliver_date { get; set; }
        public string p_deliver_time { get; set; }
        public Nullable<System.DateTime> p_return_date { get; set; }
        public string p_return_time { get; set; }
        public string Cy_Class { get; set; }
        public string Remark { get; set; }
        public Nullable<double> total_amt_e { get; set; }
        public string Dept { get; set; }
        public string EXT { get; set; }
        public string mobile_no { get; set; }
        public string statelliteYN { get; set; }
        public string OverTimeYN { get; set; }
        public string OverTime { get; set; }
        public Nullable<int> gas_ticket { get; set; }
        public Nullable<int> dis_vehicle { get; set; }
        public Nullable<int> use_money { get; set; }
        public string statelliteR { get; set; }
        public string Pay_STS { get; set; }
        public string use_time { get; set; }
        public string BorrowScr { get; set; }
        public Nullable<int> TimeMoney { get; set; }
        public string gas_ticketno { get; set; }
        public string Boss2 { get; set; }
        public string Cy_Name { get; set; }
        public string 標示刪除 { get; set; }
        public string entry_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> Del_Date { get; set; }
        public string AMCOverTimeYN { get; set; }
        public Nullable<System.DateTime> AMCOverTime { get; set; }
        public string Crd_Boss { get; set; }
        public Nullable<System.DateTime> Boss_Date { get; set; }
        public string Boss_Sign { get; set; }
        public string Crd_Del { get; set; }
    }
}
