//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAply
    {
        public int Crd_Num { get; set; }
        public string Crd_Aply { get; set; }
        public Nullable<System.DateTime> Crd_AplyDate { get; set; }
        public string Crd_Cause { get; set; }
        public string Crd_Boss { get; set; }
        public Nullable<System.DateTime> Crd_BDate { get; set; }
        public string Crd_State { get; set; }
        public string Crd_POut { get; set; }
        public Nullable<System.DateTime> Crd_PDate { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Crd_Boss2 { get; set; }
        public Nullable<System.DateTime> Crd_BDate2 { get; set; }
    }
}
