//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCopy
    {
        public int RowID { get; set; }
        public string copyNo { get; set; }
        public string copyType { get; set; }
        public string company { get; set; }
        public Nullable<System.DateTime> kdate { get; set; }
        public string kuser { get; set; }
        public string IsCancel { get; set; }
        public string cancelUser { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string cancelChk { get; set; }
        public Nullable<System.DateTime> cancelChkDate { get; set; }
        public string IsBorrow { get; set; }
        public string Crd_State { get; set; }
        public string Scr { get; set; }
    }
}
