//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTime
    {
        public int SEQ { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<System.DateTime> Appoint_Date { get; set; }
        public string Scr { get; set; }
        public string entry_id { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Doc_Status { get; set; }
    }
}
