//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomApprove
    {
        public int App_Num { get; set; }
        public string App_Licence_no { get; set; }
        public string App_Custom { get; set; }
        public string App_User { get; set; }
        public string App_Service { get; set; }
        public Nullable<System.DateTime> App_ServiceDate { get; set; }
        public Nullable<int> App_Item { get; set; }
        public string App_OALT { get; set; }
        public string App_Q1 { get; set; }
        public string App_Q2 { get; set; }
        public Nullable<int> App_Q3 { get; set; }
        public Nullable<int> App_Q4 { get; set; }
        public Nullable<int> App_Q5 { get; set; }
        public Nullable<int> App_Q6 { get; set; }
        public Nullable<int> App_Q7 { get; set; }
        public Nullable<int> App_Q8 { get; set; }
        public Nullable<int> App_Q9 { get; set; }
        public Nullable<int> App_Q10 { get; set; }
        public Nullable<int> App_Q11 { get; set; }
        public string Q3_Scr { get; set; }
        public string Q4_Scr { get; set; }
        public string Q5_Scr { get; set; }
        public string Q6_Scr { get; set; }
        public string Q7_Scr { get; set; }
        public string Q8_Scr { get; set; }
        public string Q9_Scr { get; set; }
        public string Q10_Scr { get; set; }
        public string Q11_Scr { get; set; }
        public string Q12_Scr { get; set; }
        public Nullable<System.DateTime> App_AddDate { get; set; }
        public string YN { get; set; }
        public string App_AddName { get; set; }
        public Nullable<int> App_NScr { get; set; }
        public string App_Dept { get; set; }
        public string App_Tel { get; set; }
        public string TELRecord { get; set; }
        public string CARRecord { get; set; }
        public Nullable<int> RecponseCode { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string hap_name { get; set; }
        public string mobile_no { get; set; }
        public string Insurance_Kind { get; set; }
    }
}
