//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTravel
    {
        public int Tr_Num { get; set; }
        public string Tr_Name { get; set; }
        public string Tr_ID { get; set; }
        public string Tr_Emp { get; set; }
        public string Tr_YN { get; set; }
        public string Tr_Day2 { get; set; }
        public string Tr_Day3 { get; set; }
        public Nullable<System.DateTime> Tr_Update { get; set; }
        public string Tr_Renew { get; set; }
        public string Tr_Share { get; set; }
        public string Tr_Birthday { get; set; }
    }
}
