//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiStock
    {
        public int 耗材代號 { get; set; }
        public int 類別代號 { get; set; }
        public string 品名 { get; set; }
        public string 規格 { get; set; }
        public string 單位 { get; set; }
        public Nullable<double> 單價 { get; set; }
        public Nullable<int> 庫存數量 { get; set; }
        public string 備註 { get; set; }
        public string 照片 { get; set; }
        public Nullable<System.DateTime> 建檔日期 { get; set; }
    }
}
