//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiApply
    {
        public string 申請單號 { get; set; }
        public Nullable<int> 類別代號 { get; set; }
        public string 申請人帳號 { get; set; }
        public string 申請部門 { get; set; }
        public string 申請人姓名 { get; set; }
        public Nullable<System.DateTime> 申請日期 { get; set; }
        public Nullable<int> 申請筆數 { get; set; }
        public string 用途說明 { get; set; }
        public string 其它項目 { get; set; }
        public string 主管核准 { get; set; }
        public Nullable<System.DateTime> 主管核准日 { get; set; }
        public string 主管帳號 { get; set; }
        public string 處理結果 { get; set; }
        public string 處理人姓名 { get; set; }
        public Nullable<System.DateTime> 處理日期 { get; set; }
        public string 完成說明 { get; set; }
        public Nullable<System.DateTime> 完成日期 { get; set; }
        public string 須核准 { get; set; }
        public string 處理狀態 { get; set; }
        public string 標示刪除 { get; set; }
    }
}
