//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gudata_OLD
    {
        public string ctcontno { get; set; }
        public short ctpaytrm { get; set; }
        public Nullable<short> ctterman { get; set; }
        public string gudate { get; set; }
        public string ctcustno { get; set; }
        public string ctpaydat { get; set; }
        public Nullable<decimal> cttermpa { get; set; }
        public Nullable<decimal> ctretvat { get; set; }
        public Nullable<decimal> ctrecinc { get; set; }
        public Nullable<decimal> ctrental { get; set; }
        public Nullable<decimal> ctrentba { get; set; }
        public Nullable<decimal> ctunrein { get; set; }
        public Nullable<decimal> ctrarein { get; set; }
        public string taxtype { get; set; }
        public string ctguissu { get; set; }
        public string filter { get; set; }
        public string cusno { get; set; }
        public string entrydate { get; set; }
        public string deptno { get; set; }
        public string RECPKIND { get; set; }
        public string ACCANO { get; set; }
        public Nullable<decimal> SERV_CHAR_OVER { get; set; }
        public string ACPT_DIVD { get; set; }
        public string CTAPLYNO { get; set; }
        public string CREATE_MTHD { get; set; }
        public string START_DATE { get; set; }
        public string INV_DATE { get; set; }
        public string INV_NO { get; set; }
        public string AR_TYPE { get; set; }
        public Nullable<decimal> REAL_AMT { get; set; }
        public Nullable<decimal> REAL_TAX { get; set; }
    }
}
