//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR0101
    {
        public string ID_NO { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string NickName { get; set; }
        public string EnglishName { get; set; }
        public string Brithday { get; set; }
        public string Age { get; set; }
        public string Star { get; set; }
        public string NativePlace { get; set; }
        public string BirthPlace { get; set; }
        public string LivableSours { get; set; }
        public string Blood { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Marital_Code { get; set; }
        public string Marital { get; set; }
        public string NationCode { get; set; }
        public string Nation { get; set; }
        public string Nationality { get; set; }
        public string StatusCode { get; set; }
        public string Status { get; set; }
        public string PassportNo { get; set; }
        public string Termination { get; set; }
        public string PPRec { get; set; }
        public string ARC_Date { get; set; }
        public string ARC_No { get; set; }
        public string ARC_Begin { get; set; }
        public string ARC_End { get; set; }
        public string Religious { get; set; }
        public string PRKind { get; set; }
        public string Military01 { get; set; }
        public string MealStutus { get; set; }
        public string Edu_Code { get; set; }
        public string Edu_Degree { get; set; }
        public string EducatSch { get; set; }
        public string MajorSub { get; set; }
        public string Finish { get; set; }
        public string GradStatus { get; set; }
        public string Edu_Degree_1 { get; set; }
        public string EducatSch_1 { get; set; }
        public string MajorSub_1 { get; set; }
        public string Finish_1 { get; set; }
        public string GradStatus_1 { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string Personal { get; set; }
        public string EmployeeNo { get; set; }
        public string ImageFile { get; set; }
        public string LeaveCode { get; set; }
        public string WorkingTime { get; set; }
        public string PayStatus { get; set; }
        public string OrganizeCod1 { get; set; }
        public string DevGrpCode1 { get; set; }
        public string JobGradeCod1 { get; set; }
        public string JobTitleCod1 { get; set; }
        public string MrgCod1 { get; set; }
        public string Company1 { get; set; }
        public string Department1 { get; set; }
        public string Section1 { get; set; }
        public string Field1 { get; set; }
        public string CostCod1 { get; set; }
        public string CostCenter1 { get; set; }
        public string Dev1 { get; set; }
        public string Grup1 { get; set; }
        public string JobGrade1 { get; set; }
        public string GradeNo1 { get; set; }
        public string Position1 { get; set; }
        public string JobTitle1 { get; set; }
        public string MageStutus1 { get; set; }
        public string OrganizeCode { get; set; }
        public string DevGrpCode { get; set; }
        public string JobGradeCode { get; set; }
        public string JobTitleCode { get; set; }
        public string MageStutusCo { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Field { get; set; }
        public string CostCode { get; set; }
        public string CostCenter { get; set; }
        public string Dev { get; set; }
        public string Grup { get; set; }
        public string JobGrade { get; set; }
        public string GradeNo { get; set; }
        public string Position { get; set; }
        public string JobTitle { get; set; }
        public string MageStutus { get; set; }
        public string CollarCode { get; set; }
        public string Collar { get; set; }
        public string Emp_StatusCo { get; set; }
        public string Emp_Status { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeStatus { get; set; }
        public string Union_Member { get; set; }
        public string JoinDate { get; set; }
        public string JoinLeaveDat { get; set; }
        public string DcMrgID_NO { get; set; }
        public string DcMrg { get; set; }
        public string PsLine { get; set; }
        public string AreaLine { get; set; }
        public string JobBackUp { get; set; }
        public string OverSea_Code { get; set; }
        public string OverSeaNat { get; set; }
        public string OverSeaLocal { get; set; }
        public string OverSea_Form { get; set; }
        public string OverSea_End { get; set; }
        public string OverSea_Day { get; set; }
        public string EmployeeDate { get; set; }
        public string RetireDate { get; set; }
        public string Expiration { get; set; }
        public string LeaveDate { get; set; }
        public string JobReMain { get; set; }
        public string ReturnDate { get; set; }
        public string BreakSen { get; set; }
        public string ReductedSen { get; set; }
        public string ReCo_Sen { get; set; }
        public string CompanySen { get; set; }
        public string EmploymtSen { get; set; }
    }
}
