//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public string Inf_Debie { get; set; }
        public Nullable<System.DateTime> Inf_Out { get; set; }
        public Nullable<System.DateTime> Inf_Enter { get; set; }
        public string Inf_MIS { get; set; }
        public Nullable<int> Inf_Item { get; set; }
        public string Inf_Y { get; set; }
        public string Inf_Content { get; set; }
        public string Inf_Scr { get; set; }
        public Nullable<System.DateTime> Inf_Date { get; set; }
        public int Inf_Num { get; set; }
        public string Inf_Renew { get; set; }
        public string Inf_OutTime { get; set; }
        public string Inf_EnterTime { get; set; }
    }
}
