//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVM02
    {
        public string CORP_NO { get; set; }
        public System.DateTime INVO_YM { get; set; }
        public string INVO_NO { get; set; }
        public Nullable<System.DateTime> INVO_DATE { get; set; }
        public string CUST_NO { get; set; }
        public string INVO_TITLE { get; set; }
        public string UNIF_NO { get; set; }
        public string INVO_ADDRE { get; set; }
        public Nullable<decimal> PROD_AMT { get; set; }
        public string VAT_TYPE { get; set; }
        public Nullable<decimal> VAT_AMT { get; set; }
        public Nullable<decimal> INVO_AMT { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> RD_AMT { get; set; }
    }
}
