//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCICAPLY
    {
        public int SEQ_NO { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_No { get; set; }
        public string Aply_Person { get; set; }
        public Nullable<System.DateTime> Aply_Date { get; set; }
        public string Crd_Boss { get; set; }
        public Nullable<System.DateTime> Crd_Bdate { get; set; }
        public string RUN_Person { get; set; }
        public string Crd_Pin { get; set; }
        public Nullable<System.DateTime> IN_Stock_Date { get; set; }
        public string Proced_file { get; set; }
        public string Proced_Con { get; set; }
        public string entry_id { get; set; }
        public Nullable<System.DateTime> Exe_Date { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Case_No { get; set; }
        public string IF_EXE { get; set; }
        public string Con_Man { get; set; }
        public Nullable<System.DateTime> Con_Date { get; set; }
        public string LEGAL { get; set; }
        public string NUM { get; set; }
        public string CUST_ENAME { get; set; }
        public string BUILD_DATE { get; set; }
        public string CHIEF_NO { get; set; }
        public string CHIEF_NAME { get; set; }
        public string ZIP { get; set; }
        public string RGT_ADDR { get; set; }
        public string TEL { get; set; }
        public string REASON1 { get; set; }
        public string REASON2 { get; set; }
        public string TYPE { get; set; }
        public string PRE_CLASS { get; set; }
        public string CHIEF_ENAME { get; set; }
        public string CHIEF_ADDR { get; set; }
        public string CHIEF_TEL { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> cancelDate { get; set; }
        public string cancelUser { get; set; }
    }
}
