//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class junket
    {
        public System.DateTime jun_Date { get; set; }
        public Nullable<int> jun_Time { get; set; }
        public string jun_Sponsor { get; set; }
        public string jun_Address { get; set; }
        public string jun_Rename { get; set; }
        public Nullable<System.DateTime> jun_Redate { get; set; }
        public string jun_Present { get; set; }
        public string jun_Scr { get; set; }
        public string jun_Payer { get; set; }
        public string jun_Msingle { get; set; }
        public Nullable<int> jun_Mall { get; set; }
        public int jun_Num { get; set; }
    }
}
