//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEX_SallyForth
    {
        public string CaseNum { get; set; }
        public string Sally_Class { get; set; }
        public string Case_Type_Name { get; set; }
        public string Aply_no { get; set; }
        public string Cust_no { get; set; }
        public Nullable<System.DateTime> Sally_Date_S { get; set; }
        public string Sally_Time_S { get; set; }
        public Nullable<System.DateTime> Sally_Date_E { get; set; }
        public string Sally_Time_E { get; set; }
        public string Sally_Addr { get; set; }
        public string AtmCauseScr { get; set; }
        public string Aply_PERSON { get; set; }
        public string Lex1 { get; set; }
        public string Lex2 { get; set; }
        public string Lex3 { get; set; }
        public string Lex4 { get; set; }
        public string Sales1 { get; set; }
        public string Sales2 { get; set; }
        public string Sales3 { get; set; }
        public string Sales4 { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Time { get; set; }
        public string Entry_Date { get; set; }
        public string Modify_ID { get; set; }
        public string Modify_Time { get; set; }
        public string Modify_Date { get; set; }
        public string Lex_Boss { get; set; }
        public Nullable<System.DateTime> Lex_Date { get; set; }
        public string Credit_Boss { get; set; }
        public Nullable<System.DateTime> Credit_Date { get; set; }
        public string CUR_STS { get; set; }
        public string Lex_OPION { get; set; }
        public string Credit_OPION { get; set; }
        public string Press_LEX { get; set; }
        public Nullable<System.DateTime> Press_LEXTime { get; set; }
        public string Press_Credit { get; set; }
        public Nullable<System.DateTime> Press_CreditTime { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Credit_USER { get; set; }
    }
}
