//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machinery
    {
        public Nullable<System.DateTime> M_EnterDate { get; set; }
        public Nullable<System.DateTime> M_OutDate { get; set; }
        public Nullable<int> M_Item { get; set; }
        public string M_Worker { get; set; }
        public string M_Scr { get; set; }
        public string M_Content { get; set; }
        public Nullable<System.DateTime> M_Date { get; set; }
        public int M_Num { get; set; }
        public string M_Renew { get; set; }
        public string M_EnterTime { get; set; }
        public string M_OutTime { get; set; }
        public Nullable<int> M_Host { get; set; }
    }
}
