//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEW契約餘額
    {
        public int ID { get; set; }
        public string 編______號 { get; set; }
        public string 統__編 { get; set; }
        public string 客戶名稱 { get; set; }
        public string 期間 { get; set; }
        public string 購_買_金_額 { get; set; }
        public string 契_約_金_額 { get; set; }
        public string 應收稅額 { get; set; }
        public string 起租日 { get; set; }
        public string 到期日 { get; set; }
        public string 應收帳款餘額 { get; set; }
        public string 應收票據餘額 { get; set; }
        public string 契_約_餘_額 { get; set; }
        public string 當月償還金額 { get; set; }
        public string 未實現利息餘額 { get; set; }
        public string 本金餘額 { get; set; }
    }
}
