//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtMd
    {
        public int EvtID { get; set; }
        public Nullable<int> UrlID { get; set; }
        public string Owner { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string Email { get; set; }
        public Nullable<int> NotifType { get; set; }
        public Nullable<int> LCID { get; set; }
        public Nullable<int> Criteria { get; set; }
        public string Title { get; set; }
        public string SavedBy { get; set; }
        public string RootUrl { get; set; }
    }
}
