//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTQ3
    {
        public int Q3_Num { get; set; }
        public string licenceNo { get; set; }
        public string Care_State { get; set; }
        public string CustName { get; set; }
        public string EnterDate { get; set; }
        public string UserName { get; set; }
        public string KeepItem { get; set; }
        public string UserTel { get; set; }
        public string Liaison { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A4 { get; set; }
        public string A5 { get; set; }
        public string Reception { get; set; }
        public string Add_Name { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
