//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTQ7
    {
        public int App_Num { get; set; }
        public string Order_no { get; set; }
        public string App_Q1 { get; set; }
        public string App_Q2 { get; set; }
        public Nullable<int> App_Q3 { get; set; }
        public Nullable<int> App_Q4 { get; set; }
        public Nullable<int> App_Q5 { get; set; }
        public Nullable<int> App_Q6 { get; set; }
        public Nullable<int> App_Q7 { get; set; }
        public string App_Q8 { get; set; }
        public string App_Q9 { get; set; }
        public Nullable<int> App_Q10 { get; set; }
        public Nullable<int> App_Q11 { get; set; }
        public string Q3_Scr { get; set; }
        public string Q4_Scr { get; set; }
        public string Q5_Scr { get; set; }
        public string Q6_Scr { get; set; }
        public string Q7_Scr { get; set; }
        public string Q8_Scr { get; set; }
        public string Q9_Scr { get; set; }
        public string Q10_Scr { get; set; }
        public string Q11_Scr { get; set; }
        public Nullable<System.DateTime> App_AddDate { get; set; }
        public string YN { get; set; }
        public string App_AddName { get; set; }
        public string TELRecord { get; set; }
        public string CARRecord { get; set; }
        public Nullable<int> RecponseCode { get; set; }
        public Nullable<int> App_NScr { get; set; }
        public string YNScr { get; set; }
        public string Q2_Scr { get; set; }
        public string ResponsetScr { get; set; }
        public string App_Q31 { get; set; }
        public string App_Q32 { get; set; }
        public string App_Q33 { get; set; }
        public string App_Q34 { get; set; }
        public string App_Q35 { get; set; }
        public string App_Q36 { get; set; }
        public string App_Q37 { get; set; }
        public string DOC_STATUS { get; set; }
    }
}
