//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OALTSrvMail
    {
        public int Num { get; set; }
        public string Add_Name { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> PHONE_Date { get; set; }
        public string PHONE_Time { get; set; }
        public string ORD_SCR { get; set; }
        public string listen { get; set; }
        public string SOUR_CODE { get; set; }
        public string SOUR_OTHER { get; set; }
        public string Require_Code { get; set; }
        public string Require_Other { get; set; }
        public string CustNo { get; set; }
        public string Custom { get; set; }
        public string ADDR_INC { get; set; }
        public string TEL { get; set; }
        public string FAX_NO { get; set; }
        public string CTAC { get; set; }
        public string SEX { get; set; }
        public string CTAC_TEL { get; set; }
        public string MOBIL { get; set; }
        public string MAIL_ACCT { get; set; }
        public string OTH_COMMAND { get; set; }
        public string Lincece_Type { get; set; }
        public string LEASE_CATE_CODE { get; set; }
        public Nullable<int> Saloon_QTY { get; set; }
        public Nullable<System.DateTime> Need_Date { get; set; }
        public string Need_Time { get; set; }
        public string Lease_mm { get; set; }
        public string ASUR { get; set; }
        public Nullable<double> USE_mileage { get; set; }
        public string MEMO { get; set; }
        public string DEPT { get; set; }
        public string SALESMAN_CODE { get; set; }
        public string Modify_Id { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public Nullable<System.DateTime> FIRST_DATE { get; set; }
        public string FIRST_TIME { get; set; }
        public string DOC_STATUS { get; set; }
        public string FailScr { get; set; }
        public string FailScr_Other { get; set; }
        public string vend_type { get; set; }
        public Nullable<double> RGT_CAPT_AMT { get; set; }
    }
}
