//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_PAPER_RULE_MASTER
    {
        public string APLY_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string FEE_TYPE { get; set; }
        public string INVOICE_TYPE { get; set; }
        public string FEE_TYPE_OTHER { get; set; }
        public Nullable<decimal> FIX_RENT { get; set; }
        public string EDIT_USER { get; set; }
        public string EDIT_DATETIME { get; set; }
        public Nullable<decimal> XeroxPayDay { get; set; }
        public string CustReceiveMon { get; set; }
        public Nullable<decimal> CustReceiveDays { get; set; }
        public string Notes { get; set; }
        public string InvDesc { get; set; }
        public Nullable<decimal> AplyRent { get; set; }
        public string InvPO { get; set; }
        public string NeedTSA { get; set; }
        public string NeedSpecialDetail { get; set; }
        public string SpecialStatus { get; set; }
        public string XeroxInvPerson { get; set; }
        public string OrixInvPerson { get; set; }
        public string Sades { get; set; }
        public string Spdes { get; set; }
        public string DirectInv { get; set; }
        public string NoteInv { get; set; }
    }
}
