//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_DOC_CHANGE
    {
        public string APLY_NO { get; set; }
        public string ATCH_CODE { get; set; }
        public string CHG_DATE { get; set; }
        public string CHG_STATUS { get; set; }
        public string CHG_SHEET_NO { get; set; }
        public string BR_STATUS { get; set; }
        public string KEY_IN_USER { get; set; }
        public string KEY_IN_DATETIME { get; set; }
    }
}
