//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_DOC_BR_APRV3
    {
        public string SHEET_NO { get; set; }
        public string BR_APRV_PERSON { get; set; }
        public string IF_PASS { get; set; }
        public string APRV_DATE { get; set; }
        public string APRV_OPINION { get; set; }
    }
}
