//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_AR_APLY_COND
    {
        public string APLY_NO { get; set; }
        public Nullable<decimal> APLY_AMT { get; set; }
        public string IS_CIRCLE { get; set; }
        public Nullable<int> CIRCLE_MTH { get; set; }
        public Nullable<decimal> SINGLE_MOST_AMT { get; set; }
        public Nullable<decimal> PAY_PERCENT { get; set; }
        public Nullable<decimal> APLY_TR { get; set; }
        public Nullable<decimal> MAN_CHARGE_PERCENT { get; set; }
        public string MAIN_TRAN_PROD { get; set; }
        public string TRAN_COND { get; set; }
        public string DOC_INVOICE { get; set; }
        public string DOC_ORDER { get; set; }
        public string DOC_SHIP { get; set; }
        public string DOC_SIGN { get; set; }
        public string DOC_TRUNK { get; set; }
        public string DOC_TEST { get; set; }
        public string DOC_OTHER { get; set; }
        public string DOC_OTHER_DESC { get; set; }
        public string PAY_TT { get; set; }
        public string PAY_CHECK { get; set; }
        public string PAY_OTHER { get; set; }
        public string PAY_OTHER_DESC { get; set; }
        public string CHECK_ALL { get; set; }
        public string LOCAL_CUST { get; set; }
        public string OBL_TRANS_NOTY { get; set; }
        public string COM_CHECK { get; set; }
        public string SELL_CHECK { get; set; }
        public string BUYER_CHECK { get; set; }
        public string REMARK { get; set; }
        public string COND_TRADE { get; set; }
        public string MOV_ASUR_IMP { get; set; }
        public string AUTH_LIEN_TARG { get; set; }
        public string BUY_PROM_TARG { get; set; }
        public string OTH_BUY_TARG { get; set; }
        public Nullable<decimal> COND_TRADE_AMT { get; set; }
        public Nullable<decimal> MOV_ASUR_AMT { get; set; }
        public Nullable<decimal> AUTH_LIEN_AMT { get; set; }
        public Nullable<decimal> BUY_PROM_AMT { get; set; }
        public Nullable<decimal> OTH_AMT { get; set; }
        public Nullable<decimal> APLY_TR_REAL { get; set; }
    }
}
