//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_AR_APLY_SHARE_DET_1
    {
        public string PAY_APLY_NO { get; set; }
        public int PERIOD { get; set; }
        public Nullable<double> RECV_ACCT { get; set; }
        public Nullable<double> INTRST { get; set; }
        public Nullable<double> MG_FEE { get; set; }
        public Nullable<double> CAPT_AMOR { get; set; }
        public Nullable<double> CAPT_SUR { get; set; }
    }
}
