//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_PAPER_USE_DTL_TEMP
    {
        public string APLY_NO { get; set; }
        public int period { get; set; }
        public string MAC_NO { get; set; }
        public string YEAR_MONTH { get; set; }
        public string STAR_DATE { get; set; }
        public string PEND_DATE { get; set; }
        public string UNIF_NO { get; set; }
        public string SPEC { get; set; }
        public string CASE_NO { get; set; }
        public Nullable<decimal> MONTH_FEE { get; set; }
        public Nullable<decimal> BASE_FEE_COLOR { get; set; }
        public Nullable<decimal> BASE_FEE_MONO { get; set; }
        public Nullable<decimal> FREE_QTY_COLOR { get; set; }
        public Nullable<decimal> FREE_QTY_MONO { get; set; }
        public Nullable<decimal> USE_QTY_COLOR { get; set; }
        public Nullable<decimal> USE_QTY_MONO { get; set; }
        public Nullable<decimal> ONE_PRICE_COLOR { get; set; }
        public Nullable<decimal> ONE_PRICE_MONO { get; set; }
        public Nullable<decimal> ONE_PRICE_A3_COLOR { get; set; }
        public Nullable<decimal> ONE_PRICE_A3_MONO { get; set; }
        public Nullable<decimal> SUBTOT_COLOR { get; set; }
        public Nullable<decimal> SUBTOT_MONO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> FREE_QTY_A3_COLOR { get; set; }
        public Nullable<decimal> FREE_QTY_A3_MONO { get; set; }
        public Nullable<decimal> USE_QTY_A3_COLOR { get; set; }
        public Nullable<decimal> USE_QTY_A3_MONO { get; set; }
        public Nullable<decimal> SUM_A4_COLOR { get; set; }
        public Nullable<decimal> SUM_A4_COLOR_LAST { get; set; }
        public Nullable<decimal> SUM_A4_MONO { get; set; }
        public Nullable<decimal> SUM_A4_MONO_LAST { get; set; }
        public Nullable<decimal> SUM_A3_COLOR { get; set; }
        public Nullable<decimal> SUM_A3_COLOR_LAST { get; set; }
        public Nullable<decimal> SUM_A3_MONO { get; set; }
        public Nullable<decimal> SUM_A3_MONO_LAST { get; set; }
        public string INV_DATE { get; set; }
        public string INVO_NO { get; set; }
        public Nullable<decimal> INV_AMT { get; set; }
        public Nullable<decimal> INV_TAX { get; set; }
        public Nullable<decimal> CAPITAL { get; set; }
        public string ORI_APLY_NO { get; set; }
        public Nullable<decimal> ORI_PERIOD { get; set; }
        public string IS_TRANSFER { get; set; }
        public string IMPORT_DATE { get; set; }
        public string CONVERT_DATE { get; set; }
    }
}
