//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_WARRANTER
    {
        public string SCUR_ID { get; set; }
        public string CH_NAME { get; set; }
        public string ENG_NAME { get; set; }
        public string SEX { get; set; }
        public string BRTH_DATE { get; set; }
        public string CORP_NAME { get; set; }
        public string RGT_ADDR { get; set; }
        public string DEPT_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string APPO_DATE { get; set; }
        public string TEL { get; set; }
        public string FACSIMILE { get; set; }
        public string INC_STS { get; set; }
        public string CTAC_TEL { get; set; }
        public string MOBIL { get; set; }
        public string PSUR_CTAC_NAME { get; set; }
        public string PSUR_CTAC_TEL { get; set; }
        public string DOMI_ADDR { get; set; }
        public string ADDR { get; set; }
        public string GRAD { get; set; }
        public string MAIL_ACCT { get; set; }
        public string PICTURE { get; set; }
    }
}
