//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_FARE_APLY
    {
        public string FARE_APLY_NO { get; set; }
        public string APLY_DATE { get; set; }
        public string APLY_PERSON { get; set; }
        public string DEPT { get; set; }
        public string IF_TRAVEL { get; set; }
        public string NOTE { get; set; }
        public string FARE_CON { get; set; }
        public string IF_CLOSE { get; set; }
        public string ARP_DATE { get; set; }
        public string CIT_NO { get; set; }
        public string APRV { get; set; }
    }
}
