//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_AR_PAY_APLY_1
    {
        public string PAY_APLY_NO { get; set; }
        public string APLY_NO { get; set; }
        public string ARP_DATE { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_NO1 { get; set; }
        public Nullable<double> APLY_TR { get; set; }
        public Nullable<double> PERIOD { get; set; }
        public Nullable<double> PCT_AVD_PCT { get; set; }
        public Nullable<double> PAPER_AMT { get; set; }
        public Nullable<double> AR_AMT { get; set; }
        public Nullable<double> AR_INT_NO_TAX { get; set; }
        public Nullable<double> AR_INT_IN_TAX { get; set; }
        public Nullable<double> OTH_FEE { get; set; }
        public Nullable<double> AR_APRV_AMT { get; set; }
        public string BANK_CODE { get; set; }
        public string ACCOUNT { get; set; }
        public string CUR_STS { get; set; }
        public string CON_NO { get; set; }
        public Nullable<double> REAL_TR { get; set; }
        public string CHECK_ALL { get; set; }
        public Nullable<double> MAN_CHARGE_PERCENT { get; set; }
        public string CHK_FR { get; set; }
        public string CHK_TO { get; set; }
        public string EMP_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string PAY_TYPE { get; set; }
        public Nullable<double> NEW_TR { get; set; }
        public Nullable<decimal> Company_FEE { get; set; }
        public Nullable<decimal> OTH_ONE_FEE { get; set; }
        public string ONE_INV { get; set; }
        public string KEYIN_USER { get; set; }
        public string KEYIN_DATE { get; set; }
        public string KEYIN_TIME { get; set; }
        public string UPD_USER { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
