//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_DOC_STOCK
    {
        public string APLY_NO { get; set; }
        public string ATCH_CODE { get; set; }
        public string CON_NO { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> RIGHT_QTY { get; set; }
        public Nullable<decimal> COPY_QTY { get; set; }
        public Nullable<decimal> RIGHT_BR_QTY { get; set; }
        public Nullable<decimal> COPY_BR_QTY { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<decimal> RIGHT_APLY_QTY { get; set; }
        public Nullable<decimal> COPY_APLY_QTY { get; set; }
        public Nullable<decimal> RIGHT_CAN_QTY { get; set; }
        public Nullable<decimal> COPY_CAN_QTY { get; set; }
        public string IN_DATE { get; set; }
        public string IN_PERSON { get; set; }
    }
}
