//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_RCV_DETAIL
    {
        public string CUST_CODE { get; set; }
        public string APLY_NO { get; set; }
        public int W_TIMES { get; set; }
        public string RED_DATE { get; set; }
        public string RCV_TYPE { get; set; }
        public Nullable<decimal> THIS_RCV_AMT { get; set; }
        public string DUE_DATE { get; set; }
        public string CHK_NO { get; set; }
        public string IF_CASH { get; set; }
        public string REMARK { get; set; }
    }
}
