//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_LAND
    {
        public string SCUR_ID { get; set; }
        public string PAWN_LAND_NO { get; set; }
        public string DOC_NO { get; set; }
        public decimal TOT_AREA { get; set; }
        public string RIGHT_SCOPE { get; set; }
        public Nullable<decimal> LAND_AREA { get; set; }
        public Nullable<decimal> OWN_AREA { get; set; }
        public string OWN_PERCENT { get; set; }
        public Nullable<decimal> PRE_VAL { get; set; }
        public Nullable<decimal> GOV_VAL { get; set; }
        public string PRE_DATE { get; set; }
    }
}
