//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_AR_B_CTL_1
    {
        public string PAY_APLY_NO { get; set; }
        public int SEQ_NO { get; set; }
        public string ARP_DATE { get; set; }
        public string CUST_NAME { get; set; }
        public Nullable<double> AR_INT_NO_TAX { get; set; }
        public Nullable<double> AR_DAY { get; set; }
        public Nullable<double> SERV_CHAR { get; set; }
        public Nullable<double> TAX_AMT { get; set; }
        public Nullable<double> AR_APRV_AMT { get; set; }
        public Nullable<double> AR_AMT { get; set; }
        public Nullable<double> RETAIN_AMT { get; set; }
        public string DUE_DATE { get; set; }
        public Nullable<double> THIS_USE_QUTA { get; set; }
        public Nullable<double> UNUSE_QUTA { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> AR_INT_REAL { get; set; }
        public Nullable<decimal> AR_INT_REAL_INT { get; set; }
    }
}
