//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_LEND_SHEET
    {
        public string SHEET_NO { get; set; }
        public string CDATE { get; set; }
        public string DEPT { get; set; }
        public string LEND_MAN { get; set; }
        public string CUST_CODE { get; set; }
        public string APLY_NO { get; set; }
        public string ACT_CODE { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> LEND_APLY_AMT { get; set; }
        public string LEND_APRV_MAN { get; set; }
        public string APRV_DATE { get; set; }
        public Nullable<decimal> LEND_APRV_AMT { get; set; }
    }
}
