//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_PAPER_SUPPLY_INV_TEMP
    {
        public string FRC_CODE { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<int> period { get; set; }
        public string YEAR_MONTH { get; set; }
        public string INV_DATE { get; set; }
        public string PSTAR_DATE { get; set; }
        public string PEND_DATE { get; set; }
        public string SUPPLY_INVOICE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> SUPPLY_INV_AMT { get; set; }
        public Nullable<decimal> adjust { get; set; }
        public string REMARK { get; set; }
    }
}
