//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_BUILDING
    {
        public string SCUR_ID { get; set; }
        public string BUILD_NO { get; set; }
        public string DOC_NO { get; set; }
        public string REG_DATE { get; set; }
        public string BLD_ADDR { get; set; }
        public string BLD_LAND { get; set; }
        public string MAIN_USE { get; set; }
        public string MAIN_MATERIAL { get; set; }
        public string FLOOR { get; set; }
        public Nullable<decimal> TOT_AREA { get; set; }
        public string RIGHT_SCOPE { get; set; }
    }
}
