//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR2_SAVE_CASE_DTL
    {
        public string CUST_CODE { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<decimal> BUY_AMT { get; set; }
        public Nullable<decimal> CON_TOL { get; set; }
        public Nullable<decimal> MARGIN { get; set; }
        public Nullable<decimal> PAY_AMOUNT { get; set; }
        public Nullable<decimal> CON_SUR { get; set; }
        public Nullable<decimal> CAPT_SUR { get; set; }
        public Nullable<decimal> DIG_AMT { get; set; }
        public Nullable<int> DURN { get; set; }
        public string END_DATE { get; set; }
        public string START_DATE { get; set; }
        public string DELAY_DATE { get; set; }
        public string CON_NO { get; set; }
    }
}
