//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_PAPER_QUOTATION
    {
        public string APLY_NO { get; set; }
        public string CUST_NO { get; set; }
        public string CTAC { get; set; }
        public string CTAC_TEL { get; set; }
        public string FACSIMILE { get; set; }
        public string SUPL_CODE { get; set; }
        public string FRC_DEP_CODE { get; set; }
        public string SALES_NAME { get; set; }
        public string SALES_TEL { get; set; }
        public string REMARK { get; set; }
        public decimal COEFFICIENT { get; set; }
        public Nullable<decimal> ESTIMATE { get; set; }
        public decimal XEROX_INPUT { get; set; }
        public string INCREASE { get; set; }
        public decimal EXCEED_FEE_A4_MONO { get; set; }
        public decimal EXCEED_FEE_A3_MONO { get; set; }
        public decimal EXCEED_FEE_A4_COLOR { get; set; }
        public Nullable<decimal> EXCEED_FEE_A3_COLOR { get; set; }
        public decimal MISPRINT_RATE { get; set; }
        public string INC_TAX { get; set; }
        public string NEW_CUST { get; set; }
        public string PACKAGE { get; set; }
        public string CASHIER { get; set; }
        public string OTHER { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
