//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_CASE_APLY_POLICY
    {
        public string APLY_NO { get; set; }
        public string POLICY_SUBJECT { get; set; }
        public string ASUR_TYPE_CODE { get; set; }
        public string ASUR_S_DATE { get; set; }
        public Nullable<int> MOBJ_SN { get; set; }
        public string POLICY_NO { get; set; }
        public string ASUR_E_DATE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
