//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_CRITICAL_TRACKING
    {
        public decimal SeqNo { get; set; }
        public string EMP_NO { get; set; }
        public string ADD_DATE { get; set; }
        public string SUPL_CODE { get; set; }
        public string CUST_NO { get; set; }
        public string TRACK_STS { get; set; }
        public Nullable<decimal> FORECAST_APLY_AMT { get; set; }
        public string PROGRESS { get; set; }
        public string REMARK { get; set; }
        public string APLY_NO { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE1 { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
