//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_QUOTA_APLY_OBJ_ACCS
    {
        public string QUOTA_APLY_NO { get; set; }
        public string OBJ_CODE { get; set; }
        public decimal ACCS_SEQ { get; set; }
        public string ACCS_CODE { get; set; }
        public string ACCS_NAME { get; set; }
        public string ADD { get; set; }
        public string NEW_CON_NO { get; set; }
        public string NEW_OBJ_CODE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
