//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_QUOTA_APLY_APLY_COND
    {
        public string QUOTA_APLY_NO { get; set; }
        public Nullable<decimal> APLY_TOT_QUOTA { get; set; }
        public string APLY_APPR_TYPE { get; set; }
        public string APLY_FIRST_APPR_DATE { get; set; }
        public Nullable<decimal> APLY_QUOTA_MONTHS { get; set; }
        public Nullable<decimal> APLY_DURN_M { get; set; }
        public string APLY_PAY_PERD { get; set; }
        public string APLY_B_RECEIVE { get; set; }
        public string APLY_A_RECEIVE { get; set; }
        public Nullable<decimal> APLY_SURF_TR { get; set; }
        public Nullable<decimal> APLY_REAL_TR { get; set; }
        public Nullable<decimal> APLY_SERV_CHAR { get; set; }
        public Nullable<decimal> ISU_FACTOR { get; set; }
        public string APLY_OTH_APLY_COND { get; set; }
        public string APLY_FINA_PURP { get; set; }
        public string CASE_SOUR { get; set; }
        public string AUD_CASE_TYPE { get; set; }
        public string AGENT { get; set; }
        public string OTHER { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
