//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_PAPER_QUOTATION_VALUATION
    {
        public string APLY_NO { get; set; }
        public decimal PERIOD_S { get; set; }
        public Nullable<decimal> PERIOD_E { get; set; }
        public Nullable<decimal> BASE_RENT_FEE { get; set; }
        public Nullable<decimal> A4_MONO_MONTH_BASE_PAGE { get; set; }
        public Nullable<decimal> A4_MONO_PAGE_FEE { get; set; }
        public Nullable<decimal> A4_MONO_PAGE_FEE_FRC { get; set; }
        public Nullable<decimal> A4_COLOR_MONTH_BASE_PAGE { get; set; }
        public Nullable<decimal> A4_COLOR_PAGE_FEE { get; set; }
        public Nullable<decimal> A4_COLOR_PAGE_FEE_FRC { get; set; }
        public Nullable<decimal> A3_MONO_MONTH_BASE_PAGE { get; set; }
        public Nullable<decimal> A3_MONO_PAGE_FEE { get; set; }
        public Nullable<decimal> A3_MONO_PAGE_FEE_FRC { get; set; }
        public Nullable<decimal> A3_COLOR_MONTH_BASE_PAGE { get; set; }
        public Nullable<decimal> A3_COLOR_PAGE_FEE { get; set; }
        public Nullable<decimal> A3_COLOR_PAGE_FEE_FRC { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
