//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_VISIT_REC
    {
        public decimal SeqNo { get; set; }
        public string EMP_CODE { get; set; }
        public string SUPL_CODE { get; set; }
        public string CUST_CODE { get; set; }
        public string CTAC { get; set; }
        public string VISIT_DAT { get; set; }
        public string Mes_TStart { get; set; }
        public string Mes_TStop { get; set; }
        public Nullable<decimal> FORECAST_APLY_AMT { get; set; }
        public string INTERVIEW_TOPIC { get; set; }
        public string Rec_Meat { get; set; }
        public string TRANSPORTATION { get; set; }
        public Nullable<decimal> APLY_FEE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string Case_Sour { get; set; }
        public string REC_TITLE { get; set; }
        public string Rul_Place { get; set; }
        public string Rul_Other { get; set; }
        public Nullable<int> Atm_Num { get; set; }
    }
}
