//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_USER_FUNC
    {
        public string USER_ID { get; set; }
        public string FUNC_ID { get; set; }
        public Nullable<bool> AVAILABLE { get; set; }
        public Nullable<bool> CAN_ADD { get; set; }
        public Nullable<bool> CAN_UPDATE { get; set; }
        public Nullable<bool> CAN_DELETE { get; set; }
        public Nullable<bool> CAN_EXPORT { get; set; }
        public Nullable<bool> CAN_COPY { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
