//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_CASE_APLY_APLY_COND2
    {
        public string APLY_NO { get; set; }
        public string CON_TYPE { get; set; }
        public string TMP_CODE { get; set; }
        public string EXPIRED_RENEW { get; set; }
        public Nullable<decimal> HIRE { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> YAR { get; set; }
        public Nullable<decimal> MTH { get; set; }
        public Nullable<decimal> PERIOD { get; set; }
        public string PACKAGE { get; set; }
        public string CASHIER { get; set; }
        public string CHG_CON { get; set; }
        public string PRV_APLY_NO { get; set; }
        public string CHG_CODICIL { get; set; }
        public string LIMIT { get; set; }
        public Nullable<decimal> RESTRICTION_PERIODS { get; set; }
        public string FREE_SHOW_MAC_NO { get; set; }
        public string CODICIL { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
