//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_PAPER_AR_TMP
    {
        public string ORDER_NO { get; set; }
        public string INVO_REMK { get; set; }
        public string RECP_NO { get; set; }
        public Nullable<decimal> NET_AMT_NT { get; set; }
        public Nullable<decimal> CAN_AMT_NT { get; set; }
        public string ACEP_DATE { get; set; }
        public string CHEQ_NO { get; set; }
        public string DUE_DATE { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string UPD_DATE { get; set; }
        public string REMK { get; set; }
        public string INVO_NO { get; set; }
        public string BACK_DATE { get; set; }
    }
}
