//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_FRC_SALES
    {
        public string FRC_CODE { get; set; }
        public string FRC_DEP_CODE { get; set; }
        public decimal SEQ_NO { get; set; }
        public string FRC_SALES_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string EXT { get; set; }
        public string LINE { get; set; }
        public string FACSIMILE { get; set; }
        public string MOBILE { get; set; }
        public string CELL2 { get; set; }
        public string Email { get; set; }
        public string REMARK { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
