//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_FRC_VER
    {
        public string FRC_CODE { get; set; }
        public int VER { get; set; }
        public string FRC_STS { get; set; }
        public string Eff_Date { get; set; }
        public string EXP_DATE { get; set; }
        public string APRV_BY { get; set; }
        public Nullable<decimal> QUOTA_AMT { get; set; }
        public string APRV_BOOK_IMAGE { get; set; }
        public string SEND_EXAM_IMAGE { get; set; }
        public string DEBT_IMAGE { get; set; }
        public string BUY_WAY { get; set; }
        public string EXPIRE_PROMISE { get; set; }
        public string OTH_PROMISE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
