//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_MASTER_CONTRACT
    {
        public string MAST_CON_NO { get; set; }
        public string CUST_NO { get; set; }
        public string DEPT_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public string APLY_DATE { get; set; }
        public string CONTACT { get; set; }
        public string CTAC_TEL { get; set; }
        public string APRV_DATE { get; set; }
        public string PRE_EXPIRY_DATE { get; set; }
        public string EXPIRY_DATE { get; set; }
        public string CUR_STS { get; set; }
        public string CASE_TYPE_CODE { get; set; }
        public string SIGNED_NO { get; set; }
        public string FILE_SEQ { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
