//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_CON_BAL
    {
        public string APLY_NO { get; set; }
        public decimal L_THIS { get; set; }
        public decimal L_APLY { get; set; }
        public decimal L_PREV { get; set; }
        public decimal L_APRV_IPREV_QUOTA_CYCLE { get; set; }
        public decimal L_APRV_IPREV_QUOTA_NCYCLE { get; set; }
        public decimal L_APRV_PREV_QUOTA_CYCLE { get; set; }
        public decimal L_APRV_PREV_QUOTA_NCYCLE { get; set; }
        public decimal L_APRV_PREV_QUOTA_SURPLUS { get; set; }
        public decimal L_IPREV_QUOTA_CYCLE_USED { get; set; }
        public decimal L_IPREV_QUOTA_NCYCLE_USED { get; set; }
        public decimal L_PREV_QUOTA_CYCLE_USED { get; set; }
        public decimal L_PREV_QUOTA_NCYCLE_USED { get; set; }
        public decimal L_IPREV_CYCLE_SUR { get; set; }
        public decimal L_IPREV_NCYCLE_SUR { get; set; }
        public decimal L_PREV_CYCLE_SUR { get; set; }
        public decimal L_PREV_NCYCLE_SUR { get; set; }
        public decimal L_RISKS { get; set; }
        public decimal R_APLY { get; set; }
        public decimal R_PREV { get; set; }
        public decimal R_APRV_PREV_QUOTA_CYCLE { get; set; }
        public decimal R_APRV_PREV_QUOTA_NCYCLE { get; set; }
        public decimal R_APRV_PREV_QUOTA_SURPLUS { get; set; }
        public decimal R_PREV_QUOTA_CYCLE_USED { get; set; }
        public decimal R_PREV_QUOTA_NCYCLE_USED { get; set; }
        public decimal R_PREV_CYCLE_SUR { get; set; }
        public decimal R_PREV_NCYCLE_SUR { get; set; }
        public decimal R_RISKS { get; set; }
        public decimal OALT_AMT { get; set; }
        public Nullable<decimal> REAL_VAL { get; set; }
    }
}
