//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR3_QUOTA_APLY_OBJ
    {
        public string QUOTA_APLY_NO { get; set; }
        public string OBJ_CODE { get; set; }
        public string OBJ_LOC_ADDR { get; set; }
        public string PROD_NAME { get; set; }
        public string OTC { get; set; }
        public string SPEC { get; set; }
        public string BRAND { get; set; }
        public string MAC_NO { get; set; }
        public string YEAR { get; set; }
        public string CAR_NO { get; set; }
        public string OBJ_DUE_OWNER { get; set; }
        public Nullable<decimal> Market_price { get; set; }
        public string BUDG_LEASE { get; set; }
        public Nullable<decimal> BUDG_LEASE_AMT { get; set; }
        public Nullable<decimal> SELF_RATE { get; set; }
        public Nullable<decimal> INV_AMT_I_IB { get; set; }
        public Nullable<decimal> RV_AMT { get; set; }
        public string BUY_PROMISE { get; set; }
        public string OBJ_LOC_TEL { get; set; }
        public string OBJ_LOC_FAX { get; set; }
        public string OBJ_LOC_CTAC { get; set; }
        public string FRC_CODE { get; set; }
        public string SALES_UNIT { get; set; }
        public string OBJ_ASUR_TYPE { get; set; }
        public string OBJ_ONUS { get; set; }
        public string BUY_IF { get; set; }
        public string BUY_WAY { get; set; }
        public Nullable<decimal> BUY_RATE { get; set; }
        public Nullable<decimal> REAL_BUY_PRC { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
