//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ATCH_CODE
    {
        public OR_ATCH_CODE()
        {
            this.OR_LACK_DATA = new HashSet<OR_LACK_DATA>();
        }
    
        public string ATCH_CODE { get; set; }
        public string ATCH_NAME { get; set; }
        public string ATCH_DESC { get; set; }
        public Nullable<int> ATCH_DAYS { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public Nullable<decimal> ATCH_SEQ { get; set; }
        public string APRV_IMAGE { get; set; }
        public string RTN_STS { get; set; }
    
        public virtual ICollection<OR_LACK_DATA> OR_LACK_DATA { get; set; }
    }
}
