//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_ASUR_TYPE
    {
        public OR_ASUR_TYPE()
        {
            this.OR_ASUR = new HashSet<OR_ASUR>();
        }
    
        public string ASUR_TYPE_CODE { get; set; }
        public string ASUR_TYPE_NAME { get; set; }
        public string ASUR_STS { get; set; }
        public Nullable<double> ASUR_FACTOR { get; set; }
        public string ASUR_PAYER { get; set; }
    
        public virtual ICollection<OR_ASUR> OR_ASUR { get; set; }
    }
}
