//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_BOOK
    {
        public OR_BOOK()
        {
            this.OR_BOOK_DTL = new HashSet<OR_BOOK_DTL>();
        }
    
        public string CON_SEQ_NO { get; set; }
        public decimal BOOK_PURS_AMT { get; set; }
        public decimal BOOK_CON_TOL { get; set; }
        public decimal BOOK_MAQE_DIVD_TOL { get; set; }
        public decimal BOOK_T_R { get; set; }
        public decimal MAX_YLD_LINE { get; set; }
        public decimal CUR_SELL_PRC { get; set; }
    
        public virtual ICollection<OR_BOOK_DTL> OR_BOOK_DTL { get; set; }
    }
}
