//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_BANK_LOAN_CHG
    {
        public string BANK_NO { get; set; }
        public string DATE { get; set; }
        public decimal LAST_LOAN_SUR { get; set; }
        public decimal TOD_CREDIT { get; set; }
        public decimal TOD_LOAN_AMT { get; set; }
        public decimal TOD_RED_AMT { get; set; }
    }
}
