//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_BAD_DEBT_EMP
    {
        public string DATA_MONTH { get; set; }
        public string EMP_CODE { get; set; }
        public int COUNT_SUM { get; set; }
        public int COUNT_FST_NEW { get; set; }
        public int COUNT_FST_OLD { get; set; }
        public int COUNT_1 { get; set; }
        public int COUNT_2 { get; set; }
        public int COUNT_3 { get; set; }
        public int COUNT_4_6 { get; set; }
        public int COUNT_7_12 { get; set; }
        public int COUNT_1_YEAR { get; set; }
        public int COUNT_ACDNT { get; set; }
        public int COUNT_ACDNT_CON { get; set; }
        public decimal CON_TOL_SUM { get; set; }
        public decimal CON_RES_SUM { get; set; }
        public decimal AMT_FST_NEW { get; set; }
        public decimal AMT_FST_OLD { get; set; }
        public decimal AMT_1 { get; set; }
        public decimal AMT_2 { get; set; }
        public decimal AMT_3 { get; set; }
        public decimal AMT_4_6 { get; set; }
        public decimal AMT_7_12 { get; set; }
        public decimal AMT_1_YEAR { get; set; }
        public decimal AMT_ACDNT { get; set; }
        public decimal ACDNT_CON_RES { get; set; }
        public decimal PAY_AMT { get; set; }
        public int THIS_MTH_NEW { get; set; }
        public int FST_NO_PAY_DEL { get; set; }
        public int NO_PAY_DEL_1_3 { get; set; }
        public int NO_PAY_DEL_1_6 { get; set; }
    }
}
