//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_BANK_LOAN_DTL
    {
        public string BANK_NO { get; set; }
        public string LOAN_DATE { get; set; }
        public string BANK_ACCT_NO { get; set; }
        public string LOAN_MTHD_CODE { get; set; }
        public decimal LOAN_AMT { get; set; }
        public decimal RATE { get; set; }
        public string STAR_DATE { get; set; }
        public string END_DATE { get; set; }
        public string PAY_DIVD_DATE { get; set; }
        public Nullable<decimal> PAY_DIVD { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public decimal SeqNo { get; set; }
        public decimal LOAN_SEQ { get; set; }
        public string LOAN_TYPE { get; set; }
        public string Credit_way { get; set; }
        public string Currency { get; set; }
        public string IsRecourse { get; set; }
        public string Due_date { get; set; }
        public string Long_Short_LOAN { get; set; }
        public Nullable<decimal> Interest_Payment { get; set; }
        public string Interest_Cal { get; set; }
        public string Leap_year { get; set; }
        public Nullable<decimal> Feb_rate_Days { get; set; }
        public string Fixed_interest { get; set; }
        public string Remark { get; set; }
    }
}
