//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_BOOK_DTL
    {
        public string CON_SEQ_NO { get; set; }
        public decimal PERD_TYPE { get; set; }
        public string REFD_DATE { get; set; }
        public decimal THIS_RECV_CON_AMT { get; set; }
        public decimal THIS_RECV_BUS_TAX { get; set; }
        public decimal THIS_PAIED_CAPT { get; set; }
        public decimal THIS_REAL_DIVD_LINE { get; set; }
        public decimal SERV_CHAR { get; set; }
        public decimal CAPT_SUR { get; set; }
        public decimal MAQE_DIVD_SUR_SERV_ { get; set; }
        public decimal RECV_CON_AMT_SUR { get; set; }
    
        public virtual OR_BOOK OR_BOOK { get; set; }
    }
}
