//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_APLY_COND
    {
        public string APLY_NO { get; set; }
        public string CASE_TYPE_CODE { get; set; }
        public string AUD_LVL_CODE { get; set; }
        public Nullable<decimal> STL_LEASE { get; set; }
        public string CASE_SOUR { get; set; }
        public string AUD_CASE_TYPE { get; set; }
        public string AGENT { get; set; }
        public string OTHER { get; set; }
        public string OBJ_INV_FLOW { get; set; }
        public string OBJ_PAPER_DRAW { get; set; }
        public string OBJ_PAPER_ENDER { get; set; }
        public Nullable<decimal> APLY_BUY_AMT { get; set; }
        public Nullable<decimal> APLY_RAKE { get; set; }
        public Nullable<decimal> APLY_ANT_EXP { get; set; }
        public Nullable<decimal> APLY_SAVING_EXP { get; set; }
        public Nullable<decimal> APLY_BOND { get; set; }
        public Nullable<decimal> APLY_PURS_TAX { get; set; }
        public string APLY_PAY_PERD { get; set; }
        public Nullable<decimal> APLY_DURN_M { get; set; }
        public Nullable<decimal> APLY_PERD { get; set; }
        public string APLY_PAY_MTHD { get; set; }
        public Nullable<decimal> APLY_DEPS { get; set; }
        public Nullable<decimal> APLY_SERV_CHAR { get; set; }
        public Nullable<decimal> APLY_REST { get; set; }
        public Nullable<decimal> APLY_LEASE_PERD { get; set; }
        public Nullable<decimal> APLY_SURF_TR { get; set; }
        public Nullable<decimal> APLY_REAL_TR { get; set; }
        public Nullable<decimal> APLY_LF1_FR { get; set; }
        public Nullable<decimal> APLY_LF1_TO { get; set; }
        public Nullable<decimal> APLY_LF1_HIRE { get; set; }
        public Nullable<decimal> APLY_LF2_FR { get; set; }
        public Nullable<decimal> APLY_LF2_TO { get; set; }
        public Nullable<decimal> APLY_LF2_HIRE { get; set; }
        public Nullable<decimal> APLY_LF3_FR { get; set; }
        public Nullable<decimal> APLY_LF3_TO { get; set; }
        public Nullable<decimal> APLY_LF3_HIRE { get; set; }
        public Nullable<decimal> APLY_LF4_FR { get; set; }
        public Nullable<decimal> APLY_LF4_TO { get; set; }
        public Nullable<decimal> APLY_LF4_HIRE { get; set; }
        public Nullable<decimal> APLY_LF5_FR { get; set; }
        public Nullable<decimal> APLY_LF5_TO { get; set; }
        public Nullable<decimal> APLY_LF5_HIRE { get; set; }
        public Nullable<decimal> APLY_INCM_TOL { get; set; }
        public Nullable<decimal> APLY_SELL_TAX { get; set; }
        public Nullable<decimal> APLY_MARG { get; set; }
        public string COND_TRADE { get; set; }
        public string MOV_ASUR_IMP { get; set; }
        public string AUTH_LIEN_TARG { get; set; }
        public string BUY_PROM_TARG { get; set; }
        public string OTH_BUY_TARG { get; set; }
        public Nullable<decimal> COND_TRADE_AMT { get; set; }
        public Nullable<decimal> MOV_ASUR_AMT { get; set; }
        public Nullable<decimal> AUTH_LIEN_AMT { get; set; }
        public Nullable<decimal> BUY_PROM_AMT { get; set; }
        public Nullable<decimal> OTH_AMT { get; set; }
        public Nullable<double> ISU_FACTOR { get; set; }
        public Nullable<decimal> ISU_AMT { get; set; }
        public string APLY_AMOR_MTHD { get; set; }
        public Nullable<decimal> APLY_HIRE { get; set; }
        public Nullable<decimal> APLY_TAX { get; set; }
        public Nullable<decimal> APLY_OTH_INT { get; set; }
        public string APLY_TAX_ZERO { get; set; }
        public Nullable<decimal> NON_FEAT_CHARGE { get; set; }
        public string KEYIN_USER { get; set; }
        public string KEYIN_DATE { get; set; }
        public string KEYIN_TIME { get; set; }
        public string UPD_USER { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string CASE_PROP { get; set; }
        public string CAR_OWNER_ID { get; set; }
        public string CAR_OWNER { get; set; }
        public string Manager_ID { get; set; }
        public string Manager { get; set; }
        public string AllotDesc { get; set; }
    }
}
