//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_ARP
    {
        public string APLY_NO { get; set; }
        public short SN { get; set; }
        public string UNIF_NO { get; set; }
        public string Name { get; set; }
        public string Arp_Cond { get; set; }
        public string Fee_Prop { get; set; }
        public string Bank_No { get; set; }
        public string Acc_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Arp_Mthd { get; set; }
        public string Memo { get; set; }
        public string Date { get; set; }
        public string Arp_Date { get; set; }
        public string Arp_Emp { get; set; }
        public string AP_NO { get; set; }
        public string LAST_UPD_USER { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
