//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_SCUR
    {
        public string APLY_NO { get; set; }
        public decimal ORD_NO { get; set; }
        public string SCUR_NATUR { get; set; }
        public string SCUR_NAME { get; set; }
        public string SCUR_ID { get; set; }
        public string SCUR_RELATION { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string Resident_Addr { get; set; }
        public string Mailing_Addr { get; set; }
        public string TEL_Home { get; set; }
        public string TEL_Office { get; set; }
        public string Mobile { get; set; }
    }
}
