//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_RLTY_IMP
    {
        public string APLY_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string RealtyWay { get; set; }
        public string RLTY_DESC { get; set; }
        public string BUILDING_NO { get; set; }
        public string Land_Owner { get; set; }
        public string Building_Owner { get; set; }
        public Nullable<double> LAND_AREA { get; set; }
        public Nullable<double> BUILDING_AREA { get; set; }
        public Nullable<decimal> DECD_PRC { get; set; }
        public Nullable<decimal> COLL_SUR { get; set; }
        public string CASE_FLAG { get; set; }
        public string PRCICE_BASE { get; set; }
        public Nullable<decimal> OTC_ORDERX { get; set; }
        public Nullable<decimal> OTC_AMTX { get; set; }
        public string ORDER1 { get; set; }
        public Nullable<decimal> ORDER1_AMT { get; set; }
        public string ORDER2 { get; set; }
        public Nullable<decimal> ORDER2_AMT { get; set; }
        public string ORDER3 { get; set; }
        public Nullable<decimal> ORDER3_AMT { get; set; }
        public Nullable<decimal> SET_AMT { get; set; }
        public Nullable<decimal> ORDER { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string LAND_RIGHT_SCOPE { get; set; }
        public string LAND_Use_Zoning { get; set; }
        public string BUILDING_RIGHT_SCOPE { get; set; }
        public string BUILDING_MAIN_USE { get; set; }
        public string BUILDING_MAIN_Material { get; set; }
        public Nullable<short> BUILDING_TOT_FLOOR { get; set; }
        public string BUILDING_COMPLETE_DATE { get; set; }
        public string ASUR_TYPE_CODE { get; set; }
        public Nullable<decimal> ASUR_AMOUNT { get; set; }
        public string ASUR_PAYER { get; set; }
    }
}
