//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CONTRACT
    {
        public OR_CONTRACT()
        {
            this.OR_ARP_MTHD = new HashSet<OR_ARP_MTHD>();
            this.OR_ASUR = new HashSet<OR_ASUR>();
            this.OR_CON_CHG = new HashSet<OR_CON_CHG>();
            this.OR_INV_DATA = new HashSet<OR_INV_DATA>();
            this.OR_MOV_IMP_DATA = new HashSet<OR_MOV_IMP_DATA>();
            this.OR_OTH_IMP = new HashSet<OR_OTH_IMP>();
            this.OR_PAPER_IMP_DATA = new HashSet<OR_PAPER_IMP_DATA>();
            this.OR_RLTY_IMP_DATA = new HashSet<OR_RLTY_IMP_DATA>();
            this.OR_SALES_MIFY = new HashSet<OR_SALES_MIFY>();
            this.OR_SHIP_IMP_DATA = new HashSet<OR_SHIP_IMP_DATA>();
        }
    
        public string CON_NO { get; set; }
        public string APLY_NO { get; set; }
        public string ARP_TYPE { get; set; }
        public string CON_DATE_FR { get; set; }
        public string CON_DATE_TO { get; set; }
        public string TYPE { get; set; }
        public string PAPER_PROC_STS { get; set; }
        public string PRJ_PAY_DATE { get; set; }
        public decimal THIS_MTH_RATE { get; set; }
        public string TAX_CODE { get; set; }
        public string DESC { get; set; }
        public string con_arrv_date { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    
        public virtual ICollection<OR_ARP_MTHD> OR_ARP_MTHD { get; set; }
        public virtual ICollection<OR_ASUR> OR_ASUR { get; set; }
        public virtual ICollection<OR_CON_CHG> OR_CON_CHG { get; set; }
        public virtual ICollection<OR_INV_DATA> OR_INV_DATA { get; set; }
        public virtual ICollection<OR_MOV_IMP_DATA> OR_MOV_IMP_DATA { get; set; }
        public virtual ICollection<OR_OTH_IMP> OR_OTH_IMP { get; set; }
        public virtual ICollection<OR_PAPER_IMP_DATA> OR_PAPER_IMP_DATA { get; set; }
        public virtual ICollection<OR_RLTY_IMP_DATA> OR_RLTY_IMP_DATA { get; set; }
        public virtual ICollection<OR_SALES_MIFY> OR_SALES_MIFY { get; set; }
        public virtual ICollection<OR_SHIP_IMP_DATA> OR_SHIP_IMP_DATA { get; set; }
    }
}
