//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_REF
    {
        public string APLY_NO { get; set; }
        public string AP_SUP { get; set; }
        public string NEW_CORP { get; set; }
        public string CHK_RCD_S { get; set; }
        public string CHK_RCD_C { get; set; }
        public string CHK_RCD_G { get; set; }
        public string STOCK_CORP { get; set; }
        public string CRD_SAME { get; set; }
        public string CRD_RAL { get; set; }
        public string CRD_UNINV { get; set; }
        public string CRD { get; set; }
        public string OTH { get; set; }
        public string GEN_TR { get; set; }
        public string GEN_NEW { get; set; }
        public string GEN_CHECK { get; set; }
        public string GEN_CON { get; set; }
        public string VP_SUP { get; set; }
        public string VP_TR { get; set; }
        public string VP_RANGE { get; set; }
        public string VP_NEW { get; set; }
        public string VP_CHECK { get; set; }
        public string VP_STOCK { get; set; }
        public string VP_SUP_NO1 { get; set; }
        public string VP_SUP_NOT { get; set; }
        public string VP_CON { get; set; }
        public string LAST_AUT { get; set; }
        public string VP_MANAGER { get; set; }
        public string OTH_TR { get; set; }
        public string OTH_CON { get; set; }
        public string OTH_DEF { get; set; }
        public string GEN_DEF { get; set; }
        public string VP_DEF { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
