//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_EXE_AMOR_DTL
    {
        public string APLY_NO { get; set; }
        public decimal PERIOD { get; set; }
        public string CON_CODE { get; set; }
        public Nullable<decimal> HIRE { get; set; }
        public Nullable<decimal> DIVD { get; set; }
        public Nullable<decimal> CAPT_AMOR { get; set; }
        public string PAPER_NBR { get; set; }
        public string DUE_DAT { get; set; }
        public string IF_CASH { get; set; }
        public Nullable<decimal> SURF_HIRE { get; set; }
        public Nullable<decimal> SURF_DIVD { get; set; }
        public Nullable<decimal> SURF_CAPT_AMOR { get; set; }
        public Nullable<decimal> EX_HIRE { get; set; }
        public Nullable<decimal> EX_DIVD { get; set; }
        public Nullable<decimal> EX_CAPT_AMOR { get; set; }
    }
}
