//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CUSTOM
    {
        public OR_CUSTOM()
        {
            this.OR_CUST_DATA_CHG_REC = new HashSet<OR_CUST_DATA_CHG_REC>();
            this.OR_IMPS_CUST = new HashSet<OR_IMPS_CUST>();
            this.OR_PRESS_REC = new HashSet<OR_PRESS_REC>();
            this.OR_QUOT = new HashSet<OR_QUOT>();
            this.OR_SALES_MIFY = new HashSet<OR_SALES_MIFY>();
            this.OR_SRV_REC = new HashSet<OR_SRV_REC>();
        }
    
        public string CUST_NO { get; set; }
        public string CUST_BLOC_CODE { get; set; }
        public string CUST_TYPE_CODE { get; set; }
        public string CUST_UNION { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_SNAME { get; set; }
        public string EN_NAME { get; set; }
        public string EN_SNAME { get; set; }
        public string CONTACT { get; set; }
        public string CTAC_TITLE { get; set; }
        public string CTAC_EXT { get; set; }
        public string UNIF_NO { get; set; }
        public string TAKER_ID { get; set; }
        public string TAKER { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public Nullable<decimal> EMP_PSNS { get; set; }
        public string SALES_RGT_ADDR { get; set; }
        public string FACSIMILE { get; set; }
        public Nullable<decimal> RGT_CAPT_AMT { get; set; }
        public string CTAC_ADDR { get; set; }
        public string FLOT_DATE { get; set; }
        public Nullable<decimal> REAL_CAPT_AMT { get; set; }
        public string CAPT_STR { get; set; }
        public string BUILD_DATE { get; set; }
        public string ORG_TYPE { get; set; }
        public Nullable<decimal> SALE_NET_AMT_YEAR1 { get; set; }
        public Nullable<decimal> SALE_NET_AMT1 { get; set; }
        public Nullable<decimal> SALE_NET_AMT_YEAR2 { get; set; }
        public Nullable<decimal> SALE_NET_AMT2 { get; set; }
        public string PAY_TYPE { get; set; }
        public string MAIN_BUS_ITEM { get; set; }
        public string DO_STS { get; set; }
        public string CUST_EMAIL_ADDR { get; set; }
        public Nullable<decimal> CREDIT_CUST { get; set; }
        public string JUDGE_LVL { get; set; }
        public string BUILD_STS { get; set; }
        public string CORP_CHAR { get; set; }
        public string TRAN_BANK1_NAME { get; set; }
        public string TRAN_BANK1_FUND { get; set; }
        public string TRAN_BANK1_ACCT { get; set; }
        public string TRAN_BANK2_NAME { get; set; }
        public string TRAN_BANK2_FUND { get; set; }
        public string TRAN_BANK2_ACCT { get; set; }
        public Nullable<decimal> TRAN_MAX_SUR { get; set; }
        public string TRAN_MAX_SUR_DATE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string INVOICE { get; set; }
        public Nullable<decimal> GEN_CURR_QUOTA { get; set; }
        public Nullable<decimal> VP_CURR_QUOTA { get; set; }
        public Nullable<decimal> AR_CURR_QUOTA { get; set; }
        public string GEN_SHARE { get; set; }
        public string VP_SHARE { get; set; }
        public string AR_SHARE { get; set; }
        public string BACKGROUND { get; set; }
        public string NATIONALITY { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string NEW_CUST_TYPE_CODE { get; set; }
        public string MAIN_COMP { get; set; }
        public string Honest_Agreement { get; set; }
        public string Secret_Promise { get; set; }
        public string CONTACT2 { get; set; }
        public string CTAC_TITLE2 { get; set; }
        public string CTAC_EXT2 { get; set; }
        public string Spec_cond { get; set; }
        public string Is_Transaction { get; set; }
        public string Parent_Comp_Name { get; set; }
        public string Parent_Comp_Stock_Code { get; set; }
        public string Industry_Type { get; set; }
        public string Cust_STS { get; set; }
        public string Is_Cond_Auth { get; set; }
        public string Is_Biz_Cust { get; set; }
        public string StockCode { get; set; }
        public string B_Triplicate { get; set; }
        public string Zip_Code { get; set; }
        public string RGT_ZIP_CODE { get; set; }
        public string CUST_ID_NO { get; set; }
        public string INDUSTRY_NO { get; set; }
        public string Is_Car_License { get; set; }
        public string Manager { get; set; }
        public string Manager_ID { get; set; }
    
        public virtual ICollection<OR_CUST_DATA_CHG_REC> OR_CUST_DATA_CHG_REC { get; set; }
        public virtual ICollection<OR_IMPS_CUST> OR_IMPS_CUST { get; set; }
        public virtual ICollection<OR_PRESS_REC> OR_PRESS_REC { get; set; }
        public virtual ICollection<OR_QUOT> OR_QUOT { get; set; }
        public virtual ICollection<OR_SALES_MIFY> OR_SALES_MIFY { get; set; }
        public virtual ICollection<OR_SRV_REC> OR_SRV_REC { get; set; }
    }
}
