//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_EXE_COND
    {
        public string APLY_NO { get; set; }
        public Nullable<decimal> APRV_BUY_AMT { get; set; }
        public Nullable<decimal> APRV_RAKE { get; set; }
        public Nullable<decimal> APRV_ANT_EXP { get; set; }
        public Nullable<decimal> APRV_SAVING_EXP { get; set; }
        public Nullable<decimal> APRV_BOND { get; set; }
        public Nullable<decimal> APRV_SUR { get; set; }
        public Nullable<decimal> APRV_PURS_TAX { get; set; }
        public string APRV_PAY_DURN { get; set; }
        public Nullable<decimal> APRV_DURN_M { get; set; }
        public Nullable<decimal> APRV_PERD { get; set; }
        public string APRV_PAY_MTHD { get; set; }
        public Nullable<decimal> APRV_DEPS { get; set; }
        public Nullable<decimal> APRV_SERV_CHAR { get; set; }
        public Nullable<decimal> APRV_SURF_TR { get; set; }
        public Nullable<decimal> APRV_REAL_TR { get; set; }
        public Nullable<decimal> APRV_LF1_FR { get; set; }
        public Nullable<decimal> APRV_LF1_TO { get; set; }
        public Nullable<decimal> APRV_LF1_HIRE { get; set; }
        public Nullable<decimal> APRV_LF2_FR { get; set; }
        public Nullable<decimal> APRV_LF2_TO { get; set; }
        public Nullable<decimal> APRV_LF2_HIRE { get; set; }
        public Nullable<decimal> APRV_LF3_FR { get; set; }
        public Nullable<decimal> APRV_LF3_TO { get; set; }
        public Nullable<decimal> APRV_LF3_HIRE { get; set; }
        public Nullable<decimal> APRV_LF4_FR { get; set; }
        public Nullable<decimal> APRV_LF4_TO { get; set; }
        public Nullable<decimal> APRV_LF4_HIRE { get; set; }
        public Nullable<decimal> APRV_LF5_FR { get; set; }
        public Nullable<decimal> APRV_LF5_TO { get; set; }
        public Nullable<decimal> APRV_LF5_HIRE { get; set; }
        public Nullable<decimal> APRV_INCM_TOL { get; set; }
        public Nullable<decimal> APRV_SELL_TAX { get; set; }
        public Nullable<decimal> APRV_MARG { get; set; }
        public Nullable<double> A_ISU_FACTOR { get; set; }
        public Nullable<decimal> A_ISU_AMT { get; set; }
        public string APRV_AMOR_MTHD { get; set; }
        public Nullable<decimal> APRV_HIRE { get; set; }
        public Nullable<decimal> APRV_TAX { get; set; }
        public string APRV_TAX_ZERO { get; set; }
        public Nullable<decimal> APRV_OTH_INT { get; set; }
        public Nullable<decimal> NON_FEAT_CHARGE { get; set; }
        public string KEYIN_USER { get; set; }
        public string KEYIN_DATE { get; set; }
        public string KEYIN_TIME { get; set; }
        public string UPD_USER { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
