//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_APLY_SHARE_DET
    {
        public string APLY_NO { get; set; }
        public decimal PERIOD { get; set; }
        public decimal HIRE { get; set; }
        public decimal DIVD { get; set; }
        public decimal CAPT_AMOR { get; set; }
        public Nullable<decimal> REAL_HIRE { get; set; }
        public Nullable<decimal> REAL_DIVD { get; set; }
        public Nullable<decimal> REAL_CAPT_AMOR { get; set; }
        public decimal EX_HIRE { get; set; }
        public decimal EX_DIVD { get; set; }
        public decimal EX_CAPT_AMOR { get; set; }
    }
}
