//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CON_VAL_BAL
    {
        public string APLY_NO { get; set; }
        public string CON_NO { get; set; }
        public string BLOC_NO { get; set; }
        public string CUST_NO { get; set; }
        public string UNIF_NO { get; set; }
        public Nullable<int> CURR_PERIOD { get; set; }
        public Nullable<int> TOT_PERIOD { get; set; }
        public Nullable<decimal> NONAL_VAL { get; set; }
        public Nullable<decimal> AR_VAL { get; set; }
        public Nullable<decimal> REAL_VAL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> BAN_GIN_RES { get; set; }
        public Nullable<decimal> INTEREST_RES { get; set; }
        public Nullable<decimal> PAY_AMT { get; set; }
        public Nullable<decimal> TM_PAY_AMT { get; set; }
        public Nullable<decimal> BLOC_VAL { get; set; }
    }
}
