//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CASE_INV_MERGE
    {
        public string MERGE_NO { get; set; }
        public string DealUser { get; set; }
        public string CUST_NO { get; set; }
        public string CaseType { get; set; }
        public string IncludeTAX { get; set; }
        public string RECVER { get; set; }
        public string RecverDEP { get; set; }
        public string Pos_Num { get; set; }
        public string RecverAddr { get; set; }
        public string INVOICE_TYPE { get; set; }
        public string FEE_TYPE { get; set; }
        public string FEE_TYPE_OTHER { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
