//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_CON_BAL
    {
        public string APLY_NO { get; set; }
        public Nullable<decimal> L_THIS { get; set; }
        public Nullable<decimal> L_BAL { get; set; }
        public Nullable<decimal> L_UCK_APRV { get; set; }
        public Nullable<decimal> L_UCK_USE { get; set; }
        public Nullable<decimal> L_UCK_BAL { get; set; }
        public Nullable<decimal> L_UCK_CUR_BAL { get; set; }
        public Nullable<decimal> L_CK_APRV { get; set; }
        public Nullable<decimal> L_CK_BAL { get; set; }
        public Nullable<decimal> L_CK_CUR_BAL { get; set; }
        public Nullable<decimal> L_UNUSE_APRV { get; set; }
        public Nullable<decimal> L_UNUSE_APPLY { get; set; }
        public Nullable<decimal> L_SUBTOT { get; set; }
        public Nullable<decimal> R_BAL { get; set; }
        public Nullable<decimal> R_UCK_APRV { get; set; }
        public Nullable<decimal> R_UCK_USE { get; set; }
        public Nullable<decimal> R_UCK_BAL { get; set; }
        public Nullable<decimal> R_UCK_CUR_BAL { get; set; }
        public Nullable<decimal> R_CK_APRV { get; set; }
        public Nullable<decimal> R_CK_BAL { get; set; }
        public Nullable<decimal> R_CK_CUR_BAL { get; set; }
        public Nullable<decimal> R_UNUSE_APRV { get; set; }
        public Nullable<decimal> R_UNUSE_APPLY { get; set; }
        public Nullable<decimal> R_SUBTOT { get; set; }
        public Nullable<decimal> ALL_TOT { get; set; }
        public Nullable<decimal> OALT_AMT { get; set; }
    }
}
