//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_DISH_PROC
    {
        public string C_CORP_NO { get; set; }
        public string CHEQ_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string NOTY_DATE { get; set; }
        public Nullable<decimal> DISH_AMT { get; set; }
        public string COLL_SUR_AMT { get; set; }
        public string DELAY_STS { get; set; }
        public string DISH_DESC { get; set; }
        public string SOL_MTHD { get; set; }
        public string EXE_PRJ_SOL_MTHD { get; set; }
        public string RATIF { get; set; }
    
        public virtual OR_DEPT OR_DEPT { get; set; }
        public virtual OR_DISH_NOTY OR_DISH_NOTY { get; set; }
    }
}
