//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_FRC
    {
        public OR_FRC()
        {
            this.OR_IMPS_APLY_BASE = new HashSet<OR_IMPS_APLY_BASE>();
            this.OR_IMPS_APLY_CONDIT = new HashSet<OR_IMPS_APLY_CONDIT>();
            this.OR_IMPS_CUST = new HashSet<OR_IMPS_CUST>();
        }
    
        public string FRC_CODE { get; set; }
        public string BLOC_NO { get; set; }
        public string CUST_FRC_TYPE_CODE { get; set; }
        public string FRC_NAME { get; set; }
        public string FRC_SNAME { get; set; }
        public string EN_NAME { get; set; }
        public string EN_SNAME { get; set; }
        public Nullable<decimal> DUE_BUY_RATE { get; set; }
        public Nullable<decimal> CREDIT_CUST { get; set; }
        public string BUY_PAY_MTHD { get; set; }
        public string CONTACT { get; set; }
        public string UNIF_NO { get; set; }
        public string TAKER { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public Nullable<decimal> EMP_PSNS { get; set; }
        public string SALES_RGT_ADDR { get; set; }
        public string FACSIMILE { get; set; }
        public Nullable<decimal> RGT_CAPT_AMT { get; set; }
        public string CTAC_ADDR { get; set; }
        public string FLOT_DATE { get; set; }
        public Nullable<decimal> REAL_CAPT_AMT { get; set; }
        public string CAPT_STR { get; set; }
        public string BUILD_DATE { get; set; }
        public string ORG_TYPE { get; set; }
        public string CUST_EMAIL_ADDR { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string AP_SUP { get; set; }
        public string Hand_OPINION { get; set; }
        public string Turnover_YM_S { get; set; }
        public string Turnover_YM_E { get; set; }
        public string Coor_Subject { get; set; }
        public string CORP_CODE { get; set; }
        public string SOUR_CODE { get; set; }
        public string SUB_CATE_CODE { get; set; }
        public string BUY_WAY { get; set; }
        public string Main_Prod_Desc { get; set; }
        public string FRC_Background { get; set; }
        public string BANK_CODE { get; set; }
        public string BANK_ACCT { get; set; }
        public Nullable<decimal> Turnover { get; set; }
        public string EMP_CODE { get; set; }
    
        public virtual ICollection<OR_IMPS_APLY_BASE> OR_IMPS_APLY_BASE { get; set; }
        public virtual ICollection<OR_IMPS_APLY_CONDIT> OR_IMPS_APLY_CONDIT { get; set; }
        public virtual ICollection<OR_IMPS_CUST> OR_IMPS_CUST { get; set; }
    }
}
