//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_IMPS_APLY_BASE
    {
        public OR_IMPS_APLY_BASE()
        {
            this.OR_IMPS_APLY_CONDIT = new HashSet<OR_IMPS_APLY_CONDIT>();
            this.OR_IMPS_APLY_IMPS_AUD = new HashSet<OR_IMPS_APLY_IMPS_AUD>();
            this.OR_IMPS_APLY_SCUR = new HashSet<OR_IMPS_APLY_SCUR>();
            this.OR_IMPS_APLY_SELL_AUD = new HashSet<OR_IMPS_APLY_SELL_AUD>();
        }
    
        public string APLY_NO { get; set; }
        public string FRC_CODE { get; set; }
        public string CURR_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public string AUD_LVL_CODE { get; set; }
        public string CON_SEQ_NO { get; set; }
        public string APLY_DATE { get; set; }
        public string TRACE { get; set; }
        public string TRACE_COND { get; set; }
        public string TRACE_OTH { get; set; }
        public string CASE_SOUR { get; set; }
        public string AGENT { get; set; }
        public decimal OLD_TRANS_TIMES { get; set; }
        public string SELL_SUPL_LOC { get; set; }
        public string IMPS_POST { get; set; }
        public string SIGN_DATE { get; set; }
        public string CON_STAR_DATE { get; set; }
        public string CUT_TIMES { get; set; }
        public string CON_EXPIR_DATE { get; set; }
        public decimal CUTOFF1 { get; set; }
        public decimal CUTOFF2 { get; set; }
        public decimal APLY_AMT { get; set; }
        public string FANC_CONS_EXP_BANK { get; set; }
        public decimal FANC_CONS_EXP_PLUS { get; set; }
        public decimal APRV_AMT { get; set; }
        public decimal IMPS_NBR { get; set; }
        public decimal EVERY_ACCT_EXP { get; set; }
        public decimal TRAN_REC_APLY { get; set; }
        public decimal TRAN_REC_ACCT { get; set; }
        public decimal TRAN_REC_REN { get; set; }
        public decimal TRAN_REC_VP { get; set; }
        public decimal TRAN_REC_CAR { get; set; }
        public decimal TRAN_REC_REL { get; set; }
        public decimal TRAN_MAX_SUR { get; set; }
        public string TRAN_MAX_SUR_DATE { get; set; }
        public string CUR_STS { get; set; }
        public string APRV_DATE { get; set; }
    
        public virtual OR_AUD_LVL_NAME OR_AUD_LVL_NAME { get; set; }
        public virtual OR_FRC OR_FRC { get; set; }
        public virtual ICollection<OR_IMPS_APLY_CONDIT> OR_IMPS_APLY_CONDIT { get; set; }
        public virtual ICollection<OR_IMPS_APLY_IMPS_AUD> OR_IMPS_APLY_IMPS_AUD { get; set; }
        public virtual OR_IMPS_APLY_RLTY_IMP OR_IMPS_APLY_RLTY_IMP { get; set; }
        public virtual ICollection<OR_IMPS_APLY_SCUR> OR_IMPS_APLY_SCUR { get; set; }
        public virtual ICollection<OR_IMPS_APLY_SELL_AUD> OR_IMPS_APLY_SELL_AUD { get; set; }
        public virtual OR_IMPS_APLY_SET_AMT OR_IMPS_APLY_SET_AMT { get; set; }
    }
}
