//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_IMPS_APLY_SET_AMT
    {
        public string APLY_NO { get; set; }
        public string COND_TRADE { get; set; }
        public string MOV_ASUR_IMP { get; set; }
        public string AUTH_LIEN_TARG { get; set; }
        public string BUY_PROM_TARG { get; set; }
        public string OTH_BUY_TARG { get; set; }
        public decimal COND_TRADE_AMT { get; set; }
        public decimal MOV_ASUR_AMT { get; set; }
        public decimal AUTH_LIEN_AMT { get; set; }
        public decimal BUY_PROM_AMT { get; set; }
        public decimal OTH_AMT { get; set; }
    
        public virtual OR_IMPS_APLY_BASE OR_IMPS_APLY_BASE { get; set; }
    }
}
