//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_INV_APART_DTL
    {
        public string APLY_NO { get; set; }
        public short ORD_NO { get; set; }
        public short ctpaytrm { get; set; }
        public Nullable<decimal> CAPITAL { get; set; }
        public Nullable<decimal> CAPITALAMT { get; set; }
        public Nullable<decimal> INTEREST { get; set; }
        public Nullable<decimal> INTERESTAMT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> PaperFee { get; set; }
        public Nullable<decimal> PaperTax { get; set; }
        public string CustNo { get; set; }
    }
}
