//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_IMPS_APLY_RLTY_IMP
    {
        public string APLY_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string RLTY_DESC { get; set; }
        public string CASE_FLAG { get; set; }
        public decimal DECD_PRC { get; set; }
        public string ORDER1 { get; set; }
        public decimal ORDER1_AMT { get; set; }
        public string ORDER2 { get; set; }
        public decimal ORDER2_AMT { get; set; }
        public string ORDER3 { get; set; }
        public decimal ORDER3_AMT { get; set; }
        public decimal COLL_SUR { get; set; }
        public decimal SET_AMT { get; set; }
        public decimal ORDER { get; set; }
    
        public virtual OR_IMPS_APLY_BASE OR_IMPS_APLY_BASE { get; set; }
    }
}
