//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_LACK_PROC
    {
        public string ATCH_CODE { get; set; }
        public string APLY_NO { get; set; }
        public string CON_NO { get; set; }
        public string ADD_CMP_DATE { get; set; }
        public string CUR_PROC_MTHD { get; set; }
        public string PROC_STS { get; set; }
        public string REMARK { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public Nullable<decimal> Deadline_Days { get; set; }
        public string DEAL_DEADLINE0 { get; set; }
        public string DEAL_DEADLINE { get; set; }
        public string DEAL_DEADLINE2 { get; set; }
        public string ARREST_TO_DATE { get; set; }
    }
}
