//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_MOBJECT
    {
        public string APLY_NO { get; set; }
        public int MOBJ_SN { get; set; }
        public string PROD_NAME { get; set; }
        public string SPEC { get; set; }
        public string BRAND { get; set; }
        public string MAC_NO { get; set; }
        public string CAR_NO { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> RV_AMT { get; set; }
        public string ASUR_TYPE_CODE { get; set; }
        public Nullable<decimal> ASUR_AMOUNT { get; set; }
        public string ASUR_PAYER { get; set; }
        public string CASE_FLAG { get; set; }
        public string Memos { get; set; }
        public string End_Date { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
