//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_OBJECT
    {
        public OR_OBJECT()
        {
            this.OR_ASUR = new HashSet<OR_ASUR>();
            this.OR_OBJ_SUM_DEPR = new HashSet<OR_OBJ_SUM_DEPR>();
        }
    
        public string OBJ_CODE { get; set; }
        public string FRC_CODE { get; set; }
        public string CORP_CODE { get; set; }
        public string SOUR_CODE { get; set; }
        public string SUB_CATE_CODE { get; set; }
        public string PROD_NAME { get; set; }
        public string BRAND { get; set; }
        public string SPEC { get; set; }
        public string MAC_NO { get; set; }
        public string CAR_NO { get; set; }
        public string YEAR { get; set; }
        public string ACCSORY { get; set; }
        public Nullable<decimal> REAL_BUY_PRC { get; set; }
        public string BUDG_LEASE { get; set; }
        public Nullable<decimal> BUDG_LEASE_AMT { get; set; }
        public string INV_I_IB { get; set; }
        public Nullable<decimal> INV_AMT_I_IB { get; set; }
        public Nullable<decimal> RV_AMT { get; set; }
        public Nullable<decimal> RV_AMT_MINUS { get; set; }
        public Nullable<decimal> DEPS { get; set; }
        public string PURS_DATE { get; set; }
        public Nullable<decimal> SELF_RATE { get; set; }
        public string FIX { get; set; }
        public string SALES_UNIT { get; set; }
        public string BUY_PROMISE { get; set; }
        public Nullable<decimal> BUY_RATE { get; set; }
        public string CON_SEQ_NO { get; set; }
        public string OBJ_LOC { get; set; }
        public string OBJ_LOC_DESC { get; set; }
        public string OBJ_LOC_ADDR { get; set; }
        public string OBJ_LOC_CTAC { get; set; }
        public string OBJ_LOC_TEL { get; set; }
        public string OBJ_LOC_FAX { get; set; }
        public string OBJ_STS { get; set; }
        public string OBJ_STS_DESC { get; set; }
        public string OBJ_DUE_OWNER { get; set; }
        public string OBJ_PROC_DATE { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string SEND_ADDR { get; set; }
        public string SEND_DATE { get; set; }
        public string SELL_DATE { get; set; }
        public Nullable<decimal> SELL_PRICE { get; set; }
        public string SELL_BUYER { get; set; }
        public string SELL_REMARK { get; set; }
        public string BUY_IF { get; set; }
        public string OBJ_ASUR_TYPE { get; set; }
        public string OBJ_ONUS { get; set; }
        public Nullable<int> ORI_QUA { get; set; }
        public Nullable<int> DEAL_QUA { get; set; }
        public Nullable<int> REM_QUA { get; set; }
        public Nullable<decimal> Con_Mod_Rate { get; set; }
        public string OTC { get; set; }
        public string STOCK_ADDR { get; set; }
        public string BUY_WAY { get; set; }
        public Nullable<decimal> Market_price { get; set; }
        public string Actual_lessee { get; set; }
        public string Is_spec_repo { get; set; }
        public string PURS_INVO_CONF { get; set; }
        public string Car_Type { get; set; }
        public Nullable<decimal> Car_Height { get; set; }
        public Nullable<decimal> Car_Weight { get; set; }
        public Nullable<decimal> Engine_Displacement { get; set; }
        public string Engine_SN { get; set; }
        public string License_STS { get; set; }
    
        public virtual ICollection<OR_ASUR> OR_ASUR { get; set; }
        public virtual ICollection<OR_OBJ_SUM_DEPR> OR_OBJ_SUM_DEPR { get; set; }
        public virtual OR_ORDER OR_ORDER { get; set; }
    }
}
