//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_OBJ_CHG
    {
        public string CON_NO { get; set; }
        public string OBJ_CODE { get; set; }
        public string CHG_DATE { get; set; }
        public string OBJ_LOC { get; set; }
        public string OBJ_LOC_DESC { get; set; }
        public string OBJ_LOC_ADDR { get; set; }
        public string OBJ_STS { get; set; }
        public string OBJ_STS_DESC { get; set; }
        public string OBJ_DUE_OWNER { get; set; }
        public string IMPOSE { get; set; }
        public Nullable<decimal> DISP_AMT { get; set; }
        public Nullable<decimal> PAID_AMT { get; set; }
        public Nullable<decimal> FEBCK_AMT { get; set; }
        public string MEMO { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
        public string proced_aply_no { get; set; }
        public Nullable<int> ORI_QUA { get; set; }
        public Nullable<int> DEAL_QUA { get; set; }
        public Nullable<int> REM_QUA { get; set; }
    }
}
