//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PAPER_IMP_DATA
    {
        public string CON_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string PAPER_NO { get; set; }
        public string PAPER_TYPE { get; set; }
        public string PAPER_UNIT { get; set; }
        public decimal PAPER_PAR_AMT { get; set; }
        public decimal PAPER_ACT_PCT { get; set; }
        public decimal PAPER_ACT_AMT { get; set; }
        public string PAPER_OWNER_ID { get; set; }
        public string PAPER_OWNER { get; set; }
        public decimal SET_IMP_AMT { get; set; }
        public string FUND_DATE_FR { get; set; }
        public string FUND_DATE_TO { get; set; }
        public string IF_ALIEN { get; set; }
        public string IF_NAMED { get; set; }
        public string SET_DATE_FR { get; set; }
        public string SET_DATE_TO { get; set; }
        public string EXT_DATE_TO { get; set; }
        public string IMP_CANCEL_DATE { get; set; }
        public string CANCEL_REASON { get; set; }
        public string ANNU_FLAG { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    
        public virtual OR_CONTRACT OR_CONTRACT { get; set; }
    }
}
