//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PRESS_REC_TEST
    {
        public string CUST_NO { get; set; }
        public string CON_SEQ_NO { get; set; }
        public string PRESS_DATE { get; set; }
        public string PRESS_TIME { get; set; }
        public string EMP_CODE { get; set; }
        public decimal OVER_PERD { get; set; }
        public decimal OVER_DAYS { get; set; }
        public decimal OVER_AMT { get; set; }
        public string PRESS_TYPE { get; set; }
        public string PRESS_MTHD { get; set; }
        public string OPP_USER { get; set; }
        public string PRESS_CTENT { get; set; }
        public string RECV_DATE { get; set; }
        public string BOSS_COMMENT { get; set; }
        public string BOSS_NAME { get; set; }
        public Nullable<System.DateTime> BOSS_DATE { get; set; }
        public string ORD_CLASS { get; set; }
        public string assistant { get; set; }
    }
}
