//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PRESS_STAT_LAST
    {
        public string APLY_NO { get; set; }
        public string CON_NO { get; set; }
        public string PRESS_STAT_DATE { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_SNAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public Nullable<decimal> OVER_AMT { get; set; }
        public Nullable<int> OVER_PERD { get; set; }
        public Nullable<int> OVER_DAYS { get; set; }
        public string PRESS_TYPE { get; set; }
        public string PRESS_MTHD { get; set; }
        public string CTAC { get; set; }
        public string TEL { get; set; }
        public string LAST_PRESS_DATE { get; set; }
        public string MIN_PAY_DATE { get; set; }
        public string PAPER { get; set; }
        public string CHM_YN { get; set; }
        public string ORD_CLASS { get; set; }
        public string PRESS_CTENT { get; set; }
        public string PRED_DATE { get; set; }
    }
}
