//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_PRESS_REC_T
    {
        public System.DateTime 建檔時間 { get; set; }
        public string 建檔者 { get; set; }
        public string 延滯類別 { get; set; }
        public string 申請書編號 { get; set; }
        public string 客戶名稱 { get; set; }
        public string 記錄內容 { get; set; }
        public string 收件者 { get; set; }
    }
}
