//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_QUOT
    {
        public OR_QUOT()
        {
            this.OR_QUOT_DTL = new HashSet<OR_QUOT_DTL>();
        }
    
        public string QUOT_NO { get; set; }
        public string CUST_NO { get; set; }
        public string EMP_CODE { get; set; }
        public string DATE { get; set; }
        public string CUST_NAME { get; set; }
        public string OBJ_NAME { get; set; }
        public decimal COST { get; set; }
        public decimal DURN { get; set; }
        public decimal PERIOD { get; set; }
        public decimal TR { get; set; }
        public string AMOR_MTHD { get; set; }
        public decimal PAY_MTHS { get; set; }
        public string PAY_MTHD { get; set; }
        public decimal SERV_CHAR { get; set; }
        public decimal DEPS { get; set; }
        public decimal SELF_AMT { get; set; }
        public decimal TOLER { get; set; }
        public string REMARK1 { get; set; }
        public decimal PERD1_STAR { get; set; }
        public decimal PERD1_END { get; set; }
        public decimal PERD1_AMT { get; set; }
        public Nullable<decimal> PERD2_STAR { get; set; }
        public Nullable<decimal> PERD2_END { get; set; }
        public Nullable<decimal> PERD2_AMT { get; set; }
        public Nullable<decimal> PERD3_STAR { get; set; }
        public Nullable<decimal> PERD3_END { get; set; }
        public Nullable<decimal> PERD3_AMT { get; set; }
        public Nullable<decimal> PERD4_STAR { get; set; }
        public Nullable<decimal> PERD4_END { get; set; }
        public Nullable<decimal> PERD4_AMT { get; set; }
        public Nullable<decimal> PERD5_STAR { get; set; }
        public Nullable<decimal> PERD5_END { get; set; }
        public Nullable<decimal> PERD5_AMT { get; set; }
    
        public virtual OR_CUSTOM OR_CUSTOM { get; set; }
        public virtual ICollection<OR_QUOT_DTL> OR_QUOT_DTL { get; set; }
    }
}
