//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_RECV_PAPER
    {
        public string APLY_NO { get; set; }
        public string PAPER_NBR { get; set; }
        public string BANK_NO { get; set; }
        public string CUST_NO { get; set; }
        public string EMP_CODE { get; set; }
        public decimal Period { get; set; }
        public string REC_DATE { get; set; }
        public string DUE_DAT { get; set; }
        public string PRJ_CASH_DATE { get; set; }
        public decimal PAPER_AMT { get; set; }
        public string REMARK { get; set; }
        public string ACCOUNT { get; set; }
        public string INV_NAME { get; set; }
        public string CHEQ_KIND { get; set; }
        public string endorsor { get; set; }
        public string Sign1 { get; set; }
        public string Sign1_date { get; set; }
        public string Sign2 { get; set; }
        public string Sign2_date { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
