//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_REQUEST
    {
        public string REQU_NO { get; set; }
        public string CON_SEQ_NO { get; set; }
        public string CUST_NAME { get; set; }
        public string REQU_NAME { get; set; }
        public string REQU_DEPT { get; set; }
        public string REQU_ADDR { get; set; }
        public string REQU_ZIP { get; set; }
        public string DATE_S { get; set; }
        public string DATE_E { get; set; }
        public Nullable<short> TERMS { get; set; }
        public Nullable<short> TERM { get; set; }
        public Nullable<decimal> PRV_PAYABLE { get; set; }
        public Nullable<decimal> PAYABLE { get; set; }
        public Nullable<decimal> DELAY_EXP { get; set; }
        public Nullable<decimal> OTH_FEE { get; set; }
        public string REMARK { get; set; }
        public string PAY_DATE { get; set; }
        public string ACC_NO { get; set; }
        public string INV_REMARK { get; set; }
    }
}
