//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_REQUEST_DTL
    {
        public string REQU_NO { get; set; }
        public short SEQ_NO { get; set; }
        public string PROD_NAME { get; set; }
        public string SPEC { get; set; }
        public string YEAR { get; set; }
        public string MAC_NO { get; set; }
        public string CAR_NO { get; set; }
        public string OBJ_LOC_ADDR { get; set; }
        public Nullable<decimal> BASE_FEE_COLOR { get; set; }
        public Nullable<decimal> BASE_FEE_MONO { get; set; }
        public Nullable<decimal> FREE_QTY_COLOR { get; set; }
        public Nullable<decimal> FREE_QTY_MONO { get; set; }
        public Nullable<decimal> ONE_PRICE_MONO { get; set; }
        public Nullable<decimal> ONE_PRICE_COLOR { get; set; }
        public Nullable<decimal> ONE_PRICE_A3_MONO { get; set; }
        public Nullable<decimal> ONE_PRICE_A3_COLOR { get; set; }
        public Nullable<decimal> USE_QTY_COLOR { get; set; }
        public Nullable<decimal> SUBTOT_COLOR { get; set; }
        public Nullable<decimal> USE_QTY_MONO { get; set; }
        public Nullable<decimal> SUBTOT_MONO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string RANK { get; set; }
        public Nullable<decimal> FREE_QTY_A3_COLOR { get; set; }
        public Nullable<decimal> FREE_QTY_A3_MONO { get; set; }
        public Nullable<decimal> USE_QTY_A3_COLOR { get; set; }
        public Nullable<decimal> USE_QTY_A3_MONO { get; set; }
        public Nullable<decimal> SUM_A4_COLOR { get; set; }
        public Nullable<decimal> SUM_A4_COLOR_LAST { get; set; }
        public Nullable<decimal> SUM_A4_MONO { get; set; }
        public Nullable<decimal> SUM_A4_MONO_LAST { get; set; }
        public Nullable<decimal> SUM_A3_COLOR { get; set; }
        public Nullable<decimal> SUM_A3_COLOR_LAST { get; set; }
        public Nullable<decimal> SUM_A3_MONO { get; set; }
        public Nullable<decimal> SUM_A3_MONO_LAST { get; set; }
        public string OBJ_CODE { get; set; }
        public string OBJ_STS { get; set; }
    }
}
