//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_SUPL_CODE_NUM
    {
        public string SUPL_CUST_STS { get; set; }
        public string 囝份代號 { get; set; }
        public string MOUTH { get; set; }
        public string OPP_CODE { get; set; }
        public decimal 流水號_5 { get; set; }
    }
}
