//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_SRV_REC
    {
        public string CUST_NO { get; set; }
        public string PHONE_DATE { get; set; }
        public string PHONE_TIME { get; set; }
        public string REC_TITLE { get; set; }
        public string REC_CONTENT { get; set; }
        public string KEY_USER { get; set; }
        public string APRV_USER { get; set; }
        public string APRV_DATE { get; set; }
        public string APRV_TIME { get; set; }
        public Nullable<int> CUST_CLASS { get; set; }
        public string APLY_NO { get; set; }
        public string MAC_NO { get; set; }
        public string TAKE_NAME { get; set; }
        public string TAKE_TEL { get; set; }
        public string TAKE_MAIL { get; set; }
        public string TAKE_PHONE { get; set; }
        public Nullable<System.DateTime> PFINISH { get; set; }
        public Nullable<System.DateTime> FIN_DATE { get; set; }
        public string FIN_NAME { get; set; }
        public string SRV_REC_STS { get; set; }
        public string CLOSED_DATE { get; set; }
        public string Re_Date { get; set; }
        public string Re_Time { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    
        public virtual OR_CUSTOM OR_CUSTOM { get; set; }
    }
}
