//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_SALES_MIFY
    {
        public string CON_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string DEPT_BOSS { get; set; }
        public string EMP_CODE { get; set; }
        public string AUD_LVL_NAME { get; set; }
        public string CUST_NO { get; set; }
        public string CASE_SOUR { get; set; }
        public decimal PERIOD { get; set; }
        public decimal APLY_REAL_TR { get; set; }
        public string SALES_MIFY_DATE { get; set; }
        public decimal BUY_AMT { get; set; }
        public Nullable<decimal> PURS_DELAY_AMT { get; set; }
        public Nullable<decimal> CON_DELAY_AMT { get; set; }
        public decimal INCM_TOL { get; set; }
        public Nullable<decimal> PURS_RELS_AMT { get; set; }
        public Nullable<decimal> CON_CANCEL_AMT { get; set; }
        public decimal MARGIN { get; set; }
        public decimal SPREAD { get; set; }
        public decimal TR_REDU { get; set; }
        public decimal PERD_REDU { get; set; }
        public decimal NEW_REDU { get; set; }
        public Nullable<decimal> SPEC_REDU { get; set; }
        public decimal MIFY_RATE { get; set; }
        public decimal MIFY_QTY { get; set; }
        public string DESC { get; set; }
    
        public virtual OR_CONTRACT OR_CONTRACT { get; set; }
        public virtual OR_CUSTOM OR_CUSTOM { get; set; }
    }
}
