//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_TRANS_CIT_DTL
    {
        public string CORP_CODE { get; set; }
        public string CIT_NO { get; set; }
        public decimal SEQ_NO { get; set; }
        public string ACCT_SUBJ_CODE { get; set; }
        public string INN_SUBJ_CODE { get; set; }
        public string CIT_RMK { get; set; }
        public string ADV_STS { get; set; }
        public decimal CIT_AMT { get; set; }
        public decimal BALA_AMT { get; set; }
        public string ANC_SUBJ { get; set; }
    
        public virtual OR_TRANS_CIT OR_TRANS_CIT { get; set; }
    }
}
