//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_WAIT_SEND_BIZ_LETTER
    {
        public string CUST_NO { get; set; }
        public string CON_SEQ_NO { get; set; }
        public string PRESS_DATE { get; set; }
        public string PRESS_TIME { get; set; }
        public decimal SEQ_NUM { get; set; }
    }
}
