//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORIXReceive
    {
        public int SEQ { get; set; }
        public string Consigner { get; set; }
        public string Receive_Date { get; set; }
        public string Register_Num { get; set; }
        public string Recver { get; set; }
        public string Scr { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public string R_Name { get; set; }
        public string IF_Return { get; set; }
        public string dept_no { get; set; }
        public string TYPE { get; set; }
        public string Proced_File { get; set; }
        public string File_ID { get; set; }
        public Nullable<System.DateTime> File_Date { get; set; }
        public string REC_CONTENT { get; set; }
        public string CaseScr { get; set; }
        public string ACT_RENAME { get; set; }
        public Nullable<System.DateTime> ACT_UPDATE { get; set; }
        public string CaseYN { get; set; }
        public string CHECKYN { get; set; }
        public string CHECK_USER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string UPPER_BOSS { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
    }
}
