//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORIXAuthority
    {
        public int SEQ { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> H_LDate { get; set; }
        public Nullable<System.DateTime> H_LEDate { get; set; }
        public string Scr { get; set; }
        public string Boss_ID { get; set; }
        public string Boss2 { get; set; }
        public string M_Host { get; set; }
        public string Doc_STATUS { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string entry_id { get; set; }
        public Nullable<System.DateTime> APRV_DATE { get; set; }
        public string Cy_Mangager { get; set; }
        public string M_Worker { get; set; }
        public Nullable<System.DateTime> M_Date { get; set; }
        public string M_Oworker { get; set; }
        public Nullable<System.DateTime> M_OutDate { get; set; }
        public string Del_Name { get; set; }
        public Nullable<System.DateTime> Del_Date { get; set; }
        public Nullable<System.DateTime> Crd_Boss3Date { get; set; }
    }
}
