//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ORIXContext : DbContext
    {
        public ORIXContext()
            : base("name=ORIXContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CusSrvType> CusSrvTypes { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<gudata> gudatas { get; set; }
        public DbSet<gudata_OLD> gudata_OLD { get; set; }
        public DbSet<gudata_type> gudata_type { get; set; }
        public DbSet<IVM01> IVM01 { get; set; }
        public DbSet<IVM02> IVM02 { get; set; }
        public DbSet<IVM03> IVM03 { get; set; }
        public DbSet<NEW契約餘額> NEW契約餘額 { get; set; }
        public DbSet<OR_ACCS> OR_ACCS { get; set; }
        public DbSet<OR_APRV_EMP> OR_APRV_EMP { get; set; }
        public DbSet<OR_ARP_MTHD> OR_ARP_MTHD { get; set; }
        public DbSet<OR_ASUR> OR_ASUR { get; set; }
        public DbSet<OR_ASUR_TYPE> OR_ASUR_TYPE { get; set; }
        public DbSet<OR_ATCH_CODE> OR_ATCH_CODE { get; set; }
        public DbSet<OR_AUD_AUTH> OR_AUD_AUTH { get; set; }
        public DbSet<OR_AUD_LVL_NAME> OR_AUD_LVL_NAME { get; set; }
        public DbSet<OR_AUD_REF> OR_AUD_REF { get; set; }
        public DbSet<OR_AUD_TYPE> OR_AUD_TYPE { get; set; }
        public DbSet<OR_BAD_DEBT_EMP> OR_BAD_DEBT_EMP { get; set; }
        public DbSet<OR_BANK_AMT> OR_BANK_AMT { get; set; }
        public DbSet<OR_BANK_LOAN> OR_BANK_LOAN { get; set; }
        public DbSet<OR_BANK_LOAN_CHG> OR_BANK_LOAN_CHG { get; set; }
        public DbSet<OR_BANK_LOAN_DTL> OR_BANK_LOAN_DTL { get; set; }
        public DbSet<OR_BANK_RTN> OR_BANK_RTN { get; set; }
        public DbSet<OR_BANK_RTN_DTL> OR_BANK_RTN_DTL { get; set; }
        public DbSet<OR_BLOC> OR_BLOC { get; set; }
        public DbSet<OR_BLOC_CODE_NUM> OR_BLOC_CODE_NUM { get; set; }
        public DbSet<OR_BOOK> OR_BOOK { get; set; }
        public DbSet<OR_BOOK_DTL> OR_BOOK_DTL { get; set; }
        public DbSet<OR_BUS_TUBL_CODE> OR_BUS_TUBL_CODE { get; set; }
        public DbSet<OR_CAR_IMP_DATA> OR_CAR_IMP_DATA { get; set; }
        public DbSet<OR_CASE_APLY_APLY_COND> OR_CASE_APLY_APLY_COND { get; set; }
        public DbSet<OR_CASE_APLY_ARP> OR_CASE_APLY_ARP { get; set; }
        public DbSet<OR_CASE_APLY_ASUR> OR_CASE_APLY_ASUR { get; set; }
        public DbSet<OR_CASE_APLY_AUD> OR_CASE_APLY_AUD { get; set; }
        public DbSet<OR_CASE_APLY_BASE> OR_CASE_APLY_BASE { get; set; }
        public DbSet<OR_CASE_APLY_CREDIT> OR_CASE_APLY_CREDIT { get; set; }
        public DbSet<OR_CASE_APLY_EXE_AMOR_DTL> OR_CASE_APLY_EXE_AMOR_DTL { get; set; }
        public DbSet<OR_CASE_APLY_EXE_COND> OR_CASE_APLY_EXE_COND { get; set; }
        public DbSet<OR_CASE_APLY_FEE> OR_CASE_APLY_FEE { get; set; }
        public DbSet<OR_CASE_APLY_IMAGE> OR_CASE_APLY_IMAGE { get; set; }
        public DbSet<OR_CASE_APLY_MOBJ> OR_CASE_APLY_MOBJ { get; set; }
        public DbSet<OR_CASE_APLY_OBJ> OR_CASE_APLY_OBJ { get; set; }
        public DbSet<OR_CASE_APLY_RLTY_IMP> OR_CASE_APLY_RLTY_IMP { get; set; }
        public DbSet<OR_CASE_APLY_SCUR> OR_CASE_APLY_SCUR { get; set; }
        public DbSet<OR_CASE_APLY_SHARE_DET> OR_CASE_APLY_SHARE_DET { get; set; }
        public DbSet<OR_CASE_AUD_SELECT> OR_CASE_AUD_SELECT { get; set; }
        public DbSet<OR_CASE_CONT> OR_CASE_CONT { get; set; }
        public DbSet<OR_CASE_EXE_FEE> OR_CASE_EXE_FEE { get; set; }
        public DbSet<OR_CASE_INV_MERGE> OR_CASE_INV_MERGE { get; set; }
        public DbSet<OR_CASE_INV_MERGE_SET> OR_CASE_INV_MERGE_SET { get; set; }
        public DbSet<or_case_jcic_contract_data> or_case_jcic_contract_data { get; set; }
        public DbSet<or_case_jcic_contract_head> or_case_jcic_contract_head { get; set; }
        public DbSet<or_case_jcic_payment_data> or_case_jcic_payment_data { get; set; }
        public DbSet<or_case_jcic_payment_head> or_case_jcic_payment_head { get; set; }
        public DbSet<or_case_jcic_set> or_case_jcic_set { get; set; }
        public DbSet<OR_CASE_REF> OR_CASE_REF { get; set; }
        public DbSet<OR_CASE_TYPE> OR_CASE_TYPE { get; set; }
        public DbSet<OR_CODE> OR_CODE { get; set; }
        public DbSet<OR_COMMON_CODE> OR_COMMON_CODE { get; set; }
        public DbSet<OR_CON_BAL> OR_CON_BAL { get; set; }
        public DbSet<OR_CON_CHG> OR_CON_CHG { get; set; }
        public DbSet<OR_CON_CHG_CODE> OR_CON_CHG_CODE { get; set; }
        public DbSet<OR_CON_CODE_NUM> OR_CON_CODE_NUM { get; set; }
        public DbSet<OR_CON_COMMAND> OR_CON_COMMAND { get; set; }
        public DbSet<OR_CON_VAL_BAL> OR_CON_VAL_BAL { get; set; }
        public DbSet<OR_CONTRACT> OR_CONTRACT { get; set; }
        public DbSet<OR_COUNTRY> OR_COUNTRY { get; set; }
        public DbSet<OR_CUST_DATA_CHG_REC> OR_CUST_DATA_CHG_REC { get; set; }
        public DbSet<OR_CUST_KIND> OR_CUST_KIND { get; set; }
        public DbSet<OR_CUST_NAT> OR_CUST_NAT { get; set; }
        public DbSet<OR_CUST_TOTAL> OR_CUST_TOTAL { get; set; }
        public DbSet<OR_CUSTOM> OR_CUSTOM { get; set; }
        public DbSet<OR_DEPR_CODE> OR_DEPR_CODE { get; set; }
        public DbSet<OR_DEPT> OR_DEPT { get; set; }
        public DbSet<OR_DEPT_AUD_LVL> OR_DEPT_AUD_LVL { get; set; }
        public DbSet<OR_DEPT_GRANT> OR_DEPT_GRANT { get; set; }
        public DbSet<OR_DISH_NOTY> OR_DISH_NOTY { get; set; }
        public DbSet<OR_DISH_PROC> OR_DISH_PROC { get; set; }
        public DbSet<OR_DIVD_RATE> OR_DIVD_RATE { get; set; }
        public DbSet<OR_EMP> OR_EMP { get; set; }
        public DbSet<OR_EMP_BELONG_DEPT> OR_EMP_BELONG_DEPT { get; set; }
        public DbSet<OR_EMP_PASS> OR_EMP_PASS { get; set; }
        public DbSet<OR_EXCH> OR_EXCH { get; set; }
        public DbSet<OR_FAULT> OR_FAULT { get; set; }
        public DbSet<OR_FC> OR_FC { get; set; }
        public DbSet<OR_FRC> OR_FRC { get; set; }
        public DbSet<OR_FRC_OBJ_BUY_SET> OR_FRC_OBJ_BUY_SET { get; set; }
        public DbSet<OR_FUNCTION> OR_FUNCTION { get; set; }
        public DbSet<OR_GROUP> OR_GROUP { get; set; }
        public DbSet<OR_GRP_EMP_SET> OR_GRP_EMP_SET { get; set; }
        public DbSet<OR_GRP_FUN_SET> OR_GRP_FUN_SET { get; set; }
        public DbSet<OR_IMPS_APLY_BASE> OR_IMPS_APLY_BASE { get; set; }
        public DbSet<OR_IMPS_APLY_CONDIT> OR_IMPS_APLY_CONDIT { get; set; }
        public DbSet<OR_IMPS_APLY_IMPS_AUD> OR_IMPS_APLY_IMPS_AUD { get; set; }
        public DbSet<OR_IMPS_APLY_RLTY_IMP> OR_IMPS_APLY_RLTY_IMP { get; set; }
        public DbSet<OR_IMPS_APLY_SCUR> OR_IMPS_APLY_SCUR { get; set; }
        public DbSet<OR_IMPS_APLY_SELL_AUD> OR_IMPS_APLY_SELL_AUD { get; set; }
        public DbSet<OR_IMPS_APLY_SET_AMT> OR_IMPS_APLY_SET_AMT { get; set; }
        public DbSet<OR_IMPS_CUST> OR_IMPS_CUST { get; set; }
        public DbSet<OR_INV_APART_DTL> OR_INV_APART_DTL { get; set; }
        public DbSet<OR_INV_APART_OBJ> OR_INV_APART_OBJ { get; set; }
        public DbSet<OR_INV_APART_SET> OR_INV_APART_SET { get; set; }
        public DbSet<OR_INV_DATA> OR_INV_DATA { get; set; }
        public DbSet<OR_INV_MERGE_CHG_LOG> OR_INV_MERGE_CHG_LOG { get; set; }
        public DbSet<OR_JOB_NAME> OR_JOB_NAME { get; set; }
        public DbSet<OR_LACK_DATA> OR_LACK_DATA { get; set; }
        public DbSet<OR_LACK_PROC> OR_LACK_PROC { get; set; }
        public DbSet<OR_LEASE_OBJ_MAP> OR_LEASE_OBJ_MAP { get; set; }
        public DbSet<OR_LOAN_MTHD> OR_LOAN_MTHD { get; set; }
        public DbSet<OR_MAIN_MENU_SET> OR_MAIN_MENU_SET { get; set; }
        public DbSet<OR_MARG_MIFY> OR_MARG_MIFY { get; set; }
        public DbSet<OR_MERG_MAIL> OR_MERG_MAIL { get; set; }
        public DbSet<OR_MOBJECT> OR_MOBJECT { get; set; }
        public DbSet<OR_MOV_IMP_DATA> OR_MOV_IMP_DATA { get; set; }
        public DbSet<OR_OBJ_CATE> OR_OBJ_CATE { get; set; }
        public DbSet<OR_OBJ_CHG> OR_OBJ_CHG { get; set; }
        public DbSet<OR_OBJ_DEPR_SET> OR_OBJ_DEPR_SET { get; set; }
        public DbSet<OR_OBJ_DTL_CATE> OR_OBJ_DTL_CATE { get; set; }
        public DbSet<OR_OBJ_STS> OR_OBJ_STS { get; set; }
        public DbSet<OR_OBJ_SUM_DEPR> OR_OBJ_SUM_DEPR { get; set; }
        public DbSet<OR_OBJECT> OR_OBJECT { get; set; }
        public DbSet<OR_ORDER> OR_ORDER { get; set; }
        public DbSet<OR_OTH_IMP> OR_OTH_IMP { get; set; }
        public DbSet<OR_PA> OR_PA { get; set; }
        public DbSet<OR_PAPER_IMP_DATA> OR_PAPER_IMP_DATA { get; set; }
        public DbSet<OR_PRESS_CODE> OR_PRESS_CODE { get; set; }
        public DbSet<OR_PRESS_DATE_DEF> OR_PRESS_DATE_DEF { get; set; }
        public DbSet<OR_PRESS_REC> OR_PRESS_REC { get; set; }
        public DbSet<OR_PRESS_REC_T> OR_PRESS_REC_T { get; set; }
        public DbSet<OR_PRESS_REC_TEST> OR_PRESS_REC_TEST { get; set; }
        public DbSet<OR_PRESS_STAT> OR_PRESS_STAT { get; set; }
        public DbSet<OR_PRESS_STAT_LAST> OR_PRESS_STAT_LAST { get; set; }
        public DbSet<OR_PRESS_STAT_NO> OR_PRESS_STAT_NO { get; set; }
        public DbSet<OR_PRESS_STAT_POINT> OR_PRESS_STAT_POINT { get; set; }
        public DbSet<OR_PRESS_TYPE> OR_PRESS_TYPE { get; set; }
        public DbSet<OR_QUOT> OR_QUOT { get; set; }
        public DbSet<OR_QUOT_DTL> OR_QUOT_DTL { get; set; }
        public DbSet<OR_QUOTA_APLY_BASE> OR_QUOTA_APLY_BASE { get; set; }
        public DbSet<OR_RECV_PAPER> OR_RECV_PAPER { get; set; }
        public DbSet<OR_REQUEST> OR_REQUEST { get; set; }
        public DbSet<OR_REQUEST_DTL> OR_REQUEST_DTL { get; set; }
        public DbSet<OR_REQUEST_REMARK> OR_REQUEST_REMARK { get; set; }
        public DbSet<OR_RLTY_IMP_DATA> OR_RLTY_IMP_DATA { get; set; }
        public DbSet<OR_SALES_AUTH> OR_SALES_AUTH { get; set; }
        public DbSet<OR_SALES_AUTH_DTL> OR_SALES_AUTH_DTL { get; set; }
        public DbSet<OR_SALES_AUTH_HIST> OR_SALES_AUTH_HIST { get; set; }
        public DbSet<OR_SALES_MIFY> OR_SALES_MIFY { get; set; }
        public DbSet<OR_SHIP_IMP_DATA> OR_SHIP_IMP_DATA { get; set; }
        public DbSet<OR_SHT_NO_NUM> OR_SHT_NO_NUM { get; set; }
        public DbSet<OR_SRV_REC> OR_SRV_REC { get; set; }
        public DbSet<OR_SUPL_CODE_NUM> OR_SUPL_CODE_NUM { get; set; }
        public DbSet<OR_TR> OR_TR { get; set; }
        public DbSet<OR_TRANS_CIT> OR_TRANS_CIT { get; set; }
        public DbSet<OR_TRANS_CIT_DTL> OR_TRANS_CIT_DTL { get; set; }
        public DbSet<OR_WAIT_SEND_BIZ_LETTER> OR_WAIT_SEND_BIZ_LETTER { get; set; }
        public DbSet<OR_WAIT_SEND_KEEP_LETTER> OR_WAIT_SEND_KEEP_LETTER { get; set; }
        public DbSet<OR_WAIT_SEND_MAIL> OR_WAIT_SEND_MAIL { get; set; }
        public DbSet<OR_YEAR_SALES_PRJ> OR_YEAR_SALES_PRJ { get; set; }
        public DbSet<OR2_ACT> OR2_ACT { get; set; }
        public DbSet<OR2_ACTION> OR2_ACTION { get; set; }
        public DbSet<OR2_ACTION_DETAIL> OR2_ACTION_DETAIL { get; set; }
        public DbSet<OR2_APLY_APRV_PERSON> OR2_APLY_APRV_PERSON { get; set; }
        public DbSet<OR2_AR_APLY_COND> OR2_AR_APLY_COND { get; set; }
        public DbSet<OR2_AR_APLY_SHARE_DET> OR2_AR_APLY_SHARE_DET { get; set; }
        public DbSet<OR2_AR_APLY_SHARE_DET_1> OR2_AR_APLY_SHARE_DET_1 { get; set; }
        public DbSet<OR2_AR_APRV_COND> OR2_AR_APRV_COND { get; set; }
        public DbSet<OR2_AR_B_CTL> OR2_AR_B_CTL { get; set; }
        public DbSet<OR2_AR_B_CTL_1> OR2_AR_B_CTL_1 { get; set; }
        public DbSet<OR2_AR_BUYER> OR2_AR_BUYER { get; set; }
        public DbSet<OR2_AR_CASE> OR2_AR_CASE { get; set; }
        public DbSet<OR2_AR_INVOICE> OR2_AR_INVOICE { get; set; }
        public DbSet<OR2_AR_PAY_APLY> OR2_AR_PAY_APLY { get; set; }
        public DbSet<OR2_AR_PAY_APLY_1> OR2_AR_PAY_APLY_1 { get; set; }
        public DbSet<OR2_AR_TT_DTL> OR2_AR_TT_DTL { get; set; }
        public DbSet<OR2_ATCH_OTHER> OR2_ATCH_OTHER { get; set; }
        public DbSet<OR2_BLD_MORT> OR2_BLD_MORT { get; set; }
        public DbSet<OR2_BUILDING> OR2_BUILDING { get; set; }
        public DbSet<OR2_CAN_REASON> OR2_CAN_REASON { get; set; }
        public DbSet<OR2_CHECK_TEMP> OR2_CHECK_TEMP { get; set; }
        public DbSet<OR2_CUST_QUOTA_APLY> OR2_CUST_QUOTA_APLY { get; set; }
        public DbSet<OR2_CUST_QUOTA_APRV> OR2_CUST_QUOTA_APRV { get; set; }
        public DbSet<OR2_DAILY_PERSON> OR2_DAILY_PERSON { get; set; }
        public DbSet<OR2_DOC_BR_APLY_DETAIL> OR2_DOC_BR_APLY_DETAIL { get; set; }
        public DbSet<OR2_DOC_BR_APLY_SHEET> OR2_DOC_BR_APLY_SHEET { get; set; }
        public DbSet<OR2_DOC_BR_APRV1> OR2_DOC_BR_APRV1 { get; set; }
        public DbSet<OR2_DOC_BR_APRV2> OR2_DOC_BR_APRV2 { get; set; }
        public DbSet<OR2_DOC_BR_APRV3> OR2_DOC_BR_APRV3 { get; set; }
        public DbSet<OR2_DOC_BR_DETAIL> OR2_DOC_BR_DETAIL { get; set; }
        public DbSet<OR2_DOC_BR_SHEET> OR2_DOC_BR_SHEET { get; set; }
        public DbSet<OR2_DOC_CAN> OR2_DOC_CAN { get; set; }
        public DbSet<OR2_DOC_CAN_APRV> OR2_DOC_CAN_APRV { get; set; }
        public DbSet<OR2_DOC_CHANGE> OR2_DOC_CHANGE { get; set; }
        public DbSet<OR2_DOC_IN_DETAIL> OR2_DOC_IN_DETAIL { get; set; }
        public DbSet<OR2_DOC_IN_SHEET> OR2_DOC_IN_SHEET { get; set; }
        public DbSet<OR2_DOC_R_DETAIL> OR2_DOC_R_DETAIL { get; set; }
        public DbSet<OR2_DOC_R_SHEET> OR2_DOC_R_SHEET { get; set; }
        public DbSet<OR2_DOC_STATUS> OR2_DOC_STATUS { get; set; }
        public DbSet<OR2_DOC_STOCK> OR2_DOC_STOCK { get; set; }
        public DbSet<OR2_FARE_APLY> OR2_FARE_APLY { get; set; }
        public DbSet<OR2_FARE_APLY_DETAIL> OR2_FARE_APLY_DETAIL { get; set; }
        public DbSet<OR2_FARE_APRV> OR2_FARE_APRV { get; set; }
        public DbSet<OR2_FARE_CODE> OR2_FARE_CODE { get; set; }
        public DbSet<OR2_FARE_CODE1> OR2_FARE_CODE1 { get; set; }
        public DbSet<OR2_FARE_DEPT_AUD_LVL> OR2_FARE_DEPT_AUD_LVL { get; set; }
        public DbSet<OR2_FARE_PERSON> OR2_FARE_PERSON { get; set; }
        public DbSet<OR2_FARE_RECV_CODE> OR2_FARE_RECV_CODE { get; set; }
        public DbSet<OR2_FEE> OR2_FEE { get; set; }
        public DbSet<OR2_GUDATA> OR2_GUDATA { get; set; }
        public DbSet<OR2_LAND> OR2_LAND { get; set; }
        public DbSet<OR2_LAND_MORT> OR2_LAND_MORT { get; set; }
        public DbSet<OR2_LAW_PAPER> OR2_LAW_PAPER { get; set; }
        public DbSet<OR2_LEND_SHEET> OR2_LEND_SHEET { get; set; }
        public DbSet<OR2_LOC> OR2_LOC { get; set; }
        public DbSet<OR2_LOC_DETAIL> OR2_LOC_DETAIL { get; set; }
        public DbSet<OR2_PAPER_BAL> OR2_PAPER_BAL { get; set; }
        public DbSet<OR2_PAPER_RULE_COLOR> OR2_PAPER_RULE_COLOR { get; set; }
        public DbSet<OR2_PAPER_RULE_COLOR_HIST> OR2_PAPER_RULE_COLOR_HIST { get; set; }
        public DbSet<OR2_PAPER_RULE_MASTER> OR2_PAPER_RULE_MASTER { get; set; }
        public DbSet<OR2_PAPER_RULE_MONO> OR2_PAPER_RULE_MONO { get; set; }
        public DbSet<OR2_PAPER_RULE_MONO_HIST> OR2_PAPER_RULE_MONO_HIST { get; set; }
        public DbSet<OR2_PAPER_SUP_APLY> OR2_PAPER_SUP_APLY { get; set; }
        public DbSet<OR2_PAPER_SUPPLY_INV> OR2_PAPER_SUPPLY_INV { get; set; }
        public DbSet<OR2_PAPER_SUPPLY_INV_TEMP> OR2_PAPER_SUPPLY_INV_TEMP { get; set; }
        public DbSet<OR2_PAPER_USE_DTL> OR2_PAPER_USE_DTL { get; set; }
        public DbSet<OR2_PAPER_USE_DTL_TEMP> OR2_PAPER_USE_DTL_TEMP { get; set; }
        public DbSet<OR2_RCV_DETAIL> OR2_RCV_DETAIL { get; set; }
        public DbSet<OR2_RCV_MONEY> OR2_RCV_MONEY { get; set; }
        public DbSet<OR2_SAVE_APRV> OR2_SAVE_APRV { get; set; }
        public DbSet<OR2_SAVE_CASE> OR2_SAVE_CASE { get; set; }
        public DbSet<OR2_SAVE_CASE_DTL> OR2_SAVE_CASE_DTL { get; set; }
        public DbSet<OR2_SAVE_GOAL> OR2_SAVE_GOAL { get; set; }
        public DbSet<OR2_SAVE_PERSON> OR2_SAVE_PERSON { get; set; }
        public DbSet<OR2_WARRANTER> OR2_WARRANTER { get; set; }
        public DbSet<OR3_APRVD_CASE_PROGRESS> OR3_APRVD_CASE_PROGRESS { get; set; }
        public DbSet<OR3_AUDIT_HEAD> OR3_AUDIT_HEAD { get; set; }
        public DbSet<OR3_BORROW_EXP_INTEREST_DTL> OR3_BORROW_EXP_INTEREST_DTL { get; set; }
        public DbSet<OR3_BORROW_EXP_REPAY_DTL> OR3_BORROW_EXP_REPAY_DTL { get; set; }
        public DbSet<OR3_BORROW_RATE> OR3_BORROW_RATE { get; set; }
        public DbSet<OR3_BORROW_REAL_REPAY_DTL> OR3_BORROW_REAL_REPAY_DTL { get; set; }
        public DbSet<OR3_CASE_APLY_APLY_COND2> OR3_CASE_APLY_APLY_COND2 { get; set; }
        public DbSet<OR3_CASE_APLY_POLICY> OR3_CASE_APLY_POLICY { get; set; }
        public DbSet<OR3_CASE_APLY_RENTER> OR3_CASE_APLY_RENTER { get; set; }
        public DbSet<OR3_CASE_APLY_SIGN_REC> OR3_CASE_APLY_SIGN_REC { get; set; }
        public DbSet<OR3_Common_Remark> OR3_Common_Remark { get; set; }
        public DbSet<OR3_CON_BAL> OR3_CON_BAL { get; set; }
        public DbSet<OR3_COND_DEF> OR3_COND_DEF { get; set; }
        public DbSet<OR3_COND_LST> OR3_COND_LST { get; set; }
        public DbSet<OR3_CONTRACT_SURPLUS> OR3_CONTRACT_SURPLUS { get; set; }
        public DbSet<OR3_CONTRACT_TEMP_PARA> OR3_CONTRACT_TEMP_PARA { get; set; }
        public DbSet<OR3_CONTRACT_TEMP_PARA_LST> OR3_CONTRACT_TEMP_PARA_LST { get; set; }
        public DbSet<OR3_CONTRACT_TEMP_SET> OR3_CONTRACT_TEMP_SET { get; set; }
        public DbSet<OR3_CRITICAL_TRACKING> OR3_CRITICAL_TRACKING { get; set; }
        public DbSet<OR3_EMAIL_LIST> OR3_EMAIL_LIST { get; set; }
        public DbSet<OR3_FILE_STORE> OR3_FILE_STORE { get; set; }
        public DbSet<OR3_FRC_DEP> OR3_FRC_DEP { get; set; }
        public DbSet<OR3_FRC_SALES> OR3_FRC_SALES { get; set; }
        public DbSet<OR3_FRC_VER> OR3_FRC_VER { get; set; }
        public DbSet<OR3_FUNC_BTN> OR3_FUNC_BTN { get; set; }
        public DbSet<OR3_FUNCTION> OR3_FUNCTION { get; set; }
        public DbSet<OR3_FUNDS> OR3_FUNDS { get; set; }
        public DbSet<OR3_HINT> OR3_HINT { get; set; }
        public DbSet<OR3_LATENT_CUSTOM> OR3_LATENT_CUSTOM { get; set; }
        public DbSet<OR3_MASTER_CONTRACT> OR3_MASTER_CONTRACT { get; set; }
        public DbSet<OR3_MENU_SET> OR3_MENU_SET { get; set; }
        public DbSet<OR3_MIME> OR3_MIME { get; set; }
        public DbSet<OR3_PAPER_AP_TMP> OR3_PAPER_AP_TMP { get; set; }
        public DbSet<OR3_PAPER_AR_TMP> OR3_PAPER_AR_TMP { get; set; }
        public DbSet<OR3_PAPER_QUOTATION> OR3_PAPER_QUOTATION { get; set; }
        public DbSet<OR3_PAPER_QUOTATION_VALUATION> OR3_PAPER_QUOTATION_VALUATION { get; set; }
        public DbSet<OR3_PAPER_SUPPLY_INV_TEMP> OR3_PAPER_SUPPLY_INV_TEMP { get; set; }
        public DbSet<OR3_PAPER_USE_DTL> OR3_PAPER_USE_DTL { get; set; }
        public DbSet<OR3_PAPER_USE_DTL_HIS> OR3_PAPER_USE_DTL_HIS { get; set; }
        public DbSet<OR3_PAPER_USE_DTL_TMP> OR3_PAPER_USE_DTL_TMP { get; set; }
        public DbSet<OR3_PAPER_USE_DTL_TMP_HIS> OR3_PAPER_USE_DTL_TMP_HIS { get; set; }
        public DbSet<OR3_QUOTA_APLY_APLY_COND> OR3_QUOTA_APLY_APLY_COND { get; set; }
        public DbSet<OR3_QUOTA_APLY_APRV_COND> OR3_QUOTA_APLY_APRV_COND { get; set; }
        public DbSet<OR3_QUOTA_APLY_BASE> OR3_QUOTA_APLY_BASE { get; set; }
        public DbSet<OR3_QUOTA_APLY_OBJ> OR3_QUOTA_APLY_OBJ { get; set; }
        public DbSet<OR3_QUOTA_APLY_OBJ_ACCS> OR3_QUOTA_APLY_OBJ_ACCS { get; set; }
        public DbSet<OR3_QUOTA_APLY_USER> OR3_QUOTA_APLY_USER { get; set; }
        public DbSet<OR3_QUOTA_APRV_CALSS_APLY> OR3_QUOTA_APRV_CALSS_APLY { get; set; }
        public DbSet<OR3_QUOTA_APRV_CALSS_APRV> OR3_QUOTA_APRV_CALSS_APRV { get; set; }
        public DbSet<OR3_QUOTA_CASE_TYPE> OR3_QUOTA_CASE_TYPE { get; set; }
        public DbSet<OR3_QUOTA_CONTAIN_FORMER_APLY> OR3_QUOTA_CONTAIN_FORMER_APLY { get; set; }
        public DbSet<OR3_QUOTA_CONTAIN_FORMER_APRV> OR3_QUOTA_CONTAIN_FORMER_APRV { get; set; }
        public DbSet<OR3_RECV_PAPER_TEMP> OR3_RECV_PAPER_TEMP { get; set; }
        public DbSet<OR3_SALES_DEP_REC> OR3_SALES_DEP_REC { get; set; }
        public DbSet<OR3_USER_FUNC> OR3_USER_FUNC { get; set; }
        public DbSet<OR3_USER_FUNC_BTN> OR3_USER_FUNC_BTN { get; set; }
        public DbSet<OR3_USERS> OR3_USERS { get; set; }
        public DbSet<OR3_VISIT_REC> OR3_VISIT_REC { get; set; }
        public DbSet<OR3_Zip> OR3_Zip { get; set; }
        public DbSet<OR3_授權類別> OR3_授權類別 { get; set; }
        public DbSet<OR3_業績備註> OR3_業績備註 { get; set; }
        public DbSet<OR3_機具分類表> OR3_機具分類表 { get; set; }
        public DbSet<ORIX_CHM01_OP> ORIX_CHM01_OP { get; set; }
        public DbSet<ORM01> ORM01 { get; set; }
        public DbSet<ORM02> ORM02 { get; set; }
        public DbSet<ORM03> ORM03 { get; set; }
        public DbSet<ORT01> ORT01 { get; set; }
        public DbSet<ORT02> ORT02 { get; set; }
        public DbSet<ORT03> ORT03 { get; set; }
        public DbSet<ORT04> ORT04 { get; set; }
        public DbSet<ORT05> ORT05 { get; set; }
        public DbSet<ORT06> ORT06 { get; set; }
        public DbSet<OTC_APLY_STORE> OTC_APLY_STORE { get; set; }
        public DbSet<OTC_APLY_STORE_CHG> OTC_APLY_STORE_CHG { get; set; }
        public DbSet<OTC_APLY_STORE1> OTC_APLY_STORE1 { get; set; }
        public DbSet<OTC_CASE_BASE_REM> OTC_CASE_BASE_REM { get; set; }
        public DbSet<OTC_CUSTCOP> OTC_CUSTCOP { get; set; }
        public DbSet<OTC_CUSTINCOME> OTC_CUSTINCOME { get; set; }
        public DbSet<OTC_CUSTMEM> OTC_CUSTMEM { get; set; }
        public DbSet<OTC_NEW_CUST_TYPE> OTC_NEW_CUST_TYPE { get; set; }
        public DbSet<OTC_VISA_BASE> OTC_VISA_BASE { get; set; }
        public DbSet<pbcatedt> pbcatedts { get; set; }
        public DbSet<pbcatfmt> pbcatfmts { get; set; }
        public DbSet<pbcatvld> pbcatvlds { get; set; }
        public DbSet<ReasonMail> ReasonMails { get; set; }
        public DbSet<SL91> SL91 { get; set; }
        public DbSet<sq_mail_check> sq_mail_check { get; set; }
        public DbSet<sq_quta> sq_quta { get; set; }
        public DbSet<sq_quta_m> sq_quta_m { get; set; }
        public DbSet<sq_quta_mv> sq_quta_mv { get; set; }
        public DbSet<STM01> STM01 { get; set; }
        public DbSet<STM03> STM03 { get; set; }
        public DbSet<STM04> STM04 { get; set; }
        public DbSet<STM06> STM06 { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<AR_PRED_date_1> AR_PRED_date_1 { get; set; }
        public DbSet<JCICAPLY> JCICAPLies { get; set; }
        public DbSet<RCF099> RCF099 { get; set; }
        public DbSet<v_OR_DEPT> v_OR_DEPT { get; set; }
        public DbSet<v_OR_EMP> v_OR_EMP { get; set; }
        public DbSet<view_rent_hist> view_rent_hist { get; set; }
        public DbSet<ACC10> ACC10 { get; set; }
        public DbSet<ACC11> ACC11 { get; set; }
        public DbSet<ACC18> ACC18 { get; set; }
        public DbSet<AdminId> AdminIds { get; set; }
        public DbSet<AMCREO> AMCREOs { get; set; }
        public DbSet<AnnualEmp> AnnualEmps { get; set; }
        public DbSet<AOComment> AOComments { get; set; }
        public DbSet<AOType> AOTypes { get; set; }
        public DbSet<ApplyMail> ApplyMails { get; set; }
        public DbSet<ApproveType> ApproveTypes { get; set; }
        public DbSet<AskLeave> AskLeaves { get; set; }
        public DbSet<AskLeaveClass> AskLeaveClasses { get; set; }
        public DbSet<Beforehand> Beforehands { get; set; }
        public DbSet<CameraDetail> CameraDetails { get; set; }
        public DbSet<CameraMain> CameraMains { get; set; }
        public DbSet<CameraType> CameraTypes { get; set; }
        public DbSet<CareDetail> CareDetails { get; set; }
        public DbSet<CareKeep> CareKeeps { get; set; }
        public DbSet<CareMain> CareMains { get; set; }
        public DbSet<CareType> CareTypes { get; set; }
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<ClockEmp> ClockEmps { get; set; }
        public DbSet<ClockType> ClockTypes { get; set; }
        public DbSet<ComCrit> ComCrits { get; set; }
        public DbSet<ComDetail> ComDetails { get; set; }
        public DbSet<ComeVisit> ComeVisits { get; set; }
        public DbSet<ComMain> ComMains { get; set; }
        public DbSet<ComMd> ComMds { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyAply> CompanyAplies { get; set; }
        public DbSet<CompanyAplyScr> CompanyAplyScrs { get; set; }
        public DbSet<CompanyCopy> CompanyCopies { get; set; }
        public DbSet<CompanyCopyType> CompanyCopyTypes { get; set; }
        public DbSet<CompanyName> CompanyNames { get; set; }
        public DbSet<ComType> ComTypes { get; set; }
        public DbSet<ConfRoomDetail> ConfRoomDetails { get; set; }
        public DbSet<ConfRoomDetail2009> ConfRoomDetail2009 { get; set; }
        public DbSet<ConfRoomMain> ConfRoomMains { get; set; }
        public DbSet<ConfRoomType> ConfRoomTypes { get; set; }
        public DbSet<Counter> Counters { get; set; }
        public DbSet<CreditTime> CreditTimes { get; set; }
        public DbSet<CrossRedate> CrossRedates { get; set; }
        public DbSet<CrossSell> CrossSells { get; set; }
        public DbSet<CustomApprove> CustomApproves { get; set; }
        public DbSet<CustomApproveNType> CustomApproveNTypes { get; set; }
        public DbSet<CustomeApproveName> CustomeApproveNames { get; set; }
        public DbSet<CustRequire> CustRequires { get; set; }
        public DbSet<CustRequireType> CustRequireTypes { get; set; }
        public DbSet<DiplomaticEmp> DiplomaticEmps { get; set; }
        public DbSet<Dispatch> Dispatches { get; set; }
        public DbSet<DispatchType> DispatchTypes { get; set; }
        public DbSet<DocMd> DocMds { get; set; }
        public DbSet<EmpNote> EmpNotes { get; set; }
        public DbSet<EmpSign> EmpSigns { get; set; }
        public DbSet<EmpTravel> EmpTravels { get; set; }
        public DbSet<Entrance> Entrances { get; set; }
        public DbSet<EquiApply> EquiApplies { get; set; }
        public DbSet<EquiApplyDetail> EquiApplyDetails { get; set; }
        public DbSet<EquiSpec> EquiSpecs { get; set; }
        public DbSet<EquiStock> EquiStocks { get; set; }
        public DbSet<EquiType> EquiTypes { get; set; }
        public DbSet<ETemporary> ETemporaries { get; set; }
        public DbSet<ExpAllot> ExpAllots { get; set; }
        public DbSet<EYesterday> EYesterdays { get; set; }
        public DbSet<GeneralItem> GeneralItems { get; set; }
        public DbSet<GeneralService> GeneralServices { get; set; }
        public DbSet<GuestBook> GuestBooks { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<HolidayLogin> HolidayLogins { get; set; }
        public DbSet<HolidayType> HolidayTypes { get; set; }
        public DbSet<HolidayType1> HolidayType1 { get; set; }
        public DbSet<HomePage> HomePages { get; set; }
        public DbSet<HostName> HostNames { get; set; }
        public DbSet<HR0101> HR0101 { get; set; }
        public DbSet<HR6861> HR6861 { get; set; }
        public DbSet<HR6861T> HR6861T { get; set; }
        public DbSet<HREMP> HREMPs { get; set; }
        public DbSet<HREmpScr> HREmpScrs { get; set; }
        public DbSet<HRMail> HRMails { get; set; }
        public DbSet<HU_DEPT_20121108> HU_DEPT_20121108 { get; set; }
        public DbSet<HU_DEPT1> HU_DEPT1 { get; set; }
        public DbSet<Information> Information { get; set; }
        public DbSet<InformationType> InformationTypes { get; set; }
        public DbSet<InsuranceRatio> InsuranceRatios { get; set; }
        public DbSet<InsuranceType> InsuranceTypes { get; set; }
        public DbSet<IP位址資料> IP位址資料 { get; set; }
        public DbSet<junket> junkets { get; set; }
        public DbSet<junketItem> junketItems { get; set; }
        public DbSet<LeaveOffice> LeaveOffices { get; set; }
        public DbSet<LEX_SallyForth> LEX_SallyForth { get; set; }
        public DbSet<LEX_VAL_BAL> LEX_VAL_BAL { get; set; }
        public DbSet<Machinery> Machineries { get; set; }
        public DbSet<MachineryType> MachineryTypes { get; set; }
        public DbSet<Meet> Meets { get; set; }
        public DbSet<MeetItem> MeetItems { get; set; }
        public DbSet<MessageClass> MessageClasses { get; set; }
        public DbSet<MessageEmp> MessageEmps { get; set; }
        public DbSet<MessageRule> MessageRules { get; set; }
        public DbSet<NBCarry> NBCarries { get; set; }
        public DbSet<NBCarryType> NBCarryTypes { get; set; }
        public DbSet<NewEmp> NewEmps { get; set; }
        public DbSet<NewEmpBoss> NewEmpBosses { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NoCashFlow> NoCashFlows { get; set; }
        public DbSet<NtMd> NtMds { get; set; }
        public DbSet<OALT_FIELD_SIGN> OALT_FIELD_SIGN { get; set; }
        public DbSet<OALTcommon> OALTcommons { get; set; }
        public DbSet<OALTQ1> OALTQ1 { get; set; }
        public DbSet<OALTQ2> OALTQ2 { get; set; }
        public DbSet<OALTQ3> OALTQ3 { get; set; }
        public DbSet<OALTQ4> OALTQ4 { get; set; }
        public DbSet<OALTQ6> OALTQ6 { get; set; }
        public DbSet<OALTQ7> OALTQ7 { get; set; }
        public DbSet<OALTquoted> OALTquoteds { get; set; }
        public DbSet<OALTQution> OALTQutions { get; set; }
        public DbSet<OALTSrvMail> OALTSrvMails { get; set; }
        public DbSet<OALTSrvMailScr> OALTSrvMailScrs { get; set; }
        public DbSet<OALTteach> OALTteaches { get; set; }
        public DbSet<old_OTC_PROCED_BACK_ACT> old_OTC_PROCED_BACK_ACT { get; set; }
        public DbSet<old_OTC_PROCED_BACK_ERD> old_OTC_PROCED_BACK_ERD { get; set; }
        public DbSet<old_OTC_PROCED_DEPT_ERD> old_OTC_PROCED_DEPT_ERD { get; set; }
        public DbSet<ONESTOP> ONESTOPs { get; set; }
        public DbSet<ONESTOPScr> ONESTOPScrs { get; set; }
        public DbSet<ONESTOPType> ONESTOPTypes { get; set; }
        public DbSet<ONESTOPUNIT> ONESTOPUNITs { get; set; }
        public DbSet<ONESTOPUNITemp> ONESTOPUNITemps { get; set; }
        public DbSet<ORIX_SPEICAL> ORIX_SPEICAL { get; set; }
        public DbSet<ORIXAuthority> ORIXAuthorities { get; set; }
        public DbSet<OrixGift> OrixGifts { get; set; }
        public DbSet<OrixGiftScr> OrixGiftScrs { get; set; }
        public DbSet<OrixGiftType> OrixGiftTypes { get; set; }
        public DbSet<ORIXLVL> ORIXLVLs { get; set; }
        public DbSet<ORIXReceive> ORIXReceives { get; set; }
        public DbSet<ORIXSend> ORIXSends { get; set; }
        public DbSet<OTC_DOC_BR> OTC_DOC_BR { get; set; }
        public DbSet<OTC_FIELD_SIGN> OTC_FIELD_SIGN { get; set; }
        public DbSet<OTC_INT_APLY> OTC_INT_APLY { get; set; }
        public DbSet<OTC_INT_APLY_HOMENOTE> OTC_INT_APLY_HOMENOTE { get; set; }
        public DbSet<OTC_INT_FLOW> OTC_INT_FLOW { get; set; }
        public DbSet<OTC_PROCED_Absorb> OTC_PROCED_Absorb { get; set; }
        public DbSet<OTC_PROCED_APLY> OTC_PROCED_APLY { get; set; }
        public DbSet<OTC_PROCED_APLY_HOMENOTE> OTC_PROCED_APLY_HOMENOTE { get; set; }
        public DbSet<OTC_PROCED_APLY_LIST> OTC_PROCED_APLY_LIST { get; set; }
        public DbSet<OTC_PROCED_APRV> OTC_PROCED_APRV { get; set; }
        public DbSet<OTC_PROCED_APRV_T> OTC_PROCED_APRV_T { get; set; }
        public DbSet<OTC_PROCED_BACK_ACT> OTC_PROCED_BACK_ACT { get; set; }
        public DbSet<OTC_PROCED_BACK_ERD> OTC_PROCED_BACK_ERD { get; set; }
        public DbSet<OTC_PROCED_COLUMN> OTC_PROCED_COLUMN { get; set; }
        public DbSet<OTC_PROCED_Content> OTC_PROCED_Content { get; set; }
        public DbSet<OTC_PROCED_Content2> OTC_PROCED_Content2 { get; set; }
        public DbSet<OTC_PROCED_DEMERIT> OTC_PROCED_DEMERIT { get; set; }
        public DbSet<OTC_Proced_Demerit_Affirm> OTC_Proced_Demerit_Affirm { get; set; }
        public DbSet<OTC_PROCED_DEPT_ERD> OTC_PROCED_DEPT_ERD { get; set; }
        public DbSet<OTC_PROCED_DOC> OTC_PROCED_DOC { get; set; }
        public DbSet<OTC_PROCED_INVO> OTC_PROCED_INVO { get; set; }
        public DbSet<OTC_PROCED_LOSE> OTC_PROCED_LOSE { get; set; }
        public DbSet<OTC_PROCED_LVL> OTC_PROCED_LVL { get; set; }
        public DbSet<OTC_PROCED_MIS> OTC_PROCED_MIS { get; set; }
        public DbSet<OTC_PROCED_MIS_TYPE> OTC_PROCED_MIS_TYPE { get; set; }
        public DbSet<OTC_PROCED_NEW_APLYNO> OTC_PROCED_NEW_APLYNO { get; set; }
        public DbSet<OTC_PROCED_OALTADD> OTC_PROCED_OALTADD { get; set; }
        public DbSet<OTC_PROCED_OBJECT> OTC_PROCED_OBJECT { get; set; }
        public DbSet<OTC_PROCED_PAY> OTC_PROCED_PAY { get; set; }
        public DbSet<OTC_PROCED_SEND> OTC_PROCED_SEND { get; set; }
        public DbSet<OTC_PROCED_TYPE> OTC_PROCED_TYPE { get; set; }
        public DbSet<OTC_PROCED_UNITE> OTC_PROCED_UNITE { get; set; }
        public DbSet<PaperAply> PaperAplies { get; set; }
        public DbSet<PaperAplyScr> PaperAplyScrs { get; set; }
        public DbSet<PaperCTW> PaperCTWs { get; set; }
        public DbSet<PaperFolder> PaperFolders { get; set; }
        public DbSet<PaperItem> PaperItems { get; set; }
        public DbSet<PaperSelectAply> PaperSelectAplies { get; set; }
        public DbSet<PaperSelectT> PaperSelectTs { get; set; }
        public DbSet<PE_ReviewForm> PE_ReviewForm { get; set; }
        public DbSet<PostAgent> PostAgents { get; set; }
        public DbSet<Postal> Postals { get; set; }
        public DbSet<PROCED_CODE> PROCED_CODE { get; set; }
        public DbSet<PROCED_Deadline> PROCED_Deadline { get; set; }
        public DbSet<ProcedUnit> ProcedUnits { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProjectorDetail> ProjectorDetails { get; set; }
        public DbSet<ProjectorMain> ProjectorMains { get; set; }
        public DbSet<ProjectorType> ProjectorTypes { get; set; }
        public DbSet<ProocedUNIT> ProocedUNITs { get; set; }
        public DbSet<RecordDetail> RecordDetails { get; set; }
        public DbSet<RecordMain> RecordMains { get; set; }
        public DbSet<RecordType> RecordTypes { get; set; }
        public DbSet<Rentec> Rentecs { get; set; }
        public DbSet<RentecACH> RentecACHes { get; set; }
        public DbSet<RentecType> RentecTypes { get; set; }
        public DbSet<ReplyBook> ReplyBooks { get; set; }
        public DbSet<ResponsetType> ResponsetTypes { get; set; }
        public DbSet<SALE_APLY_AMOUNT> SALE_APLY_AMOUNT { get; set; }
        public DbSet<SALEDEPCU> SALEDEPCUS { get; set; }
        public DbSet<SALEDEPREC> SALEDEPRECs { get; set; }
        public DbSet<SALEDEPTYPE> SALEDEPTYPEs { get; set; }
        public DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public DbSet<ScheduleItem> ScheduleItems { get; set; }
        public DbSet<ScheduleMain> ScheduleMains { get; set; }
        public DbSet<ScheduleType> ScheduleTypes { get; set; }
        public DbSet<ScheduleView> ScheduleViews { get; set; }
        public DbSet<SecurityAgree> SecurityAgrees { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<ServiceMail> ServiceMails { get; set; }
        public DbSet<ServiceRMail> ServiceRMails { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<Shart_Amount> Shart_Amount { get; set; }
        public DbSet<Shart_AReporder> Shart_AReporder { get; set; }
        public DbSet<Shart_CAROrder> Shart_CAROrder { get; set; }
        public DbSet<Shart_Contract> Shart_Contract { get; set; }
        public DbSet<Shart_cost> Shart_cost { get; set; }
        public DbSet<Shart_Custom> Shart_Custom { get; set; }
        public DbSet<Shart_ETAGPay> Shart_ETAGPay { get; set; }
        public DbSet<Shart_Holiday> Shart_Holiday { get; set; }
        public DbSet<Shart_INVO> Shart_INVO { get; set; }
        public DbSet<Shart_licence> Shart_licence { get; set; }
        public DbSet<Shart_licenceDate> Shart_licenceDate { get; set; }
        public DbSet<Shart_licenceRed> Shart_licenceRed { get; set; }
        public DbSet<Shart_Order> Shart_Order { get; set; }
        public DbSet<Shart_OtherINV> Shart_OtherINV { get; set; }
        public DbSet<Shart_OtherSendPay> Shart_OtherSendPay { get; set; }
        public DbSet<Shart_RAmount> Shart_RAmount { get; set; }
        public DbSet<Shart_Reporder> Shart_Reporder { get; set; }
        public DbSet<Shart_ReporderList> Shart_ReporderList { get; set; }
        public DbSet<Shart_ReporderScr> Shart_ReporderScr { get; set; }
        public DbSet<Shart_ReporderSeat> Shart_ReporderSeat { get; set; }
        public DbSet<Shart_RINVO> Shart_RINVO { get; set; }
        public DbSet<Shart_RorderT> Shart_RorderT { get; set; }
        public DbSet<Shart_RVend> Shart_RVend { get; set; }
        public DbSet<Shart_Self> Shart_Self { get; set; }
        public DbSet<Shart_SendCar> Shart_SendCar { get; set; }
        public DbSet<Shopping> Shoppings { get; set; }
        public DbSet<Sign_AgreeBook> Sign_AgreeBook { get; set; }
        public DbSet<Special> Specials { get; set; }
        public DbSet<SpecialMail> SpecialMails { get; set; }
        public DbSet<SpecialType> SpecialTypes { get; set; }
        public DbSet<SrtbivrTMail> SrtbivrTMails { get; set; }
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<USBCarry> USBCarries { get; set; }
        public DbSet<USBDetail> USBDetails { get; set; }
        public DbSet<USBMain> USBMains { get; set; }
        public DbSet<USBType> USBTypes { get; set; }
        public DbSet<VoteDetail> VoteDetails { get; set; }
        public DbSet<VoteLog> VoteLogs { get; set; }
        public DbSet<VoteMain> VoteMains { get; set; }
        public DbSet<WB6101> WB6101 { get; set; }
        public DbSet<WB6621> WB6621 { get; set; }
        public DbSet<WB6621_APRV> WB6621_APRV { get; set; }
        public DbSet<WB6621type> WB6621type { get; set; }
        public DbSet<work_day> work_day { get; set; }
        public DbSet<WorkClass> WorkClasses { get; set; }
        public DbSet<WorkEmp> WorkEmps { get; set; }
        public DbSet<WorkRecord> WorkRecords { get; set; }
        public DbSet<WorkState> WorkStates { get; set; }
        public DbSet<WorkView> WorkViews { get; set; }
        public DbSet<YearHoliday> YearHolidays { get; set; }
        public DbSet<員工> 員工 { get; set; }
        public DbSet<員工_950310> 員工_950310 { get; set; }
        public DbSet<員工_970508> 員工_970508 { get; set; }
        public DbSet<員工_981006> 員工_981006 { get; set; }
        public DbSet<郵件帳號_> 郵件帳號_ { get; set; }
    
        public virtual ObjectResult<s_ConditionItems_Result> s_ConditionItems(string pTypeField, string pListName, string pSpaceRow, string pShowCode)
        {
            var pTypeFieldParameter = pTypeField != null ?
                new ObjectParameter("PTypeField", pTypeField) :
                new ObjectParameter("PTypeField", typeof(string));
    
            var pListNameParameter = pListName != null ?
                new ObjectParameter("PListName", pListName) :
                new ObjectParameter("PListName", typeof(string));
    
            var pSpaceRowParameter = pSpaceRow != null ?
                new ObjectParameter("PSpaceRow", pSpaceRow) :
                new ObjectParameter("PSpaceRow", typeof(string));
    
            var pShowCodeParameter = pShowCode != null ?
                new ObjectParameter("PShowCode", pShowCode) :
                new ObjectParameter("PShowCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<s_ConditionItems_Result>("s_ConditionItems", pTypeFieldParameter, pListNameParameter, pSpaceRowParameter, pShowCodeParameter);
        }
    
        public virtual ObjectResult<s_GetNumber_Result> s_GetNumber(string pCode, string pKind, string pYear, string pMonth)
        {
            var pCodeParameter = pCode != null ?
                new ObjectParameter("PCode", pCode) :
                new ObjectParameter("PCode", typeof(string));
    
            var pKindParameter = pKind != null ?
                new ObjectParameter("PKind", pKind) :
                new ObjectParameter("PKind", typeof(string));
    
            var pYearParameter = pYear != null ?
                new ObjectParameter("PYear", pYear) :
                new ObjectParameter("PYear", typeof(string));
    
            var pMonthParameter = pMonth != null ?
                new ObjectParameter("PMonth", pMonth) :
                new ObjectParameter("PMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<s_GetNumber_Result>("s_GetNumber", pCodeParameter, pKindParameter, pYearParameter, pMonthParameter);
        }
    
        public virtual ObjectResult<s_WE020_Grid_Result> s_WE020_Grid(string pAPLY_NO, string pCONTACT, string pCUST_NO, string pIS_SEARCH, string pCUST_NAME, string pFRC_CODE, string pFRC_NAME, string pCTAC_TEL, string pRECV_NAME, string pSEND_ADDR, string pADDR, string pPROD_NAME, string pMAC_NO, string pAPLY_DATE_S, string pAPLY_DATE_E, string pEMP_CODE, string pCUR_STS, string pDEPT_CODE, string pCASE_SOUR, string pIS_DEL, string pINV_NO, string pCAR_NO)
        {
            var pAPLY_NOParameter = pAPLY_NO != null ?
                new ObjectParameter("PAPLY_NO", pAPLY_NO) :
                new ObjectParameter("PAPLY_NO", typeof(string));
    
            var pCONTACTParameter = pCONTACT != null ?
                new ObjectParameter("PCONTACT", pCONTACT) :
                new ObjectParameter("PCONTACT", typeof(string));
    
            var pCUST_NOParameter = pCUST_NO != null ?
                new ObjectParameter("PCUST_NO", pCUST_NO) :
                new ObjectParameter("PCUST_NO", typeof(string));
    
            var pIS_SEARCHParameter = pIS_SEARCH != null ?
                new ObjectParameter("PIS_SEARCH", pIS_SEARCH) :
                new ObjectParameter("PIS_SEARCH", typeof(string));
    
            var pCUST_NAMEParameter = pCUST_NAME != null ?
                new ObjectParameter("PCUST_NAME", pCUST_NAME) :
                new ObjectParameter("PCUST_NAME", typeof(string));
    
            var pFRC_CODEParameter = pFRC_CODE != null ?
                new ObjectParameter("PFRC_CODE", pFRC_CODE) :
                new ObjectParameter("PFRC_CODE", typeof(string));
    
            var pFRC_NAMEParameter = pFRC_NAME != null ?
                new ObjectParameter("PFRC_NAME", pFRC_NAME) :
                new ObjectParameter("PFRC_NAME", typeof(string));
    
            var pCTAC_TELParameter = pCTAC_TEL != null ?
                new ObjectParameter("PCTAC_TEL", pCTAC_TEL) :
                new ObjectParameter("PCTAC_TEL", typeof(string));
    
            var pRECV_NAMEParameter = pRECV_NAME != null ?
                new ObjectParameter("PRECV_NAME", pRECV_NAME) :
                new ObjectParameter("PRECV_NAME", typeof(string));
    
            var pSEND_ADDRParameter = pSEND_ADDR != null ?
                new ObjectParameter("PSEND_ADDR", pSEND_ADDR) :
                new ObjectParameter("PSEND_ADDR", typeof(string));
    
            var pADDRParameter = pADDR != null ?
                new ObjectParameter("PADDR", pADDR) :
                new ObjectParameter("PADDR", typeof(string));
    
            var pPROD_NAMEParameter = pPROD_NAME != null ?
                new ObjectParameter("PPROD_NAME", pPROD_NAME) :
                new ObjectParameter("PPROD_NAME", typeof(string));
    
            var pMAC_NOParameter = pMAC_NO != null ?
                new ObjectParameter("PMAC_NO", pMAC_NO) :
                new ObjectParameter("PMAC_NO", typeof(string));
    
            var pAPLY_DATE_SParameter = pAPLY_DATE_S != null ?
                new ObjectParameter("PAPLY_DATE_S", pAPLY_DATE_S) :
                new ObjectParameter("PAPLY_DATE_S", typeof(string));
    
            var pAPLY_DATE_EParameter = pAPLY_DATE_E != null ?
                new ObjectParameter("PAPLY_DATE_E", pAPLY_DATE_E) :
                new ObjectParameter("PAPLY_DATE_E", typeof(string));
    
            var pEMP_CODEParameter = pEMP_CODE != null ?
                new ObjectParameter("PEMP_CODE", pEMP_CODE) :
                new ObjectParameter("PEMP_CODE", typeof(string));
    
            var pCUR_STSParameter = pCUR_STS != null ?
                new ObjectParameter("PCUR_STS", pCUR_STS) :
                new ObjectParameter("PCUR_STS", typeof(string));
    
            var pDEPT_CODEParameter = pDEPT_CODE != null ?
                new ObjectParameter("PDEPT_CODE", pDEPT_CODE) :
                new ObjectParameter("PDEPT_CODE", typeof(string));
    
            var pCASE_SOURParameter = pCASE_SOUR != null ?
                new ObjectParameter("PCASE_SOUR", pCASE_SOUR) :
                new ObjectParameter("PCASE_SOUR", typeof(string));
    
            var pIS_DELParameter = pIS_DEL != null ?
                new ObjectParameter("PIS_DEL", pIS_DEL) :
                new ObjectParameter("PIS_DEL", typeof(string));
    
            var pINV_NOParameter = pINV_NO != null ?
                new ObjectParameter("PINV_NO", pINV_NO) :
                new ObjectParameter("PINV_NO", typeof(string));
    
            var pCAR_NOParameter = pCAR_NO != null ?
                new ObjectParameter("PCAR_NO", pCAR_NO) :
                new ObjectParameter("PCAR_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<s_WE020_Grid_Result>("s_WE020_Grid", pAPLY_NOParameter, pCONTACTParameter, pCUST_NOParameter, pIS_SEARCHParameter, pCUST_NAMEParameter, pFRC_CODEParameter, pFRC_NAMEParameter, pCTAC_TELParameter, pRECV_NAMEParameter, pSEND_ADDRParameter, pADDRParameter, pPROD_NAMEParameter, pMAC_NOParameter, pAPLY_DATE_SParameter, pAPLY_DATE_EParameter, pEMP_CODEParameter, pCUR_STSParameter, pDEPT_CODEParameter, pCASE_SOURParameter, pIS_DELParameter, pINV_NOParameter, pCAR_NOParameter);
        }
    
        public virtual ObjectResult<s_Emp_Class_Result> s_Emp_Class(string pEmp, string pAply_No, string pDept_Code, string pEmp_Code)
        {
            var pEmpParameter = pEmp != null ?
                new ObjectParameter("PEmp", pEmp) :
                new ObjectParameter("PEmp", typeof(string));
    
            var pAply_NoParameter = pAply_No != null ?
                new ObjectParameter("PAply_No", pAply_No) :
                new ObjectParameter("PAply_No", typeof(string));
    
            var pDept_CodeParameter = pDept_Code != null ?
                new ObjectParameter("PDept_Code", pDept_Code) :
                new ObjectParameter("PDept_Code", typeof(string));
    
            var pEmp_CodeParameter = pEmp_Code != null ?
                new ObjectParameter("PEmp_Code", pEmp_Code) :
                new ObjectParameter("PEmp_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<s_Emp_Class_Result>("s_Emp_Class", pEmpParameter, pAply_NoParameter, pDept_CodeParameter, pEmp_CodeParameter);
        }
    }
}
