//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORIX_SPEICAL
    {
        public int SEQ { get; set; }
        public Nullable<System.DateTime> APLY_DATE { get; set; }
        public string APLY_PERSON { get; set; }
        public string RECVER { get; set; }
        public string BACK_REASON { get; set; }
        public string UPPER_BOSS { get; set; }
        public string MODIFY_ID { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Crd_Del { get; set; }
        public Nullable<System.DateTime> AtmBossD { get; set; }
    }
}
