//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORM02
    {
        public string UNIQ_KEY { get; set; }
        public string CORP_NO { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_KIND { get; set; }
        public string ORDER_DATE { get; set; }
        public string DEPT_NO { get; set; }
        public string EMP_NO { get; set; }
        public string FOR_CODE { get; set; }
        public string CUST_NO { get; set; }
        public string CUST_ORDER { get; set; }
        public decimal ORDER_TOT_AMT { get; set; }
        public Nullable<decimal> ORDER_TOT_AMT_NT { get; set; }
        public Nullable<decimal> TAX_AMT { get; set; }
        public Nullable<decimal> INVO_AMT { get; set; }
        public string TAX_CODE { get; set; }
        public string INVO_KIND { get; set; }
        public string ADDR_CONT { get; set; }
        public string TRAN_CODE { get; set; }
        public string TRADE_COND { get; set; }
        public string PAY_WAY { get; set; }
        public Nullable<short> PAY_DAYS { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<double> CURR_RATE { get; set; }
        public Nullable<double> MAX_QTY { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public string CONT_NO { get; set; }
        public string CONF_CODE { get; set; }
        public string SIMUL_YN { get; set; }
        public string FINAL_CODE { get; set; }
        public string AUDIT_CODE { get; set; }
        public string REMK { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string ADD_OR_DEL { get; set; }
        public string AUDIT_ID { get; set; }
        public string AUDIT_DATE { get; set; }
    }
}
