//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORM03
    {
        public string UNIQ_KEY { get; set; }
        public string CORP_NO { get; set; }
        public string ORDER_ADJ_NO { get; set; }
        public string ORDER_ADJ_DATE { get; set; }
        public string ORDER_ADJ_KIND { get; set; }
        public string ORDER_NO { get; set; }
        public string DEPT_NO { get; set; }
        public string EMP_NO { get; set; }
        public string CUST_NO { get; set; }
        public decimal ORI_ORDER_TOT_AMT { get; set; }
        public Nullable<decimal> ORI_ORDER_TOT_AMT_NT { get; set; }
        public decimal ORDER_TOT_AMT { get; set; }
        public Nullable<decimal> ORDER_TOT_AMT_NT { get; set; }
        public decimal FIN_ORDER_TOT_AMT { get; set; }
        public Nullable<decimal> FIN_ORDER_TOT_AMT_NT { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<double> CURR_RATE { get; set; }
        public string AUDIT_CODE { get; set; }
        public string REMK { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string ADD_OR_DEL { get; set; }
    }
}
