//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORT05
    {
        public string UNIQ_KEY { get; set; }
        public string CORP_NO { get; set; }
        public string ORDER_ADJ_NO { get; set; }
        public string ORDER_ADJ_KIND { get; set; }
        public string ORDER_ADJ_DATE { get; set; }
        public string CUST_NO { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<double> CURR_RATE { get; set; }
        public string DATA_SEQ { get; set; }
        public string ORDER_NO { get; set; }
        public string ORT03_UNIQ_KEY { get; set; }
        public string INDE_NO { get; set; }
        public string PROD_NO { get; set; }
        public string SIZE { get; set; }
        public string COLOR { get; set; }
        public Nullable<double> ORI_QTY_1 { get; set; }
        public Nullable<double> ORI_QTY_2 { get; set; }
        public Nullable<double> ORI_QTY_3 { get; set; }
        public Nullable<double> ORI_COUNT_QTY { get; set; }
        public Nullable<double> ORI_COUNT_RATE { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_1 { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_2 { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_3 { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_1 { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_2 { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_3 { get; set; }
        public Nullable<decimal> ORI_AMT { get; set; }
        public Nullable<decimal> ORI_AMT_NT { get; set; }
        public Nullable<decimal> ORI_ORDER_AMT { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_1_NT { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_2_NT { get; set; }
        public Nullable<decimal> ORI_UNIT_PRICE_3_NT { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_1_NT { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_2_NT { get; set; }
        public Nullable<decimal> ORI_ORDER_PRICE_3_NT { get; set; }
        public Nullable<decimal> ORI_ORDER_AMT_NT { get; set; }
        public string ADJ_CODE { get; set; }
        public Nullable<double> QTY_1 { get; set; }
        public Nullable<double> QTY_2 { get; set; }
        public Nullable<double> QTY_3 { get; set; }
        public Nullable<double> COUNT_QTY { get; set; }
        public Nullable<double> COUNT_RATE { get; set; }
        public Nullable<decimal> UNIT_PRICE_1 { get; set; }
        public Nullable<decimal> UNIT_PRICE_2 { get; set; }
        public Nullable<decimal> UNIT_PRICE_3 { get; set; }
        public Nullable<decimal> ORDER_PRICE_1 { get; set; }
        public Nullable<decimal> ORDER_PRICE_2 { get; set; }
        public Nullable<decimal> ORDER_PRICE_3 { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<decimal> AMT_NT { get; set; }
        public Nullable<decimal> ORDER_AMT { get; set; }
        public Nullable<decimal> UNIT_PRICE_1_NT { get; set; }
        public Nullable<decimal> UNIT_PRICE_2_NT { get; set; }
        public Nullable<decimal> UNIT_PRICE_3_NT { get; set; }
        public Nullable<decimal> ORDER_PRICE_1_NT { get; set; }
        public Nullable<decimal> ORDER_PRICE_2_NT { get; set; }
        public Nullable<decimal> ORDER_PRICE_3_NT { get; set; }
        public Nullable<decimal> ORDER_AMT_NT { get; set; }
        public Nullable<double> FIN_QTY_1 { get; set; }
        public Nullable<double> FIN_QTY_2 { get; set; }
        public Nullable<double> FIN_QTY_3 { get; set; }
        public Nullable<double> FIN_COUNT_QTY { get; set; }
        public Nullable<double> FIN_COUNT_RATE { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_1 { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_2 { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_3 { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_1 { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_2 { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_3 { get; set; }
        public Nullable<decimal> FIN_AMT { get; set; }
        public Nullable<decimal> FIN_AMT_NT { get; set; }
        public Nullable<decimal> FIN_ORDER_AMT { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_1_NT { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_2_NT { get; set; }
        public Nullable<decimal> FIN_UNIT_PRICE_3_NT { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_1_NT { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_2_NT { get; set; }
        public Nullable<decimal> FIN_ORDER_PRICE_3_NT { get; set; }
        public Nullable<decimal> FIN_ORDER_AMT_NT { get; set; }
        public string STORE_NO { get; set; }
        public string AUDIT_CODE { get; set; }
        public string REMK { get; set; }
        public string FIELD_1 { get; set; }
        public string FIELD_2 { get; set; }
        public string FIELD_3 { get; set; }
        public string FIELD_4 { get; set; }
        public string FIELD_5 { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string ADD_OR_DEL { get; set; }
    }
}
