//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_APLY_HOMENOTE
    {
        public string Proced_aply_no { get; set; }
        public string ord_Class { get; set; }
        public string Proced_aprv_emp { get; set; }
        public string aply_com { get; set; }
        public Nullable<int> ord_no { get; set; }
        public string Boss_sign { get; set; }
        public int Proced_Num { get; set; }
        public string Dept { get; set; }
        public string Proced_aprv_lvl { get; set; }
        public Nullable<int> Over_Day { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public string NewAplyNo { get; set; }
    }
}
