//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_PAY
    {
        public string PROCED_APLY_NO { get; set; }
        public string APLY_COM { get; set; }
        public Nullable<int> A_NO_RENT { get; set; }
        public Nullable<int> A_NO_FINE { get; set; }
        public Nullable<int> A_NO_SELF { get; set; }
        public Nullable<int> A_NO_FUEL { get; set; }
        public Nullable<int> A_NO_FORMAL { get; set; }
        public string A_SCR { get; set; }
        public Nullable<int> A_SEC_SCRAP { get; set; }
        public Nullable<int> A_SEC_LOSS { get; set; }
        public Nullable<int> A_MIDDLE_AGES { get; set; }
        public Nullable<int> A_EARNEST { get; set; }
        public string MAIN { get; set; }
        public string Content { get; set; }
        public string A_rename_new { get; set; }
        public string A_rename_unite { get; set; }
        public string A_rename_address { get; set; }
        public string A_rename_agent { get; set; }
        public string A_rename_date { get; set; }
        public string A_rename_credit { get; set; }
        public string A_rename_unpaid { get; set; }
        public string A_rename_refund { get; set; }
        public string A_tenant { get; set; }
        public string A_payment_cycle { get; set; }
        public string A_payment_time { get; set; }
        public string A_change_payment { get; set; }
        public string A_payment_way { get; set; }
        public string A_first_payment { get; set; }
        public Nullable<int> A_arrear_days { get; set; }
        public Nullable<double> A_irr { get; set; }
        public string A_car_insurance { get; set; }
        public string A_burglary_insurance { get; set; }
        public string A_third_insurance { get; set; }
        public string A_third_wealth { get; set; }
        public string A_drink_excess { get; set; }
        public string A_third_poilot { get; set; }
        public string A_fare_insurance { get; set; }
        public string A_exit_substitute { get; set; }
        public string A_burglary_substitute { get; set; }
        public string A_overflow { get; set; }
        public string A_spare_part { get; set; }
        public string A_typhoon { get; set; }
        public string A_strong_drink { get; set; }
        public string A_other { get; set; }
        public Nullable<int> A_fees { get; set; }
        public Nullable<int> A_limit_mileage { get; set; }
        public Nullable<double> A_add_mileage { get; set; }
        public string A_fittings { get; set; }
        public Nullable<int> A_fittings_price { get; set; }
        public string A_scur_name { get; set; }
        public string A_scur_birthday { get; set; }
        public string A_scur_id { get; set; }
        public string A_scur_address { get; set; }
        public string A_car_deal { get; set; }
        public string A_car_return { get; set; }
        public string A_law_name { get; set; }
        public string A_tel { get; set; }
        public string A_deal_way { get; set; }
        public string A_law_flow { get; set; }
        public Nullable<int> A_capital { get; set; }
        public Nullable<int> A_overdue_annul { get; set; }
        public Nullable<int> A_twn { get; set; }
        public Nullable<int> A_twn_loss { get; set; }
        public string A_storng_card { get; set; }
        public Nullable<int> A_re_mileage { get; set; }
        public Nullable<int> A_salse { get; set; }
        public Nullable<int> A_ACC_FINE { get; set; }
        public Nullable<int> A_acc_mailage { get; set; }
        public string A_Business_Address { get; set; }
        public string A_Case_Address { get; set; }
        public string A_Liaison { get; set; }
        public string A_user_name { get; set; }
        public string A_Punish_Address { get; set; }
        public string A_invo_address { get; set; }
        public string A_receiver { get; set; }
        public string A_change_class { get; set; }
        public Nullable<int> A_OTC_Contract { get; set; }
        public Nullable<int> A_FORMAL_Day { get; set; }
        public string A_recover_date { get; set; }
        public string A_pay_cash { get; set; }
        public Nullable<int> A_red { get; set; }
        public Nullable<int> A_Reparation { get; set; }
        public string A_law_date { get; set; }
        public Nullable<int> A_suffer_insurance { get; set; }
        public string A_EndCause { get; set; }
        public string A_EndScr { get; set; }
        public Nullable<int> A_DigestMoney { get; set; }
        public string A_Insurance_Content { get; set; }
        public string A_ChangeDate_Start { get; set; }
        public string A_ChangeDate_Stop { get; set; }
        public Nullable<int> A_Change_InsuranceMoney { get; set; }
        public Nullable<int> A_rent { get; set; }
        public string A_Tease_Start { get; set; }
        public string A_Tease_Stop { get; set; }
        public Nullable<double> A_Total_Day { get; set; }
        public string A_Custom_Name { get; set; }
        public string A_Custom_Unite { get; set; }
        public string A_Storng_Ins { get; set; }
        public string A_Strong_InsYN { get; set; }
        public string A_Car_Ins { get; set; }
        public string A_Car_InsYN { get; set; }
        public string A_BurglaryIns { get; set; }
        public string A_BurglaryInsYN { get; set; }
        public string A_Third_Ins { get; set; }
        public string A_Third_InsYN { get; set; }
        public string A_Third_WealthYN { get; set; }
        public string A_Third_PolotYN { get; set; }
        public string A_Fare_Ins { get; set; }
        public string A_Fare_InsYN { get; set; }
        public Nullable<int> A_Adv_Keep { get; set; }
        public Nullable<int> A_Adv_Insurance { get; set; }
        public Nullable<int> A_Adv_Depreciation { get; set; }
        public Nullable<int> A_Adv_Oil { get; set; }
        public Nullable<int> A_Adv_Clean { get; set; }
        public Nullable<int> A_Adv_Total { get; set; }
        public string A_OutLicenceNo { get; set; }
        public string A_Factory { get; set; }
        public string A_Mode { get; set; }
        public Nullable<int> A_Exhaust { get; set; }
        public string A_Year { get; set; }
        public string A_Carmaster { get; set; }
        public string A_StartDate { get; set; }
        public string A_StopDate { get; set; }
        public Nullable<int> A_EveryDayRent { get; set; }
        public Nullable<int> A_Smileage { get; set; }
        public Nullable<int> A_Emileage { get; set; }
        public string A_RentType { get; set; }
        public string A_CauseScr { get; set; }
        public string A_Other_party { get; set; }
        public string A_Pro_Name { get; set; }
        public string A_Pro_ID { get; set; }
        public string A_establish { get; set; }
        public string A_No_establish { get; set; }
        public string A_Law { get; set; }
        public string A_annex { get; set; }
        public string A_Pro_Name2 { get; set; }
        public string A_Pro_Name3 { get; set; }
        public string A_Pro_ID2 { get; set; }
        public string A_Pro_ID3 { get; set; }
    }
}
