//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_CASE_BASE_REM
    {
        public string APLY_NO { get; set; }
        public string SING_CON_DATE { get; set; }
        public string PREDICT_LEASE_DATE { get; set; }
        public string PREDICT_PAY_DATE { get; set; }
        public string CUS_PAY_WAY { get; set; }
        public string DIS_CONTRACT { get; set; }
        public string MEM { get; set; }
        public string SUPPLY_PAY_WAY { get; set; }
        public string PAY_SUPPLY_DUE_DATE { get; set; }
        public Nullable<decimal> PAY_AUPPY_AMT { get; set; }
        public string MEM2 { get; set; }
        public string SEC_RENT_REM { get; set; }
        public string selfuse { get; set; }
        public string supplybuy { get; set; }
        public string EASYCASE { get; set; }
        public string confirm_25to31 { get; set; }
        public string first_pay_date { get; set; }
        public string pay_supply_tt_acc { get; set; }
        public string IF_CON { get; set; }
        public string CON_MAN { get; set; }
        public string CON_DATE { get; set; }
        public string OTC_CON_MAN { get; set; }
        public string ACC_MEM { get; set; }
        public string REMARK2 { get; set; }
        public string CHM_YN { get; set; }
        public string REM_ORDER { get; set; }
        public string REM_CUST_CONTRACT { get; set; }
        public string REM_CUST_AGREEMENT { get; set; }
        public string REM_CUST_INV { get; set; }
        public string REM_CUST_OTH { get; set; }
        public string REM_CUST_OTH_DESC { get; set; }
        public string REM_FRC_CONTRACT { get; set; }
        public string REM_FRC_COOPAGREEMENT { get; set; }
        public string REM_FRC_AGREEMENT { get; set; }
        public string REM_FRC_INV { get; set; }
        public string REM_FRC_OTH { get; set; }
        public string REM_FRC_OTH_DESC { get; set; }
        public string REM_FRC_ZEOX { get; set; }
        public string Add_User { get; set; }
        public string Add_Date { get; set; }
        public string Upd_User { get; set; }
        public string Upd_Date { get; set; }
        public string CRD_CON_DATE { get; set; }
    }
}
