//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_APLY
    {
        public string PROCED_APLY_NO { get; set; }
        public string APLY_DATE { get; set; }
        public string APLY_PERSON { get; set; }
        public string DEPT { get; set; }
        public string NOTE { get; set; }
        public string PROCED_CON { get; set; }
        public string APRV_CLASS { get; set; }
        public string Aply_no { get; set; }
        public string licence_no { get; set; }
        public string con_no { get; set; }
        public Nullable<int> pay_mm { get; set; }
        public Nullable<int> no_mm { get; set; }
        public Nullable<int> Overdue_State { get; set; }
        public string PROCED_FILE { get; set; }
        public string lvl_Renew { get; set; }
        public Nullable<System.DateTime> lvl_Update { get; set; }
        public string RE_name { get; set; }
        public Nullable<System.DateTime> RE_update { get; set; }
        public string assistant { get; set; }
        public string APLY_COM { get; set; }
        public string ord_class { get; set; }
        public string trn_no { get; set; }
        public string Cust_no { get; set; }
        public string Cust_Name { get; set; }
        public string Acc_File { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<System.DateTime> Acc_Date { get; set; }
        public string Cen_File { get; set; }
        public string Cen_Name { get; set; }
        public Nullable<System.DateTime> Cen_Date { get; set; }
        public string VP_Name { get; set; }
        public Nullable<System.DateTime> VP_Date { get; set; }
        public string VP_File { get; set; }
        public string Lex_File { get; set; }
        public string Lex_Name { get; set; }
        public Nullable<System.DateTime> Lex_Date { get; set; }
        public string OALT_30Day { get; set; }
    }
}
