//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_CUSTINCOME
    {
        public string CUST_NO { get; set; }
        public string CUST_YEAR { get; set; }
        public Nullable<int> CUST_INCOME { get; set; }
        public Nullable<int> COP_UTAX_MO { get; set; }
        public Nullable<int> COP_EMP_NUM { get; set; }
    }
}
