//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_PROCED_Content2
    {
        public string PROCED_APLY_NO { get; set; }
        public string B_Obj_Back { get; set; }
        public string B_LossMoney { get; set; }
        public string B_pay_Custom { get; set; }
        public string B_FeeINV { get; set; }
        public string B_VP_Salse { get; set; }
        public string B_VP_Sell { get; set; }
        public string B_Obj_salse { get; set; }
        public string B_Sing_INV { get; set; }
        public string B_change_month { get; set; }
        public Nullable<int> B_INV_Stop { get; set; }
        public Nullable<int> B_Cut_OFF { get; set; }
        public Nullable<int> B_Expect { get; set; }
        public string B_INV_open { get; set; }
        public string B_ReturnTime { get; set; }
        public Nullable<int> B_Triplicate { get; set; }
        public string B_return_INV { get; set; }
        public string B_Back_INVDate { get; set; }
        public string B_Back_INVPresent { get; set; }
        public string B_Stop_Cause { get; set; }
        public Nullable<int> B_Stop_Ctpaytrm { get; set; }
        public string B_Stop_Month { get; set; }
        public string B_RE_Cause { get; set; }
        public Nullable<int> B_RE_Ctpaytrm { get; set; }
        public Nullable<int> B_RE_Ectpaytrm { get; set; }
        public string B_Renew_Ctpaytrm { get; set; }
        public string B_Renew_Month { get; set; }
        public string B_SignNum { get; set; }
        public string B_Other { get; set; }
        public string B_Bstartdate { get; set; }
        public string B_Astartdate { get; set; }
        public Nullable<int> B_Stop_Time { get; set; }
        public string B_Compose { get; set; }
        public string B_VPScr { get; set; }
        public Nullable<int> B_RE_Time { get; set; }
        public string B_Sign_Close { get; set; }
        public string B_Absorb { get; set; }
        public Nullable<int> B_AbsorbTerm { get; set; }
        public string B_ReINV_APLYNO { get; set; }
        public string B_StopINV_AplyNo1 { get; set; }
        public string B_StopINV_AplyNo2 { get; set; }
        public string B_StopINV_AplyNo3 { get; set; }
        public string B_DurableYear { get; set; }
        public Nullable<int> B_Gratis_Month { get; set; }
        public string B_Gratis_Date { get; set; }
        public string B_Usable_Date { get; set; }
        public Nullable<double> B_Buy_SaleMoney { get; set; }
        public string B_Old_SaleYN { get; set; }
        public string B_DINVSend { get; set; }
        public string B_DFutureDate { get; set; }
        public string B_DAPayDate { get; set; }
        public string B_DPayOK { get; set; }
        public string B_DINV_open { get; set; }
        public string B_cancel_YN { get; set; }
        public string B_oldsaleINV { get; set; }
        public Nullable<double> B_INVcancel_money { get; set; }
        public Nullable<double> B_Continue_OtherIncome { get; set; }
        public string B_Rent_Pay { get; set; }
        public string B_NewCase { get; set; }
        public string B_EXEdate { get; set; }
        public string B_Newaplyno { get; set; }
        public Nullable<double> B_NewTime { get; set; }
        public string B_NewStartDate { get; set; }
        public string B_cancel_Date { get; set; }
        public Nullable<double> B_Contract { get; set; }
        public Nullable<double> B_TR { get; set; }
        public string B_Tol_Contract { get; set; }
        public string B_Follow_money { get; set; }
        public string B_PayCustom { get; set; }
        public Nullable<double> B_PayAllINV { get; set; }
        public string B_PRVDate { get; set; }
        public Nullable<int> B_Tol_time { get; set; }
        public string B_Insurance_Com { get; set; }
        public string B_lose_time { get; set; }
        public string B_lose_month { get; set; }
        public string B_lose_open { get; set; }
        public string B_lose_INVopen { get; set; }
        public string B_lose_YN { get; set; }
        public Nullable<double> B_RTax { get; set; }
        public string B_RWay { get; set; }
        public string B_RStages { get; set; }
        public string B_RCheq_No { get; set; }
        public Nullable<double> B_RMoney { get; set; }
        public string B_NewCaseNum { get; set; }
        public string B_LendDate { get; set; }
        public Nullable<double> B_salse_Bus_new { get; set; }
        public string B_salse_proced_aply_no { get; set; }
        public string B_salse_Cause { get; set; }
        public string B_salse_INVODate { get; set; }
        public string B_salse_INVOOpen { get; set; }
        public string B_INVR_Date { get; set; }
        public Nullable<double> B_salse_Money { get; set; }
        public string B_Count_Money { get; set; }
        public string B_Bus_proced_aply_no { get; set; }
        public Nullable<double> B_OutScrap { get; set; }
        public string B_usance { get; set; }
        public string B_ProdName { get; set; }
        public string B_MacNo { get; set; }
        public string B_LossAddr { get; set; }
        public string B_ProcedNoB { get; set; }
        public string B_Ind { get; set; }
        public string B_OTIDate { get; set; }
        public string B_DocName { get; set; }
        public string B_DocScr { get; set; }
        public string B_DocClass { get; set; }
        public string B_WaitINV { get; set; }
        public string B_Doc1 { get; set; }
        public string B_Doc2 { get; set; }
        public string B_Doc3 { get; set; }
        public string B_Sign_Date { get; set; }
        public string B_Eff_Date { get; set; }
        public string B_CON_DATE_TO { get; set; }
        public string B_End_Note { get; set; }
        public string B_PACT_no { get; set; }
        public string B_PACT_Name { get; set; }
        public string B_OTC { get; set; }
        public string B_OALT { get; set; }
        public string B_OAMC { get; set; }
        public string B_OTI { get; set; }
        public string B_OTLI { get; set; }
        public string B_Secret_Promise { get; set; }
        public string B_Doc_Return { get; set; }
        public string B_Profit_PACT { get; set; }
        public string B_SPEC_PACT { get; set; }
        public Nullable<double> B_salse_MoneyD { get; set; }
        public string B_OEC { get; set; }
        public string B_SPC { get; set; }
        public string B_Resist { get; set; }
        public Nullable<double> B_old_Aply_Hire { get; set; }
    }
}
