//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTC_DOC_BR
    {
        public string SHEET_NO { get; set; }
        public string ATCH_CODE { get; set; }
        public Nullable<int> RIGHT_QTY { get; set; }
        public string APLY_PERSON { get; set; }
        public Nullable<double> OVER_DAY { get; set; }
        public string P_RETURN_DATE { get; set; }
        public string APLY_NO { get; set; }
        public Nullable<int> COPY_QTY { get; set; }
        public string B_Date { get; set; }
        public string CON_NO { get; set; }
        public string Cust_Sname { get; set; }
        public string Aply_Date { get; set; }
        public string Dept_Code { get; set; }
        public string Cust_no { get; set; }
        public string B_PERSON { get; set; }
    }
}
