//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperAply
    {
        public string Trn_No { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Add_Name { get; set; }
        public string Corp_No { get; set; }
        public string Floor { get; set; }
        public string Crd_STS { get; set; }
        public string Case_YN { get; set; }
        public string Parpose { get; set; }
        public string Void_Name { get; set; }
        public Nullable<System.DateTime> Void_Date { get; set; }
        public string UPPER_BOSS { get; set; }
        public Nullable<System.DateTime> BOSS_DATE { get; set; }
        public string Paper_Rname { get; set; }
        public Nullable<System.DateTime> Paper_Rdate { get; set; }
    }
}
