//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperAplyScr
    {
        public string Trn_No { get; set; }
        public string Box_Num { get; set; }
        public string App_Item { get; set; }
        public string Proc_Emp { get; set; }
        public Nullable<System.DateTime> Proc_Date { get; set; }
        public Nullable<System.DateTime> M_OutDate { get; set; }
        public string Box_NumS { get; set; }
        public string Box_NumE { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> FARE_APLY_QTY { get; set; }
    }
}
