//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_ReviewForm
    {
        public string FARE_APLY_NO { get; set; }
        public string Corp_Name { get; set; }
        public string Trade { get; set; }
        public string Create_AO { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Sketch { get; set; }
        public string Target1 { get; set; }
        public string Target2 { get; set; }
        public string Target3 { get; set; }
        public string Target4 { get; set; }
        public string Inds_Type { get; set; }
        public string Rgt_capt_amt { get; set; }
        public string Stockholder { get; set; }
        public string Ctac_Title1 { get; set; }
        public string Ctac_Title2 { get; set; }
        public string Ctac_Title3 { get; set; }
        public string Ctac_Title4 { get; set; }
        public string Main_Product { get; set; }
        public Nullable<double> Hold_Ratio { get; set; }
        public string Inc_Tel { get; set; }
        public Nullable<double> Sale_net_amt { get; set; }
        public Nullable<double> Gross_Ratio { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<double> EPS { get; set; }
        public Nullable<double> Fluid_Ratio { get; set; }
        public Nullable<double> Debt_Ratio { get; set; }
        public Nullable<double> Interest_DBL { get; set; }
        public Nullable<double> ENV { get; set; }
        public Nullable<double> Day20_Share { get; set; }
        public Nullable<double> Day60_Share { get; set; }
        public Nullable<double> Jail_Ratio { get; set; }
        public Nullable<double> PBR { get; set; }
        public string Visit_Parley { get; set; }
        public string Add_Comment { get; set; }
        public string Direct { get; set; }
        public string FailScr { get; set; }
        public Nullable<double> Sale_Net_Amt2 { get; set; }
        public Nullable<double> Gross_Ratio2 { get; set; }
        public Nullable<double> Profit2 { get; set; }
        public Nullable<double> EPS2 { get; set; }
        public Nullable<double> Fluid_Ratio2 { get; set; }
        public Nullable<double> Debt_Ratio2 { get; set; }
        public Nullable<double> Interest_DBL2 { get; set; }
        public Nullable<double> ENV2 { get; set; }
        public string Profit_Year { get; set; }
        public string Profit_Year2 { get; set; }
        public string BS_Year { get; set; }
        public string BS_Year2 { get; set; }
        public string CTAC_ADDR { get; set; }
        public string Cust_no { get; set; }
        public string Taker { get; set; }
        public Nullable<double> EBITDA { get; set; }
        public string EBITDA2 { get; set; }
        public string Other { get; set; }
        public Nullable<double> volatility { get; set; }
        public string DEPT { get; set; }
    }
}
