//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedUnit
    {
        public int Num { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string Shop_Employee { get; set; }
        public string ShopID { get; set; }
        public string Deal_Employee { get; set; }
        public string DealID { get; set; }
        public string Add_Employee { get; set; }
        public Nullable<System.DateTime> Add_Date { get; set; }
    }
}
