//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCED_CODE
    {
        public string ORD_CLASS { get; set; }
        public string ORD_NAME { get; set; }
        public string ORD_COM { get; set; }
        public string ORD_SCR { get; set; }
        public string ORC_590 { get; set; }
        public string A20_No { get; set; }
        public string SignYN { get; set; }
        public string OTC_CustName { get; set; }
        public string Tshow { get; set; }
        public string Object { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
    }
}
