//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Pro_Num { get; set; }
        public string Pro_Name { get; set; }
        public Nullable<System.DateTime> Pro_Ndate { get; set; }
        public Nullable<System.DateTime> Pro_Edate { get; set; }
        public Nullable<bool> Pro_Time { get; set; }
        public string Pro_Scr { get; set; }
        public Nullable<int> Pro_Spare { get; set; }
        public string Pro_Pic { get; set; }
        public string Pro_Price { get; set; }
        public string Pro_Show { get; set; }
        public string Pro_Rule { get; set; }
        public Nullable<int> Pro_Amount { get; set; }
        public string Pro_Unit { get; set; }
        public string Pro_State { get; set; }
        public Nullable<int> Pro_Limit { get; set; }
        public string Pro_Renew { get; set; }
    }
}
