//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCF099
    {
        public string cust_no { get; set; }
        public string end_date { get; set; }
        public Nullable<decimal> hire_tot { get; set; }
        public Nullable<decimal> party_tot { get; set; }
        public Nullable<decimal> otc_tot { get; set; }
        public string bloc_no { get; set; }
    }
}
