//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonMail
    {
        public string Rm_Dept { get; set; }
        public string Rm_EmpId { get; set; }
        public string Rm_Name { get; set; }
        public Nullable<int> Rm_Time { get; set; }
        public string Rm_mail { get; set; }
        public int Num { get; set; }
    }
}
