//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordMain
    {
        public int 自動編號 { get; set; }
        public string 借用編號 { get; set; }
        public Nullable<int> 錄音筆編號 { get; set; }
        public string 借用人 { get; set; }
        public string 借用目的 { get; set; }
        public Nullable<System.DateTime> 使用日期 { get; set; }
        public string 開始時間 { get; set; }
        public string 結束時間 { get; set; }
        public Nullable<System.DateTime> 例行結束日 { get; set; }
        public string 例行類型 { get; set; }
        public string 星期 { get; set; }
        public Nullable<System.DateTime> 借用日期 { get; set; }
        public string 建檔人 { get; set; }
        public string 建檔人編號 { get; set; }
        public Nullable<System.DateTime> Car_Return { get; set; }
        public string Car_Company { get; set; }
        public string Car_USB { get; set; }
        public Nullable<System.DateTime> Car_Out { get; set; }
    }
}
