//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALEDEPCU
    {
        public int Cus_Num { get; set; }
        public string Cus_Name { get; set; }
        public string Cus_Unite { get; set; }
        public Nullable<int> Cus_Type { get; set; }
        public string Cus_Other { get; set; }
        public string Cus_Tel1 { get; set; }
        public string Cus_Tel2 { get; set; }
        public string Cus_Liaise { get; set; }
        public string Cus_Fax { get; set; }
        public string Cus_Action { get; set; }
        public string Cus_Address { get; set; }
        public string Cus_Scr { get; set; }
        public string Cus_Renew { get; set; }
        public Nullable<System.DateTime> Cus_Update { get; set; }
        public string Cus_Creat { get; set; }
        public string Cus_Company { get; set; }
        public string Cus_Dep { get; set; }
    }
}
