//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int 自動編號 { get; set; }
        public string 報修人帳號 { get; set; }
        public string 報修人姓名 { get; set; }
        public string 報修主旨 { get; set; }
        public string 報修內容 { get; set; }
        public string 附檔 { get; set; }
        public Nullable<System.DateTime> 報修日期 { get; set; }
        public string 處理結果 { get; set; }
        public string 處理人姓名 { get; set; }
        public Nullable<System.DateTime> 處理日期 { get; set; }
        public string 完成說明 { get; set; }
        public string 完成人姓名 { get; set; }
        public Nullable<System.DateTime> 完成日期 { get; set; }
        public string 附件 { get; set; }
        public string 備註 { get; set; }
        public string 功能別 { get; set; }
        public string 建檔人帳號 { get; set; }
        public string 處理狀態 { get; set; }
        public string 標示刪除 { get; set; }
        public Nullable<int> 報修類別代號 { get; set; }
        public string 主管簽核 { get; set; }
        public Nullable<System.DateTime> 核準日期 { get; set; }
        public string 簽呈編號 { get; set; }
        public string 作廢人 { get; set; }
        public Nullable<System.DateTime> 作廢日期 { get; set; }
        public string 營業員 { get; set; }
        public string 契約編號 { get; set; }
        public string 財務副總 { get; set; }
        public Nullable<System.DateTime> 副總核準日期 { get; set; }
        public string 協理 { get; set; }
        public Nullable<System.DateTime> 協理核準日期 { get; set; }
        public Nullable<double> 處理時數 { get; set; }
    }
}
