//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public int 報修類別代號 { get; set; }
        public string 報修類別名稱 { get; set; }
        public string 報修層級 { get; set; }
        public string 報修等級 { get; set; }
        public string 公司別 { get; set; }
    }
}
