//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_CAROrder
    {
        public string Order_No { get; set; }
        public string Cust_no { get; set; }
        public string Cust_Name { get; set; }
        public string CTAC { get; set; }
        public string Inc_Tel { get; set; }
        public string SEND_Cause { get; set; }
        public string Sign_No { get; set; }
        public string Car_No { get; set; }
        public string Sour_licence_Type { get; set; }
        public Nullable<System.DateTime> Visit_Date_Br { get; set; }
        public Nullable<System.DateTime> Visit_Date_Back { get; set; }
        public string Sour_Code { get; set; }
        public string licence_Type { get; set; }
        public string New_Car_No { get; set; }
        public string Other_Car_No { get; set; }
        public string Car_Type { get; set; }
        public string Other_Car_Type { get; set; }
        public string Doc_Status { get; set; }
        public string transfer_ID { get; set; }
        public Nullable<double> COST { get; set; }
        public string MEMO { get; set; }
        public string GET_PST { get; set; }
        public string GET_Name { get; set; }
        public string GET_ID { get; set; }
        public string GET_APLY_NAME { get; set; }
        public string SEND_PST { get; set; }
        public string special_Need { get; set; }
        public string Aply_Dept { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string Other_licence_Type { get; set; }
        public Nullable<double> UserDays { get; set; }
        public string Visit_Time_Br { get; set; }
        public string Visit_Time_Back { get; set; }
        public Nullable<int> CostDay_L { get; set; }
        public Nullable<int> CostDay_H { get; set; }
        public Nullable<int> CostDay_SH { get; set; }
        public Nullable<double> Cost_Hire { get; set; }
        public Nullable<double> Cost_RabiteL { get; set; }
        public Nullable<double> Cost_RabiteH { get; set; }
        public Nullable<double> Cost_RabiteSH { get; set; }
        public string Fax_No { get; set; }
        public string Send_YN { get; set; }
        public string Back_PST { get; set; }
        public string Proced_aply_no { get; set; }
        public string mobile_no { get; set; }
        public string RndNum { get; set; }
        public Nullable<double> Cost_Other { get; set; }
        public string Cost_Scr { get; set; }
        public string SendMessageID { get; set; }
        public string MIS_Scr { get; set; }
        public Nullable<double> OverTimeHour { get; set; }
    }
}
