//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_licence
    {
        public string LicenceNo { get; set; }
        public Nullable<int> Licence_Type { get; set; }
        public string UserClass { get; set; }
        public string Pub_Pst { get; set; }
        public string Use_Year { get; set; }
        public Nullable<double> Use_Mileage { get; set; }
        public Nullable<double> demage_a { get; set; }
        public Nullable<double> demage_b { get; set; }
        public Nullable<double> demage_c { get; set; }
        public Nullable<double> demage_d { get; set; }
        public Nullable<double> demage_e { get; set; }
        public Nullable<double> demage_f { get; set; }
        public Nullable<double> demage_g { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string OrderYN { get; set; }
        public string con_Sdate { get; set; }
        public string con_Edate { get; set; }
        public string YN { get; set; }
        public string con_kind { get; set; }
        public string Over_Time { get; set; }
        public string con_arrv { get; set; }
    }
}
