//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Amount
    {
        public string QUOT_NO { get; set; }
        public string Start_Date { get; set; }
        public int ctpaytrm { get; set; }
        public Nullable<double> R_AMOUNT { get; set; }
        public string CTPAYDAT { get; set; }
        public string PRESS_Scr { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string YN { get; set; }
        public int Open_Time { get; set; }
    }
}
