//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Self
    {
        public string QUOT_NO { get; set; }
        public string CUST_NO { get; set; }
        public string PILOT_NAME { get; set; }
        public string PILOT_ID { get; set; }
        public string PILOT_PHONE { get; set; }
        public string PILOT_TEL { get; set; }
        public string Licence_Type { get; set; }
        public Nullable<System.DateTime> Visit_Date_Br { get; set; }
        public Nullable<System.DateTime> Visit_Date_Back { get; set; }
        public string Get_Pst { get; set; }
        public string Back_Pst { get; set; }
        public string Do_STS { get; set; }
        public string Fee_Type { get; set; }
        public string Aply_YN { get; set; }
        public Nullable<double> Get_Money { get; set; }
        public Nullable<double> One_Way_mileage { get; set; }
        public Nullable<double> oil_Fees { get; set; }
        public Nullable<double> Armor_Rent { get; set; }
        public Nullable<double> Send_Fees { get; set; }
        public Nullable<double> GPS { get; set; }
        public Nullable<double> Over_Time_Fees { get; set; }
        public Nullable<double> Balance_Fees { get; set; }
        public string Pay_Way { get; set; }
        public string Case_Sour { get; set; }
        public string Bonus_Back { get; set; }
        public string Pay_Mode { get; set; }
        public string OSS { get; set; }
        public string Dept_No { get; set; }
        public string Agent { get; set; }
        public string Special_needScr { get; set; }
        public Nullable<double> LevelDay { get; set; }
        public Nullable<double> Hoilday { get; set; }
        public Nullable<double> LevelHire { get; set; }
        public Nullable<double> HolidayHire { get; set; }
        public Nullable<double> Rabite_L { get; set; }
        public Nullable<double> Rabite_H { get; set; }
        public string Visit_Time_Br { get; set; }
        public string Visit_Time_Back { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public Nullable<double> spec_Redu { get; set; }
        public Nullable<double> New_Redu { get; set; }
        public string Close_Case { get; set; }
        public Nullable<double> Start_Collection { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public Nullable<double> Back_Collection { get; set; }
        public Nullable<System.DateTime> Back_Date { get; set; }
        public string Scr { get; set; }
        public string Aply_no { get; set; }
        public string INVO_NO { get; set; }
        public string INVO_Date { get; set; }
        public string Send_Date { get; set; }
        public Nullable<double> R_AMOUNT { get; set; }
        public string CTPAYDAT { get; set; }
        public string PRESS_Scr { get; set; }
        public Nullable<double> Rebate { get; set; }
        public string SHoilday { get; set; }
        public Nullable<double> Rabite_SH { get; set; }
        public Nullable<System.DateTime> OverTime_Date { get; set; }
        public string CTAC { get; set; }
        public string Boss_Tel { get; set; }
        public string Fax_No { get; set; }
        public string CaseAplyScr { get; set; }
        public string INV_STS { get; set; }
        public string INV_Scr { get; set; }
        public Nullable<double> PERIOD { get; set; }
        public string CreditCard { get; set; }
        public string RCV_Case { get; set; }
        public string T201_id { get; set; }
        public string T201_date { get; set; }
        public string T201_Time { get; set; }
        public Nullable<System.DateTime> CreditDate { get; set; }
        public string Rcv_Scr { get; set; }
        public string ACCT_Type { get; set; }
        public string assistant { get; set; }
    }
}
