//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_SendCar
    {
        public string Order_No { get; set; }
        public Nullable<System.DateTime> malleability_Date { get; set; }
        public string special_Scr { get; set; }
        public string SendCar_STS { get; set; }
        public Nullable<System.DateTime> Car_EXE_Date { get; set; }
        public Nullable<double> Sour_Mileage { get; set; }
        public Nullable<System.DateTime> Car_EXEBack_Date { get; set; }
        public Nullable<double> Return_Mileage { get; set; }
        public Nullable<double> Vend_Collection { get; set; }
        public string FEE_YN { get; set; }
        public Nullable<double> Self_Money { get; set; }
        public Nullable<double> Build_Money { get; set; }
        public Nullable<double> Loss_Business { get; set; }
        public Nullable<double> Oth_AMT { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> IN_Date { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string CaseYN { get; set; }
        public string Same_YN { get; set; }
        public string Car_EXE_Time { get; set; }
        public string Car_EXEBack_Time { get; set; }
        public string ARP_No { get; set; }
        public string malleability_Time { get; set; }
        public Nullable<double> ETAG { get; set; }
        public string ETAG_Pay { get; set; }
        public string ETAG_NO { get; set; }
        public string ETAG_CreditCard { get; set; }
        public Nullable<System.DateTime> ETAG_CreditDate { get; set; }
        public string CarReturnYN { get; set; }
        public string Car_File { get; set; }
    }
}
