//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_ReporderScr
    {
        public string Order_No { get; set; }
        public string Sch_Class { get; set; }
        public string Sch_Item { get; set; }
        public Nullable<System.DateTime> Sch_Date { get; set; }
        public string Sch_Time { get; set; }
        public Nullable<double> Sch_Mony { get; set; }
        public string Sch_Flight { get; set; }
        public Nullable<System.DateTime> NOTY_DATE { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Entry_ID1 { get; set; }
        public string Entry_Date1 { get; set; }
        public string Entry_Time1 { get; set; }
        public string Car_Type { get; set; }
        public Nullable<double> Across_Add { get; set; }
        public string Meet_Addr { get; set; }
        public int SEQ { get; set; }
        public Nullable<int> Hour_Total { get; set; }
        public Nullable<double> Hour_Money { get; set; }
        public Nullable<System.DateTime> Seat_Time { get; set; }
        public Nullable<double> Cost_Scr { get; set; }
    }
}
