//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_AReporder
    {
        public string Order_No { get; set; }
        public string Entry_Dept { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Modify_ID { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public string Gen_ID { get; set; }
        public string Gen_Dirver { get; set; }
        public string Gen_Phone { get; set; }
        public string Licence_No { get; set; }
        public Nullable<System.DateTime> Gen_Date { get; set; }
        public string Gen_DTime { get; set; }
        public Nullable<double> Gen_PassWay { get; set; }
        public Nullable<double> Gen_Stop { get; set; }
        public Nullable<double> Gen_PaseTime { get; set; }
        public Nullable<double> Gen_Time { get; set; }
        public Nullable<double> Gen_Across { get; set; }
        public Nullable<double> Gen_Other { get; set; }
        public Nullable<double> Gen_Collection { get; set; }
        public Nullable<System.DateTime> Gen_OverDate { get; set; }
        public string Gen_OverTime { get; set; }
        public Nullable<System.DateTime> Noty_Date { get; set; }
        public Nullable<System.DateTime> Send_Date { get; set; }
    }
}
