//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Order
    {
        public string Count_Type { get; set; }
        public int Licence_Type { get; set; }
        public string type_Name { get; set; }
        public Nullable<double> Hire { get; set; }
        public Nullable<double> Hire1 { get; set; }
        public Nullable<double> Hire3 { get; set; }
        public Nullable<double> Hire6 { get; set; }
        public Nullable<double> Hire10 { get; set; }
        public Nullable<double> HireH { get; set; }
        public Nullable<double> HireS { get; set; }
        public Nullable<double> Limit_milrage { get; set; }
        public Nullable<double> Over_Mile_amt { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public string StopYN { get; set; }
        public int SEQ { get; set; }
    }
}
