//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_ReporderSeat
    {
        public string Order_No { get; set; }
        public string Gen_ID { get; set; }
        public string Gen_Driver { get; set; }
        public string Licence_No { get; set; }
        public string Gen_Phone { get; set; }
        public Nullable<System.DateTime> Gen_Date { get; set; }
        public string Gen_Time { get; set; }
        public Nullable<double> Gen_PassWay { get; set; }
        public Nullable<double> Gen_Stop { get; set; }
        public Nullable<double> Gen_Meal { get; set; }
        public Nullable<double> Gen_OverTime { get; set; }
        public Nullable<double> Gen_PastTime { get; set; }
        public Nullable<double> Gen_across { get; set; }
        public Nullable<double> Gen_Other { get; set; }
        public Nullable<double> Gen_Collection { get; set; }
        public Nullable<System.DateTime> Gen_OverDate { get; set; }
        public string Gen_OverTimeE { get; set; }
        public Nullable<double> Gen_Cost { get; set; }
        public string Entry_ID { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Modify_ID { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public string ARP_No { get; set; }
        public int SEQ { get; set; }
        public string Car_Name1 { get; set; }
        public string Car_Name2 { get; set; }
        public Nullable<int> Car_Person { get; set; }
        public string Car_Tel1 { get; set; }
        public string Car_Tel2 { get; set; }
        public string Car_Pay { get; set; }
        public string Pay_Type { get; set; }
        public string Scr_Need { get; set; }
        public string INV_STS { get; set; }
        public string INV_Scr { get; set; }
        public Nullable<double> Vend_Collection { get; set; }
        public string Car_Name3 { get; set; }
        public string Car_Tel3 { get; set; }
        public Nullable<double> Cost { get; set; }
        public string CreditCard { get; set; }
        public Nullable<System.DateTime> CreditDate { get; set; }
        public string Car_Name4 { get; set; }
        public string Car_Tel4 { get; set; }
        public string Case_Sour { get; set; }
        public string assistant { get; set; }
    }
}
