//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shart_Custom
    {
        public string Cust_Kind { get; set; }
        public string Cust_No { get; set; }
        public string Cust_Name { get; set; }
        public string Boss_Mobile { get; set; }
        public string Tel_no { get; set; }
        public string ACCT_Type { get; set; }
        public Nullable<double> Spec_Redu { get; set; }
        public Nullable<double> New_Redu { get; set; }
        public string Mail_Acct { get; set; }
        public string Boss_Date { get; set; }
        public string Sex_No { get; set; }
        public string Cust_Class { get; set; }
        public string CTAC { get; set; }
        public string Boss_Tel { get; set; }
        public string Fax_No { get; set; }
        public string Open_Postal { get; set; }
        public string Open_Addr { get; set; }
        public string ConFer_Post_no { get; set; }
        public string ConFer_Addr { get; set; }
        public string Inv_Post_No { get; set; }
        public string Inv_Addr { get; set; }
        public string Entry_Id { get; set; }
        public string Entry_Date { get; set; }
        public string Entry_Time { get; set; }
        public string Modify_Id { get; set; }
        public string Modify_Date { get; set; }
        public string Modify_Time { get; set; }
        public string Void { get; set; }
        public string Void_Name { get; set; }
        public Nullable<System.DateTime> Void_Date { get; set; }
        public string invo_kind { get; set; }
        public string Country_code { get; set; }
    }
}
