//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping
    {
        public int Shop_Num { get; set; }
        public Nullable<int> Pro_Num { get; set; }
        public string Shop_Dept { get; set; }
        public Nullable<System.DateTime> Shop_Date { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_Tel { get; set; }
        public string Shop_Tel2 { get; set; }
        public Nullable<int> Shop_Count { get; set; }
        public Nullable<int> Shop_Get { get; set; }
        public Nullable<int> Shop_Amount { get; set; }
        public string MAC { get; set; }
        public string Get_date { get; set; }
        public string Get_time { get; set; }
        public Nullable<decimal> Rec_money { get; set; }
    }
}
