//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL91
    {
        public int 序號 { get; set; }
        public string DAY { get; set; }
        public Nullable<short> CODE { get; set; }
        public string NUM { get; set; }
        public string NEW { get; set; }
        public string CUSTOMER { get; set; }
        public string 授權類別 { get; set; }
        public string ST { get; set; }
        public string ST1 { get; set; }
        public Nullable<short> TERM { get; set; }
        public Nullable<double> TR { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string SALES { get; set; }
        public string SALES1 { get; set; }
        public string SHARE { get; set; }
        public string SHARE1 { get; set; }
        public Nullable<double> S_R { get; set; }
        public Nullable<double> TAL { get; set; }
        public string MACHINE { get; set; }
        public string 標的物名稱 { get; set; }
        public string A_A { get; set; }
        public Nullable<double> CAPITA { get; set; }
        public Nullable<double> S_COST { get; set; }
        public Nullable<double> S_TOTAL { get; set; }
        public Nullable<double> S_AMT { get; set; }
        public Nullable<double> O_COST { get; set; }
        public Nullable<double> O_TOTAL { get; set; }
        public Nullable<double> O_AMT { get; set; }
        public Nullable<double> N_IN { get; set; }
        public Nullable<double> TERM_AD { get; set; }
        public Nullable<double> TR_AD { get; set; }
        public Nullable<double> OLD_AD { get; set; }
        public Nullable<double> DIS_AD { get; set; }
        public Nullable<double> ADJUSTMENT { get; set; }
        public Nullable<double> O_ADJUST { get; set; }
        public Nullable<double> S_ADJUST { get; set; }
        public string ADJUST { get; set; }
        public Nullable<double> FUND { get; set; }
        public Nullable<double> FUND_COST { get; set; }
        public Nullable<double> O_FUNDCOST { get; set; }
        public Nullable<double> S_FUNDCOST { get; set; }
        public string AD_TO { get; set; }
        public string ORIGINAL { get; set; }
        public string MEMO { get; set; }
        public Nullable<double> TRCOST { get; set; }
        public string DSCRPY { get; set; }
        public string DSCRPY_ME { get; set; }
        public string 前處理情形 { get; set; }
        public string 後處理情形 { get; set; }
        public Nullable<System.DateTime> SAVE_DATE { get; set; }
        public Nullable<System.DateTime> SAVE_TIME { get; set; }
        public Nullable<bool> FIX { get; set; }
        public string exculde { get; set; }
    }
}
