//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int Seq_No { get; set; }
        public Nullable<System.DateTime> APLY_DATE { get; set; }
        public string CUST_NAME { get; set; }
        public string CAR_NO { get; set; }
        public string Telegram { get; set; }
        public Nullable<int> Require_Code { get; set; }
        public string Describe { get; set; }
        public string DOC_Status { get; set; }
        public string Add_Name { get; set; }
        public string M_Worker { get; set; }
        public Nullable<System.DateTime> NoteChk { get; set; }
        public Nullable<System.DateTime> M_OutDate { get; set; }
        public string M_Content { get; set; }
        public Nullable<int> lineType { get; set; }
        public string DEPT { get; set; }
        public string assistant { get; set; }
        public string TEL { get; set; }
    }
}
