//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STM03
    {
        public string CORP_NO { get; set; }
        public string YYMM { get; set; }
        public string PROD_NO { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> ST_COST { get; set; }
        public Nullable<decimal> ADD_COST { get; set; }
        public Nullable<decimal> MIN_COST { get; set; }
        public Nullable<decimal> END_COST { get; set; }
        public string ENTRY_ID { get; set; }
        public string ENTRY_DATE { get; set; }
        public string ENTRY_TIME { get; set; }
        public string MODIFY_ID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string MODIFY_TIME { get; set; }
        public string ADD_OR_DEL { get; set; }
        public Nullable<decimal> ADJ_COST { get; set; }
    }
}
