//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OR_EMP
    {
        public string EMP_CODE { get; set; }
        public string SALESMAN_CODE { get; set; }
        public string ID_NO { get; set; }
        public string DEPT_CODE { get; set; }
        public string AUD_LVL_CODE { get; set; }
        public string OALT_LVL_CODE { get; set; }
        public string AMC_LVL_CODE { get; set; }
        public string OTC_LVL_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_ENAME { get; set; }
        public string JOB_NAME { get; set; }
        public string UPPER_BOSS { get; set; }
        public string CORP_ACCT { get; set; }
        public string JOB_AGENT { get; set; }
        public string MAIL_ACCT { get; set; }
        public string ICQ_NO { get; set; }
        public string OTH_ADDR { get; set; }
        public string EXT { get; set; }
        public string BANK_ACCT1 { get; set; }
        public string BANK_ACCT2 { get; set; }
        public string GRAD { get; set; }
        public string CAREER1 { get; set; }
        public string CAREER2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string MOBIL { get; set; }
        public string DOMI_ADDR { get; set; }
        public string ADDR { get; set; }
        public string BRTH_DATE { get; set; }
        public string APPO_DATE { get; set; }
        public string QUIT_DATE { get; set; }
        public string PSUR_CTAC_NAME { get; set; }
        public string PSUR_CTAC_TEL { get; set; }
        public string PICTURE { get; set; }
        public string OFF_LOC { get; set; }
        public string NET_LOC { get; set; }
        public string INC_STS { get; set; }
        public string ADD_USER_ID { get; set; }
        public string ADD_DATE { get; set; }
        public string ADD_TIME { get; set; }
        public string LAST_UPD_USER_ID { get; set; }
        public string LAST_UPD_DATE { get; set; }
        public string LAST_UPD_TIME { get; set; }
    }
}
