//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_rent_hist
    {
        public string CORP_NO { get; set; }
        public string ACEP_NO { get; set; }
        public string DATA_SEQ { get; set; }
        public string RECP_NO { get; set; }
        public string RECP_SEQ { get; set; }
        public string SALE_NO { get; set; }
        public string INVO_NO { get; set; }
        public string CUST_NO { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<decimal> CAN_AMT { get; set; }
        public string CHEQ_NO { get; set; }
        public string DUE_DATE { get; set; }
        public string CHEQ_MAN { get; set; }
        public string ACEP_DATE { get; set; }
        public string USCACCT_CODE { get; set; }
    }
}
