//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WB6621
    {
        public int Leave_IDNO { get; set; }
        public string ID_NO { get; set; }
        public string LeaveMnrCode { get; set; }
        public string Name { get; set; }
        public string OrganizeCode { get; set; }
        public string LeavePS { get; set; }
        public string LeavePE { get; set; }
        public string LeaveTS { get; set; }
        public string LeaveTE { get; set; }
        public string LeavePD { get; set; }
        public string LeavePT { get; set; }
        public string ReMark { get; set; }
        public string DeleteReMark { get; set; }
        public Nullable<System.DateTime> LastModeDate { get; set; }
        public string LastModePs { get; set; }
        public string Inputdate { get; set; }
        public string LeabeManner { get; set; }
        public string WorkingTime { get; set; }
        public string WorkReadHr { get; set; }
        public string EmployeeNo { get; set; }
        public string LeaveTime { get; set; }
        public string SalaryMonth { get; set; }
        public string TurnTeamcode { get; set; }
    }
}
