//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkRecord
    {
        public int SEQ { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string Peak_Time { get; set; }
        public string Cust_Name { get; set; }
        public string Target { get; set; }
        public string entry_id { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string dept_Code { get; set; }
        public string Boss { get; set; }
        public string Cur_STS { get; set; }
        public Nullable<System.DateTime> Crd_DelDate { get; set; }
        public string Crd_Del { get; set; }
        public string modify_id { get; set; }
        public string modify_date { get; set; }
        public string modify_time { get; set; }
        public Nullable<int> Class { get; set; }
        public string memo1 { get; set; }
        public string Case_Sour { get; set; }
        public Nullable<double> TRAN_AMT { get; set; }
    }
}
