//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearHoliday
    {
        public int EYear_Num { get; set; }
        public string EYear_EmpID { get; set; }
        public string EYear_Name { get; set; }
        public string EYear_ID { get; set; }
        public Nullable<double> EYear_Day { get; set; }
        public string EYear_Money { get; set; }
        public string EYear_Renew { get; set; }
        public Nullable<System.DateTime> EYear_Update { get; set; }
        public double EYear { get; set; }
        public Nullable<double> EYear_Now { get; set; }
    }
}
