//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class 員工
    {
        public string 員工識別碼 { get; set; }
        public string 公司別 { get; set; }
        public string 身分證字號 { get; set; }
        public string 部門或科系代碼 { get; set; }
        public string 職稱 { get; set; }
        public string 中文姓名 { get; set; }
        public string 英文姓名 { get; set; }
        public string 社內帳號 { get; set; }
        public string 電子郵件帳號 { get; set; }
        public string 電腦編號 { get; set; }
        public string 分機 { get; set; }
        public string 電話1 { get; set; }
        public string 電話2 { get; set; }
        public string 手機 { get; set; }
        public string 地址 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public Nullable<System.DateTime> 雇用日期 { get; set; }
        public string 緊急聯絡人姓名 { get; set; }
        public string 緊急聯絡人電話 { get; set; }
        public byte[] 照片 { get; set; }
        public string 辦公室位置 { get; set; }
        public string 網路位址 { get; set; }
        public Nullable<bool> 在職狀況 { get; set; }
        public Nullable<bool> 調查表簽回 { get; set; }
        public string 郵件主機 { get; set; }
        public string bbs帳號 { get; set; }
        public string 門禁卡號 { get; set; }
        public string C1F門禁卡號 { get; set; }
        public int Num { get; set; }
        public string 出勤記錄 { get; set; }
    }
}
