//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrixModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class 郵件帳號_
    {
        public int id { get; set; }
        public string 公司 { get; set; }
        public string 名字 { get; set; }
        public string 電子郵件 { get; set; }
        public string 商務電話 { get; set; }
        public string 行動電話 { get; set; }
        public string 住家電話 { get; set; }
        public string 部門 { get; set; }
    }
}
